// Copyright (c) Microsoft. All rights reserved.

// This sample shows how to download files generated by Code Interpreter using
// the OpenAI Containers API. Container files cannot be downloaded through the
// standard Files API; both the container ID and file ID are required.
package main

import (
	"cmp"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/microsoft/agent-framework-go/agent"
	"github.com/microsoft/agent-framework-go/examples/internal/demo"
	"github.com/microsoft/agent-framework-go/message"
	"github.com/microsoft/agent-framework-go/provider/openaiprovider"
	"github.com/microsoft/agent-framework-go/tool"
	"github.com/microsoft/agent-framework-go/tool/hostedtool"
	"github.com/openai/openai-go/v3"
)

var model = cmp.Or(strings.TrimSpace(os.Getenv("OPENAI_CHAT_MODEL_NAME")), "gpt-4o-mini")

var logger = demo.NewLogger(
	"OpenAI Code Interpreter File Download",
	"Generates a file with Code Interpreter and downloads it through the Containers API.",
	"Model", model,
)

func main() {
	ctx := context.Background()
	client := openai.NewClient()

	a := openaiprovider.NewResponsesAgent(
		client,
		openaiprovider.AgentConfig{
			Model:        model,
			Instructions: "You are a helpful assistant that can generate files using code.",
			Config: agent.Config{
				Name:        "CodeInterpreterAgent",
				Middlewares: []agent.Middleware{logger},
				Tools:       []tool.Tool{&hostedtool.CodeInterpreter{}},
			},
		},
	)

	resp, err := a.RunText(ctx, "Create a CSV file named multiplication-table.csv with the multiplication tables from 1 to 12. Include headers and provide the file for download.").Collect()
	if err != nil {
		demo.Panic(err)
	}
	demo.Response(resp, nil)

	files := containerFiles(resp)
	if len(files) == 0 {
		demo.Assistant("No container file citations found in the response.")
		demo.Assistant("The model may not have generated a downloadable file for this prompt.")
		return
	}

	downloadDir, err := os.MkdirTemp("", "agent-framework-code-interpreter-")
	if err != nil {
		demo.Panic(err)
	}
	demo.Assistantf("Download directory: %s", downloadDir)

	for _, file := range files {
		demo.Assistantf("Downloading container file: %s", file.filename)
		demo.Assistantf("  Container ID: %s", file.containerID)
		demo.Assistantf("  File ID:      %s", file.fileID)

		outputPath, err := downloadContainerFile(ctx, &client, downloadDir, file)
		if err != nil {
			demo.Panic(err)
		}
		demo.Assistantf("  Saved to:     %s", outputPath)
	}
}

type containerFile struct {
	containerID string
	fileID      string
	filename    string
}

func containerFiles(resp *agent.Response) []containerFile {
	seen := make(map[string]struct{})
	var files []containerFile
	for content := range resp.Contents() {
		for _, annotation := range content.Header().Annotations {
			citation, ok := annotation.(*message.CitationAnnotation)
			if !ok || citation.FileID == "" {
				continue
			}
			containerID, _ := citation.AdditionalProperties["ContainerId"].(string)
			if containerID == "" {
				continue
			}

			key := containerID + "/" + citation.FileID
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}
			files = append(files, containerFile{
				containerID: containerID,
				fileID:      citation.FileID,
				filename:    citation.Title,
			})
		}
	}
	return files
}

func downloadContainerFile(ctx context.Context, client *openai.Client, outputDir string, file containerFile) (string, error) {
	response, err := client.Containers.Files.Content.Get(ctx, file.containerID, file.fileID)
	if err != nil {
		return "", fmt.Errorf("download container file %q: %w", file.fileID, err)
	}
	defer response.Body.Close()

	filename := filepath.Base(strings.TrimSpace(file.filename))
	if filename == "" || filename == "." || filename == ".." || filename == string(filepath.Separator) {
		filename = file.fileID
	}
	outputPath := filepath.Join(outputDir, filename)

	output, err := os.Create(outputPath)
	if err != nil {
		return "", fmt.Errorf("create output file %q: %w", outputPath, err)
	}
	if _, err := io.Copy(output, response.Body); err != nil {
		_ = output.Close()
		_ = os.Remove(outputPath)
		return "", fmt.Errorf("write output file %q: %w", outputPath, err)
	}
	if err := output.Close(); err != nil {
		_ = os.Remove(outputPath)
		return "", fmt.Errorf("close output file %q: %w", outputPath, err)
	}

	return outputPath, nil
}
