// Copyright (c) Microsoft. All rights reserved.

package workflow

import (
	"errors"
	"iter"
	"slices"
)

type Edge struct {
	Index int

	Connection EdgeConnection

	// EdgeAssigned is an optional function that maps an incoming message to a subset of the target
	// executor nodes (or optionally all of them).
	// If nil, all destination nodes are selected.
	// Only used for fan out edges.
	EdgeAssigned func(int, any) iter.Seq[int]

	// Condition is an optional predicate determining whether the edge is active for a given message.
	// If nil, the edge is always active when a message is generated by the source.
	// Only used for direct edges.
	Condition func(any) bool
}

// Equal reports whether this Edge is equal to another Edge
// without considering the Index field.
func (e Edge) Equal(other Edge) bool {
	if (e.Condition == nil) != (other.Condition == nil) {
		return false
	}
	if (e.EdgeAssigned == nil) != (other.EdgeAssigned == nil) {
		return false
	}
	if !e.Connection.Equal(other.Connection) {
		return false
	}
	return true
}

// EdgeConnection is a representation for the connection structure of an edge of any multiplicity,
// defined by an ordered list of sources and sinks connected by this edge.
type EdgeConnection struct {
	SourceIDs []string
	SinkIDs   []string
}

func (c EdgeConnection) Equal(other EdgeConnection) bool {
	return slices.Equal(c.SourceIDs, other.SourceIDs) && slices.Equal(c.SinkIDs, other.SinkIDs)
}

// NewConnection creates a new Connection ensuring that source and sink IDs are unique.
func NewConnection(sourceIDs, sinkIDs []string) (EdgeConnection, error) {
	ids := make(map[string]struct{}, max(len(sourceIDs), len(sinkIDs)))
	for _, id := range sourceIDs {
		if _, exists := ids[id]; exists {
			return EdgeConnection{}, errors.New("sourceIDs must be unique")
		}
		ids[id] = struct{}{}
	}
	clear(ids)
	for _, id := range sinkIDs {
		if _, exists := ids[id]; exists {
			return EdgeConnection{}, errors.New("sinkIDs must be unique and not overlap with sourceIDs")
		}
		ids[id] = struct{}{}
	}

	return EdgeConnection{
		SourceIDs: sourceIDs,
		SinkIDs:   sinkIDs,
	}, nil
}
