// Copyright (c) Microsoft. All rights reserved.

package workflow

import (
	"iter"
	"slices"
)

// EdgeOption configures an [Edge] when it is added to a workflow via [Builder].
type EdgeOption func(*Edge)

// WithEdgeLabel sets an optional label on the edge. Labels can be used by
// visualizers to annotate edges.
func WithEdgeLabel(label string) EdgeOption {
	return func(e *Edge) { e.Label = label }
}

// WithEdgeAssigner attaches an [Edge.Assigner] callback to a fan-out edge.
// The assigner is invoked for each message and must return the indexes of
// the targets that should receive it. Has no effect on direct or fan-in
// edges.
func WithEdgeAssigner(assigner func(targetCount int, message any) iter.Seq[int]) EdgeOption {
	return func(e *Edge) { e.Assigner = assigner }
}

func applyEdgeOptions(e *Edge, opts []EdgeOption) {
	for _, opt := range opts {
		if opt != nil {
			opt(e)
		}
	}
}

// Edge represents a connection or relationship between nodes.
type Edge struct {
	Index int

	Connection EdgeConnection

	// Label is an optional label for the edge, allowing arbitrary metadata
	// to be associated with it (e.g. for visualization purposes).
	Label string

	// Assigner is an optional function that maps an incoming message to a subset of the target
	// executor nodes (or optionally all of them).
	// If nil, all destination nodes are selected.
	// Only used for fan out edges.
	Assigner func(int, any) iter.Seq[int]

	// Condition is an optional predicate determining whether the edge is active for a given message.
	// If nil, the edge is always active when a message is generated by the source.
	// Only used for direct edges.
	Condition func(any) bool
}

// Equal reports whether this Edge is equal to another Edge
// without considering the Index field.
func (e Edge) Equal(other Edge) bool {
	if (e.Condition == nil) != (other.Condition == nil) {
		return false
	}
	if (e.Assigner == nil) != (other.Assigner == nil) {
		return false
	}
	if e.Label != other.Label {
		return false
	}
	if !e.Connection.Equal(other.Connection) {
		return false
	}
	return true
}

// EdgeConnection is a representation for the connection structure of an edge of any multiplicity,
// defined by an ordered list of sources and sinks connected by this edge.
type EdgeConnection struct {
	SourceIDs []string
	SinkIDs   []string
}

func (c EdgeConnection) Equal(other EdgeConnection) bool {
	return slices.Equal(c.SourceIDs, other.SourceIDs) && slices.Equal(c.SinkIDs, other.SinkIDs)
}
