version: "2"
linters:
  enable:
    - bodyclose
    - nakedret
    - predeclared
    - unconvert
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - staticcheck
        text: "SA5011"
formatters:
  enable:
    - gofumpt
