// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import "github.com/Azure/azure-sdk-for-go/sdk/azcore"

// Client contains the methods for the service.
// Don't use this type directly, use a constructor function instead.
type Client struct {
	internal *azcore.Client
	endpoint string
}

// NewConnectionsClient creates a new instance of [ConnectionsClient].
func (client *Client) NewConnectionsClient() *ConnectionsClient {
	return &ConnectionsClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewDatasetsClient creates a new instance of [DatasetsClient].
func (client *Client) NewDatasetsClient() *DatasetsClient {
	return &DatasetsClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewDeploymentsClient creates a new instance of [DeploymentsClient].
func (client *Client) NewDeploymentsClient() *DeploymentsClient {
	return &DeploymentsClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewEvaluationRulesClient creates a new instance of [EvaluationRulesClient].
func (client *Client) NewEvaluationRulesClient() *EvaluationRulesClient {
	return &EvaluationRulesClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewEvaluationTaxonomiesClient creates a new instance of [EvaluationTaxonomiesClient].
func (client *Client) NewEvaluationTaxonomiesClient() *EvaluationTaxonomiesClient {
	return &EvaluationTaxonomiesClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewEvaluatorGenerationJobsClient creates a new instance of [EvaluatorGenerationJobsClient].
func (client *Client) NewEvaluatorGenerationJobsClient() *EvaluatorGenerationJobsClient {
	return &EvaluatorGenerationJobsClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewEvaluatorsClient creates a new instance of [EvaluatorsClient].
func (client *Client) NewEvaluatorsClient() *EvaluatorsClient {
	return &EvaluatorsClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewIndexesClient creates a new instance of [IndexesClient].
func (client *Client) NewIndexesClient() *IndexesClient {
	return &IndexesClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewInsightsClient creates a new instance of [InsightsClient].
func (client *Client) NewInsightsClient() *InsightsClient {
	return &InsightsClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewMemoryStoresClient creates a new instance of [MemoryStoresClient].
func (client *Client) NewMemoryStoresClient() *MemoryStoresClient {
	return &MemoryStoresClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewRedTeamsClient creates a new instance of [RedTeamsClient].
func (client *Client) NewRedTeamsClient() *RedTeamsClient {
	return &RedTeamsClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewSchedulesClient creates a new instance of [SchedulesClient].
func (client *Client) NewSchedulesClient() *SchedulesClient {
	return &SchedulesClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewToolboxesClient creates a new instance of [ToolboxesClient].
func (client *Client) NewToolboxesClient() *ToolboxesClient {
	return &ToolboxesClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}
