// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// ConnectionsClient contains the methods for the Connections group.
// Don't use this type directly, use [Client.NewConnectionsClient] instead.
//
// Generated from API version v1
type ConnectionsClient struct {
	internal *azcore.Client
	endpoint string
}

// NewListPager - List connections
//
// Returns the connections available in the current project, optionally filtered by type or default status.
//   - options - ConnectionsClientListOptions contains the optional parameters for the ConnectionsClient.NewListPager method.
func (client *ConnectionsClient) NewListPager(options *ConnectionsClientListOptions) *runtime.Pager[ConnectionsClientListResponse] {
	return runtime.NewPager(runtime.PagingHandler[ConnectionsClientListResponse]{
		More: func(page ConnectionsClientListResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *ConnectionsClientListResponse) (ConnectionsClientListResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listCreateRequest(ctx, options)
			}, nil)
			if err != nil {
				return ConnectionsClientListResponse{}, err
			}
			return client.listHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listCreateRequest creates the List request.
func (client *ConnectionsClient) listCreateRequest(ctx context.Context, options *ConnectionsClientListOptions) (*policy.Request, error) {
	urlPath := "/connections"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	if options != nil && options.ConnectionType != nil {
		reqQP.Set("connectionType", string(*options.ConnectionType))
	}
	if options != nil && options.DefaultConnection != nil {
		reqQP.Set("defaultConnection", strconv.FormatBool(*options.DefaultConnection))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.ClientRequestID != nil {
		req.Raw().Header["x-ms-client-request-id"] = []string{*options.ClientRequestID}
	}
	return req, nil
}

// listHandleResponse handles the List response.
func (client *ConnectionsClient) listHandleResponse(resp *http.Response) (ConnectionsClientListResponse, error) {
	result := ConnectionsClientListResponse{}
	if val := resp.Header.Get("x-ms-client-request-id"); val != "" {
		result.ClientRequestID = &val
	}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedConnection); err != nil {
		return ConnectionsClientListResponse{}, err
	}
	return result, nil
}

// get - Get a connection
//
// Retrieves the specified connection and its configuration details without including credential values.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The friendly name of the connection, provided by the user.
//   - options - connectionsClientgetOptions contains the optional parameters for the ConnectionsClient.get method.
func (client *ConnectionsClient) get(ctx context.Context, name string, options *connectionsClientgetOptions) (connectionsClientgetResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "ConnectionsClient.get", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, name, options)
	if err != nil {
		return connectionsClientgetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return connectionsClientgetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return connectionsClientgetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the get request.
func (client *ConnectionsClient) getCreateRequest(ctx context.Context, name string, options *connectionsClientgetOptions) (*policy.Request, error) {
	urlPath := "/connections/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.ClientRequestID != nil {
		req.Raw().Header["x-ms-client-request-id"] = []string{*options.ClientRequestID}
	}
	return req, nil
}

// getHandleResponse handles the get response.
func (client *ConnectionsClient) getHandleResponse(resp *http.Response) (connectionsClientgetResponse, error) {
	result := connectionsClientgetResponse{}
	if val := resp.Header.Get("x-ms-client-request-id"); val != "" {
		result.ClientRequestID = &val
	}
	if err := runtime.UnmarshalAsJSON(resp, &result.Connection); err != nil {
		return connectionsClientgetResponse{}, err
	}
	return result, nil
}

// getWithCredentials - Get a connection with credentials
//
// Retrieves the specified connection together with its credential values.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The friendly name of the connection, provided by the user.
//   - options - connectionsClientgetWithCredentialsOptions contains the optional parameters for the ConnectionsClient.getWithCredentials
//     method.
func (client *ConnectionsClient) getWithCredentials(ctx context.Context, name string, options *connectionsClientgetWithCredentialsOptions) (connectionsClientgetWithCredentialsResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "ConnectionsClient.getWithCredentials", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getWithCredentialsCreateRequest(ctx, name, options)
	if err != nil {
		return connectionsClientgetWithCredentialsResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return connectionsClientgetWithCredentialsResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return connectionsClientgetWithCredentialsResponse{}, err
	}
	resp, err := client.getWithCredentialsHandleResponse(httpResp)
	return resp, err
}

// getWithCredentialsCreateRequest creates the getWithCredentials request.
func (client *ConnectionsClient) getWithCredentialsCreateRequest(ctx context.Context, name string, options *connectionsClientgetWithCredentialsOptions) (*policy.Request, error) {
	urlPath := "/connections/{name}/getConnectionWithCredentials"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.ClientRequestID != nil {
		req.Raw().Header["x-ms-client-request-id"] = []string{*options.ClientRequestID}
	}
	return req, nil
}

// getWithCredentialsHandleResponse handles the getWithCredentials response.
func (client *ConnectionsClient) getWithCredentialsHandleResponse(resp *http.Response) (connectionsClientgetWithCredentialsResponse, error) {
	result := connectionsClientgetWithCredentialsResponse{}
	if val := resp.Header.Get("x-ms-client-request-id"); val != "" {
		result.ClientRequestID = &val
	}
	if err := runtime.UnmarshalAsJSON(resp, &result.Connection); err != nil {
		return connectionsClientgetWithCredentialsResponse{}, err
	}
	return result, nil
}
