// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

const (
	versionV1 string = "v1"
)

// AttackStrategy - Strategies for attacks.
type AttackStrategy string

const (
	// AttackStrategyASCIIArt - Generates visual art using ASCII characters, often used for creative or obfuscation purposes.
	AttackStrategyASCIIArt AttackStrategy = "ascii_art"
	// AttackStrategyASCIISmuggler - Conceals data within ASCII characters, making it harder to detect.
	AttackStrategyASCIISmuggler AttackStrategy = "ascii_smuggler"
	// AttackStrategyAnsiAttack - Utilizes ANSI escape sequences to manipulate text appearance and behavior.
	AttackStrategyAnsiAttack AttackStrategy = "ansi_attack"
	// AttackStrategyAtbash - Implements the Atbash cipher, a simple substitution cipher where each letter is mapped to its reverse.
	AttackStrategyAtbash AttackStrategy = "atbash"
	// AttackStrategyBase64 - Encodes binary data into a text format using Base64, commonly used for data transmission.
	AttackStrategyBase64 AttackStrategy = "base64"
	// AttackStrategyBaseline - Represents the baseline direct adversarial probing, which is used by attack strategies as the
	// attack objective.
	AttackStrategyBaseline AttackStrategy = "baseline"
	// AttackStrategyBinary - Converts text into binary code, representing data in a series of 0s and 1s.
	AttackStrategyBinary AttackStrategy = "binary"
	// AttackStrategyCaesar - Applies the Caesar cipher, a substitution cipher that shifts characters by a fixed number of positions.
	AttackStrategyCaesar AttackStrategy = "caesar"
	// AttackStrategyCharacterSpace - Alters text by adding spaces between characters, often used for obfuscation.
	AttackStrategyCharacterSpace AttackStrategy = "character_space"
	// AttackStrategyCharacterSwap - Swaps characters within text to create variations or obfuscate the original content.
	AttackStrategyCharacterSwap AttackStrategy = "character_swap"
	// AttackStrategyCrescendo - Gradually increases the intensity or complexity of the attack over time.
	AttackStrategyCrescendo AttackStrategy = "crescendo"
	// AttackStrategyDiacritic - Adds diacritical marks to characters, changing their appearance and sometimes their meaning.
	AttackStrategyDiacritic AttackStrategy = "diacritic"
	// AttackStrategyDifficult - Represents a default set of difficult complexity attacks. Difficult complexity attacks include
	// attacks that require access to significant resources and effort to execute an attack such as knowledge of search-based
	// algorithms in addition to a generative AI model.
	AttackStrategyDifficult AttackStrategy = "difficult"
	// AttackStrategyEasy - Represents a default set of easy complexity attacks. Easy complexity attacks require less effort,
	// such as translation of a prompt into some encoding, and does not require any Large Language Model to convert or orchestrate.
	AttackStrategyEasy AttackStrategy = "easy"
	// AttackStrategyFlip - Flips characters from front to back, creating a mirrored effect.
	AttackStrategyFlip AttackStrategy = "flip"
	// AttackStrategyIndirectJailbreak - Represents indirect jailbreak attacks that use complex methods to bypass AI safeguards.
	AttackStrategyIndirectJailbreak AttackStrategy = "indirect_jailbreak"
	// AttackStrategyJailbreak - Injects specially crafted prompts to bypass AI safeguards, known as User Injected Prompt Attacks
	// (UPIA).
	AttackStrategyJailbreak AttackStrategy = "jailbreak"
	// AttackStrategyLeetspeak - Transforms text into Leetspeak, a form of encoding that replaces letters with similar-looking
	// numbers or symbols.
	AttackStrategyLeetspeak AttackStrategy = "leetspeak"
	// AttackStrategyModerate - Represents a default set of moderate complexity attacks. Moderate complexity attacks require having
	// access to resources such as another generative AI model.
	AttackStrategyModerate AttackStrategy = "moderate"
	// AttackStrategyMorse - Encodes text into Morse code, using dots and dashes to represent characters.
	AttackStrategyMorse AttackStrategy = "morse"
	// AttackStrategyMultiTurn - Creates multi-turn conversations to simulate extended interactions.
	AttackStrategyMultiTurn AttackStrategy = "multi_turn"
	// AttackStrategyROT13 - Applies the ROT13 cipher, a simple substitution cipher that shifts characters by 13 positions.
	AttackStrategyROT13 AttackStrategy = "rot13"
	// AttackStrategyStringJoin - Joins multiple strings together, often used for concatenation or obfuscation.
	AttackStrategyStringJoin AttackStrategy = "string_join"
	// AttackStrategySuffixAppend - Appends an adversarial suffix to the prompt.
	AttackStrategySuffixAppend AttackStrategy = "suffix_append"
	// AttackStrategyTense - Alters the tense of the text, changing its temporal context.
	AttackStrategyTense AttackStrategy = "tense"
	// AttackStrategyURL - Encodes text into URL format.
	AttackStrategyURL AttackStrategy = "url"
	// AttackStrategyUnicodeConfusable - Uses Unicode characters that look similar to standard characters, creating visual confusion.
	AttackStrategyUnicodeConfusable AttackStrategy = "unicode_confusable"
	// AttackStrategyUnicodeSubstitution - Substitutes standard characters with Unicode equivalents, often for obfuscation.
	AttackStrategyUnicodeSubstitution AttackStrategy = "unicode_substitution"
)

// PossibleAttackStrategyValues returns the possible values for the AttackStrategy const type.
func PossibleAttackStrategyValues() []AttackStrategy {
	return []AttackStrategy{
		AttackStrategyASCIIArt,
		AttackStrategyASCIISmuggler,
		AttackStrategyAnsiAttack,
		AttackStrategyAtbash,
		AttackStrategyBase64,
		AttackStrategyBaseline,
		AttackStrategyBinary,
		AttackStrategyCaesar,
		AttackStrategyCharacterSpace,
		AttackStrategyCharacterSwap,
		AttackStrategyCrescendo,
		AttackStrategyDiacritic,
		AttackStrategyDifficult,
		AttackStrategyEasy,
		AttackStrategyFlip,
		AttackStrategyIndirectJailbreak,
		AttackStrategyJailbreak,
		AttackStrategyLeetspeak,
		AttackStrategyModerate,
		AttackStrategyMorse,
		AttackStrategyMultiTurn,
		AttackStrategyROT13,
		AttackStrategyStringJoin,
		AttackStrategySuffixAppend,
		AttackStrategyTense,
		AttackStrategyURL,
		AttackStrategyUnicodeConfusable,
		AttackStrategyUnicodeSubstitution,
	}
}

// AzureAISearchQueryType - Available query types for Azure AI Search tool.
type AzureAISearchQueryType string

const (
	// AzureAISearchQueryTypeSemantic - Query type `semantic`
	AzureAISearchQueryTypeSemantic AzureAISearchQueryType = "semantic"
	// AzureAISearchQueryTypeSimple - Query type `simple`
	AzureAISearchQueryTypeSimple AzureAISearchQueryType = "simple"
	// AzureAISearchQueryTypeVector - Query type `vector`
	AzureAISearchQueryTypeVector AzureAISearchQueryType = "vector"
	// AzureAISearchQueryTypeVectorSemanticHybrid - Query type `vector_semantic_hybrid`
	AzureAISearchQueryTypeVectorSemanticHybrid AzureAISearchQueryType = "vector_semantic_hybrid"
	// AzureAISearchQueryTypeVectorSimpleHybrid - Query type `vector_simple_hybrid`
	AzureAISearchQueryTypeVectorSimpleHybrid AzureAISearchQueryType = "vector_simple_hybrid"
)

// PossibleAzureAISearchQueryTypeValues returns the possible values for the AzureAISearchQueryType const type.
func PossibleAzureAISearchQueryTypeValues() []AzureAISearchQueryType {
	return []AzureAISearchQueryType{
		AzureAISearchQueryTypeSemantic,
		AzureAISearchQueryTypeSimple,
		AzureAISearchQueryTypeVector,
		AzureAISearchQueryTypeVectorSemanticHybrid,
		AzureAISearchQueryTypeVectorSimpleHybrid,
	}
}

type ComputerEnvironment string

const (
	ComputerEnvironmentBrowser ComputerEnvironment = "browser"
	ComputerEnvironmentLinux   ComputerEnvironment = "linux"
	ComputerEnvironmentMac     ComputerEnvironment = "mac"
	ComputerEnvironmentUbuntu  ComputerEnvironment = "ubuntu"
	ComputerEnvironmentWindows ComputerEnvironment = "windows"
)

// PossibleComputerEnvironmentValues returns the possible values for the ComputerEnvironment const type.
func PossibleComputerEnvironmentValues() []ComputerEnvironment {
	return []ComputerEnvironment{
		ComputerEnvironmentBrowser,
		ComputerEnvironmentLinux,
		ComputerEnvironmentMac,
		ComputerEnvironmentUbuntu,
		ComputerEnvironmentWindows,
	}
}

// ConnectionType - The Type (or category) of the connection
type ConnectionType string

const (
	// ConnectionTypeAPIKey - Generic connection that uses API Key authentication
	ConnectionTypeAPIKey ConnectionType = "ApiKey"
	// ConnectionTypeApplicationConfiguration - Application Configuration
	ConnectionTypeApplicationConfiguration ConnectionType = "AppConfig"
	// ConnectionTypeApplicationInsights - Application Insights
	ConnectionTypeApplicationInsights ConnectionType = "AppInsights"
	// ConnectionTypeAzureAISearch - Azure AI Search
	ConnectionTypeAzureAISearch ConnectionType = "CognitiveSearch"
	// ConnectionTypeAzureBlobStorage - Azure Blob Storage, with specified container
	ConnectionTypeAzureBlobStorage ConnectionType = "AzureBlob"
	// ConnectionTypeAzureOpenAI - Azure OpenAI Service
	ConnectionTypeAzureOpenAI ConnectionType = "AzureOpenAI"
	// ConnectionTypeAzureStorageAccount - Azure Blob Storage, with container not specified (used by Agents)
	ConnectionTypeAzureStorageAccount ConnectionType = "AzureStorageAccount"
	// ConnectionTypeCosmosDB - CosmosDB
	ConnectionTypeCosmosDB ConnectionType = "CosmosDB"
	// ConnectionTypeCustom - Custom Keys
	ConnectionTypeCustom ConnectionType = "CustomKeys"
	// ConnectionTypeRemoteTool - Remote tool
	ConnectionTypeRemoteTool ConnectionType = "RemoteTool_Preview"
)

// PossibleConnectionTypeValues returns the possible values for the ConnectionType const type.
func PossibleConnectionTypeValues() []ConnectionType {
	return []ConnectionType{
		ConnectionTypeAPIKey,
		ConnectionTypeApplicationConfiguration,
		ConnectionTypeApplicationInsights,
		ConnectionTypeAzureAISearch,
		ConnectionTypeAzureBlobStorage,
		ConnectionTypeAzureOpenAI,
		ConnectionTypeAzureStorageAccount,
		ConnectionTypeCosmosDB,
		ConnectionTypeCustom,
		ConnectionTypeRemoteTool,
	}
}

type ContainerMemoryLimit string

const (
	ContainerMemoryLimit16G ContainerMemoryLimit = "16g"
	ContainerMemoryLimit1G  ContainerMemoryLimit = "1g"
	ContainerMemoryLimit4G  ContainerMemoryLimit = "4g"
	ContainerMemoryLimit64G ContainerMemoryLimit = "64g"
)

// PossibleContainerMemoryLimitValues returns the possible values for the ContainerMemoryLimit const type.
func PossibleContainerMemoryLimitValues() []ContainerMemoryLimit {
	return []ContainerMemoryLimit{
		ContainerMemoryLimit16G,
		ContainerMemoryLimit1G,
		ContainerMemoryLimit4G,
		ContainerMemoryLimit64G,
	}
}

type ContainerNetworkPolicyParamType string

const (
	ContainerNetworkPolicyParamTypeAllowlist ContainerNetworkPolicyParamType = "allowlist"
	ContainerNetworkPolicyParamTypeDisabled  ContainerNetworkPolicyParamType = "disabled"
)

// PossibleContainerNetworkPolicyParamTypeValues returns the possible values for the ContainerNetworkPolicyParamType const type.
func PossibleContainerNetworkPolicyParamTypeValues() []ContainerNetworkPolicyParamType {
	return []ContainerNetworkPolicyParamType{
		ContainerNetworkPolicyParamTypeAllowlist,
		ContainerNetworkPolicyParamTypeDisabled,
	}
}

type ContainerSkillType string

const (
	ContainerSkillTypeInline         ContainerSkillType = "inline"
	ContainerSkillTypeSkillReference ContainerSkillType = "skill_reference"
)

// PossibleContainerSkillTypeValues returns the possible values for the ContainerSkillType const type.
func PossibleContainerSkillTypeValues() []ContainerSkillType {
	return []ContainerSkillType{
		ContainerSkillTypeInline,
		ContainerSkillTypeSkillReference,
	}
}

// CredentialType - The credential type used by the connection
type CredentialType string

const (
	// CredentialTypeAPIKey - API Key credential
	CredentialTypeAPIKey CredentialType = "ApiKey"
	// CredentialTypeAgenticIdentityPreview - Agentic identity credential
	CredentialTypeAgenticIdentityPreview CredentialType = "AgenticIdentityToken_Preview"
	// CredentialTypeCustom - Custom credential
	CredentialTypeCustom CredentialType = "CustomKeys"
	// CredentialTypeEntraID - Entra ID credential (formerly known as AAD)
	CredentialTypeEntraID CredentialType = "AAD"
	// CredentialTypeNone - No credential
	CredentialTypeNone CredentialType = "None"
	// CredentialTypeSAS - Shared Access Signature (SAS) credential
	CredentialTypeSAS CredentialType = "SAS"
)

// PossibleCredentialTypeValues returns the possible values for the CredentialType const type.
func PossibleCredentialTypeValues() []CredentialType {
	return []CredentialType{
		CredentialTypeAPIKey,
		CredentialTypeAgenticIdentityPreview,
		CredentialTypeCustom,
		CredentialTypeEntraID,
		CredentialTypeNone,
		CredentialTypeSAS,
	}
}

type CustomToolParamFormatType string

const (
	CustomToolParamFormatTypeGrammar CustomToolParamFormatType = "grammar"
	CustomToolParamFormatTypeText    CustomToolParamFormatType = "text"
)

// PossibleCustomToolParamFormatTypeValues returns the possible values for the CustomToolParamFormatType const type.
func PossibleCustomToolParamFormatTypeValues() []CustomToolParamFormatType {
	return []CustomToolParamFormatType{
		CustomToolParamFormatTypeGrammar,
		CustomToolParamFormatTypeText,
	}
}

// DatasetType - Enum to determine the type of data.
type DatasetType string

const (
	// DatasetTypeURIFile - URI file.
	DatasetTypeURIFile DatasetType = "uri_file"
	// DatasetTypeURIFolder - URI folder.
	DatasetTypeURIFolder DatasetType = "uri_folder"
)

// PossibleDatasetTypeValues returns the possible values for the DatasetType const type.
func PossibleDatasetTypeValues() []DatasetType {
	return []DatasetType{
		DatasetTypeURIFile,
		DatasetTypeURIFolder,
	}
}

// DayOfWeek - Days of the week for recurrence schedule.
type DayOfWeek string

const (
	// DayOfWeekFriday - Friday.
	DayOfWeekFriday DayOfWeek = "Friday"
	// DayOfWeekMonday - Monday.
	DayOfWeekMonday DayOfWeek = "Monday"
	// DayOfWeekSaturday - Saturday.
	DayOfWeekSaturday DayOfWeek = "Saturday"
	// DayOfWeekSunday - Sunday.
	DayOfWeekSunday DayOfWeek = "Sunday"
	// DayOfWeekThursday - Thursday.
	DayOfWeekThursday DayOfWeek = "Thursday"
	// DayOfWeekTuesday - Tuesday.
	DayOfWeekTuesday DayOfWeek = "Tuesday"
	// DayOfWeekWednesday - Wednesday.
	DayOfWeekWednesday DayOfWeek = "Wednesday"
)

// PossibleDayOfWeekValues returns the possible values for the DayOfWeek const type.
func PossibleDayOfWeekValues() []DayOfWeek {
	return []DayOfWeek{
		DayOfWeekFriday,
		DayOfWeekMonday,
		DayOfWeekSaturday,
		DayOfWeekSunday,
		DayOfWeekThursday,
		DayOfWeekTuesday,
		DayOfWeekWednesday,
	}
}

type DeploymentType string

const (
	// DeploymentTypeModelDeployment - Model deployment
	DeploymentTypeModelDeployment DeploymentType = "ModelDeployment"
)

// PossibleDeploymentTypeValues returns the possible values for the DeploymentType const type.
func PossibleDeploymentTypeValues() []DeploymentType {
	return []DeploymentType{
		DeploymentTypeModelDeployment,
	}
}

// EvaluationLevel - The level at which evaluation is performed.
type EvaluationLevel string

const (
	// EvaluationLevelConversation - Evaluation is performed at the conversation level.
	EvaluationLevelConversation EvaluationLevel = "conversation"
	// EvaluationLevelTurn - Evaluation is performed at the turn level.
	EvaluationLevelTurn EvaluationLevel = "turn"
)

// PossibleEvaluationLevelValues returns the possible values for the EvaluationLevel const type.
func PossibleEvaluationLevelValues() []EvaluationLevel {
	return []EvaluationLevel{
		EvaluationLevelConversation,
		EvaluationLevelTurn,
	}
}

// EvaluationRuleActionType - Type of the evaluation action.
type EvaluationRuleActionType string

const (
	// EvaluationRuleActionTypeContinuousEvaluation - Continuous evaluation.
	EvaluationRuleActionTypeContinuousEvaluation EvaluationRuleActionType = "continuousEvaluation"
	// EvaluationRuleActionTypeHumanEvaluationPreview - Human evaluation preview.
	EvaluationRuleActionTypeHumanEvaluationPreview EvaluationRuleActionType = "humanEvaluationPreview"
)

// PossibleEvaluationRuleActionTypeValues returns the possible values for the EvaluationRuleActionType const type.
func PossibleEvaluationRuleActionTypeValues() []EvaluationRuleActionType {
	return []EvaluationRuleActionType{
		EvaluationRuleActionTypeContinuousEvaluation,
		EvaluationRuleActionTypeHumanEvaluationPreview,
	}
}

// EvaluationRuleEventType - Type of the evaluation rule event.
type EvaluationRuleEventType string

const (
	// EvaluationRuleEventTypeManual - Manual trigger.
	EvaluationRuleEventTypeManual EvaluationRuleEventType = "manual"
	// EvaluationRuleEventTypeResponseCompleted - Response completed.
	EvaluationRuleEventTypeResponseCompleted EvaluationRuleEventType = "responseCompleted"
)

// PossibleEvaluationRuleEventTypeValues returns the possible values for the EvaluationRuleEventType const type.
func PossibleEvaluationRuleEventTypeValues() []EvaluationRuleEventType {
	return []EvaluationRuleEventType{
		EvaluationRuleEventTypeManual,
		EvaluationRuleEventTypeResponseCompleted,
	}
}

// EvaluationTaxonomyInputType - Type of the evaluation taxonomy input.
type EvaluationTaxonomyInputType string

const (
	// EvaluationTaxonomyInputTypeAgent - Agent
	EvaluationTaxonomyInputTypeAgent EvaluationTaxonomyInputType = "agent"
	// EvaluationTaxonomyInputTypePolicy - Policy
	EvaluationTaxonomyInputTypePolicy EvaluationTaxonomyInputType = "policy"
)

// PossibleEvaluationTaxonomyInputTypeValues returns the possible values for the EvaluationTaxonomyInputType const type.
func PossibleEvaluationTaxonomyInputTypeValues() []EvaluationTaxonomyInputType {
	return []EvaluationTaxonomyInputType{
		EvaluationTaxonomyInputTypeAgent,
		EvaluationTaxonomyInputTypePolicy,
	}
}

// EvaluatorCategory - The category of the evaluator
type EvaluatorCategory string

const (
	// EvaluatorCategoryAgents - Agents
	EvaluatorCategoryAgents EvaluatorCategory = "agents"
	// EvaluatorCategoryQuality - Quality
	EvaluatorCategoryQuality EvaluatorCategory = "quality"
	// EvaluatorCategorySafety - Risk & Safety
	EvaluatorCategorySafety EvaluatorCategory = "safety"
)

// PossibleEvaluatorCategoryValues returns the possible values for the EvaluatorCategory const type.
func PossibleEvaluatorCategoryValues() []EvaluatorCategory {
	return []EvaluatorCategory{
		EvaluatorCategoryAgents,
		EvaluatorCategoryQuality,
		EvaluatorCategorySafety,
	}
}

// EvaluatorDefinitionType - The type of evaluator definition
type EvaluatorDefinitionType string

const (
	// EvaluatorDefinitionTypeCode - Code-based definition
	EvaluatorDefinitionTypeCode EvaluatorDefinitionType = "code"
	// EvaluatorDefinitionTypeOpenaiGraders - OpenAI graders
	EvaluatorDefinitionTypeOpenaiGraders EvaluatorDefinitionType = "openai_graders"
	// EvaluatorDefinitionTypePrompt - Prompt-based definition
	EvaluatorDefinitionTypePrompt EvaluatorDefinitionType = "prompt"
	// EvaluatorDefinitionTypePromptAndCode - Prompt & Code Based definition
	EvaluatorDefinitionTypePromptAndCode EvaluatorDefinitionType = "prompt_and_code"
	// EvaluatorDefinitionTypeRubric - Rubric-based evaluator definition. Stores dimensions (the scoring blueprint) for both quality
	// and safety evaluators. Can be created via the generate API or manually via createVersion.
	EvaluatorDefinitionTypeRubric EvaluatorDefinitionType = "rubric"
	// EvaluatorDefinitionTypeService - Service-based evaluator
	EvaluatorDefinitionTypeService EvaluatorDefinitionType = "service"
)

// PossibleEvaluatorDefinitionTypeValues returns the possible values for the EvaluatorDefinitionType const type.
func PossibleEvaluatorDefinitionTypeValues() []EvaluatorDefinitionType {
	return []EvaluatorDefinitionType{
		EvaluatorDefinitionTypeCode,
		EvaluatorDefinitionTypeOpenaiGraders,
		EvaluatorDefinitionTypePrompt,
		EvaluatorDefinitionTypePromptAndCode,
		EvaluatorDefinitionTypeRubric,
		EvaluatorDefinitionTypeService,
	}
}

// EvaluatorGenerationJobSourceType - The supported source types for evaluator generation jobs.
type EvaluatorGenerationJobSourceType string

const (
	// EvaluatorGenerationJobSourceTypeAgent - Agent source — references an agent to fetch instructions and metadata from.
	EvaluatorGenerationJobSourceTypeAgent EvaluatorGenerationJobSourceType = "agent"
	// EvaluatorGenerationJobSourceTypeDataset - Dataset source — reference to a dataset.
	EvaluatorGenerationJobSourceTypeDataset EvaluatorGenerationJobSourceType = "dataset"
	// EvaluatorGenerationJobSourceTypePrompt - Prompt source — inline text provided by the user.
	EvaluatorGenerationJobSourceTypePrompt EvaluatorGenerationJobSourceType = "prompt"
	// EvaluatorGenerationJobSourceTypeTraces - Traces source — conversation traces from Application Insights.
	EvaluatorGenerationJobSourceTypeTraces EvaluatorGenerationJobSourceType = "traces"
)

// PossibleEvaluatorGenerationJobSourceTypeValues returns the possible values for the EvaluatorGenerationJobSourceType const type.
func PossibleEvaluatorGenerationJobSourceTypeValues() []EvaluatorGenerationJobSourceType {
	return []EvaluatorGenerationJobSourceType{
		EvaluatorGenerationJobSourceTypeAgent,
		EvaluatorGenerationJobSourceTypeDataset,
		EvaluatorGenerationJobSourceTypePrompt,
		EvaluatorGenerationJobSourceTypeTraces,
	}
}

// EvaluatorMetricDirection - The direction of the metric indicating whether a higher value is better, a lower value is better,
// or neutral
type EvaluatorMetricDirection string

const (
	// EvaluatorMetricDirectionDecrease - It indicates a lower value is better for this metric
	EvaluatorMetricDirectionDecrease EvaluatorMetricDirection = "decrease"
	// EvaluatorMetricDirectionIncrease - It indicates a higher value is better for this metric
	EvaluatorMetricDirectionIncrease EvaluatorMetricDirection = "increase"
	// EvaluatorMetricDirectionNeutral - It indicates no preference for this metric direction
	EvaluatorMetricDirectionNeutral EvaluatorMetricDirection = "neutral"
)

// PossibleEvaluatorMetricDirectionValues returns the possible values for the EvaluatorMetricDirection const type.
func PossibleEvaluatorMetricDirectionValues() []EvaluatorMetricDirection {
	return []EvaluatorMetricDirection{
		EvaluatorMetricDirectionDecrease,
		EvaluatorMetricDirectionIncrease,
		EvaluatorMetricDirectionNeutral,
	}
}

// EvaluatorMetricType - The type of the evaluator
type EvaluatorMetricType string

const (
	// EvaluatorMetricTypeBoolean - Boolean metric representing true/false values
	EvaluatorMetricTypeBoolean EvaluatorMetricType = "boolean"
	// EvaluatorMetricTypeContinuous - Continuous metric representing values in a continuous range.
	EvaluatorMetricTypeContinuous EvaluatorMetricType = "continuous"
	// EvaluatorMetricTypeOrdinal - Ordinal metric representing categories that can be ordered or ranked.
	EvaluatorMetricTypeOrdinal EvaluatorMetricType = "ordinal"
)

// PossibleEvaluatorMetricTypeValues returns the possible values for the EvaluatorMetricType const type.
func PossibleEvaluatorMetricTypeValues() []EvaluatorMetricType {
	return []EvaluatorMetricType{
		EvaluatorMetricTypeBoolean,
		EvaluatorMetricTypeContinuous,
		EvaluatorMetricTypeOrdinal,
	}
}

// EvaluatorType - The type of the evaluator
type EvaluatorType string

const (
	// EvaluatorTypeBuiltIn - Built-in evaluator (Microsoft provided)
	EvaluatorTypeBuiltIn EvaluatorType = "builtin"
	// EvaluatorTypeCustom - Custom evaluator
	EvaluatorTypeCustom EvaluatorType = "custom"
)

// PossibleEvaluatorTypeValues returns the possible values for the EvaluatorType const type.
func PossibleEvaluatorTypeValues() []EvaluatorType {
	return []EvaluatorType{
		EvaluatorTypeBuiltIn,
		EvaluatorTypeCustom,
	}
}

type FunctionShellToolParamEnvironmentType string

const (
	FunctionShellToolParamEnvironmentTypeContainerAuto      FunctionShellToolParamEnvironmentType = "container_auto"
	FunctionShellToolParamEnvironmentTypeContainerReference FunctionShellToolParamEnvironmentType = "container_reference"
	FunctionShellToolParamEnvironmentTypeLocal              FunctionShellToolParamEnvironmentType = "local"
)

// PossibleFunctionShellToolParamEnvironmentTypeValues returns the possible values for the FunctionShellToolParamEnvironmentType const type.
func PossibleFunctionShellToolParamEnvironmentTypeValues() []FunctionShellToolParamEnvironmentType {
	return []FunctionShellToolParamEnvironmentType{
		FunctionShellToolParamEnvironmentTypeContainerAuto,
		FunctionShellToolParamEnvironmentTypeContainerReference,
		FunctionShellToolParamEnvironmentTypeLocal,
	}
}

type GrammarSyntax1 string

const (
	GrammarSyntax1Lark  GrammarSyntax1 = "lark"
	GrammarSyntax1Regex GrammarSyntax1 = "regex"
)

// PossibleGrammarSyntax1Values returns the possible values for the GrammarSyntax1 const type.
func PossibleGrammarSyntax1Values() []GrammarSyntax1 {
	return []GrammarSyntax1{
		GrammarSyntax1Lark,
		GrammarSyntax1Regex,
	}
}

type ImageGenActionEnum string

const (
	ImageGenActionEnumAuto     ImageGenActionEnum = "auto"
	ImageGenActionEnumEdit     ImageGenActionEnum = "edit"
	ImageGenActionEnumGenerate ImageGenActionEnum = "generate"
)

// PossibleImageGenActionEnumValues returns the possible values for the ImageGenActionEnum const type.
func PossibleImageGenActionEnumValues() []ImageGenActionEnum {
	return []ImageGenActionEnum{
		ImageGenActionEnumAuto,
		ImageGenActionEnumEdit,
		ImageGenActionEnumGenerate,
	}
}

type ImageGenToolBackground string

const (
	ImageGenToolBackgroundAuto        ImageGenToolBackground = "auto"
	ImageGenToolBackgroundOpaque      ImageGenToolBackground = "opaque"
	ImageGenToolBackgroundTransparent ImageGenToolBackground = "transparent"
)

// PossibleImageGenToolBackgroundValues returns the possible values for the ImageGenToolBackground const type.
func PossibleImageGenToolBackgroundValues() []ImageGenToolBackground {
	return []ImageGenToolBackground{
		ImageGenToolBackgroundAuto,
		ImageGenToolBackgroundOpaque,
		ImageGenToolBackgroundTransparent,
	}
}

type ImageGenToolModel string

const (
	ImageGenToolModelGptImage1     ImageGenToolModel = "gpt-image-1"
	ImageGenToolModelGptImage15    ImageGenToolModel = "gpt-image-1.5"
	ImageGenToolModelGptImage1Mini ImageGenToolModel = "gpt-image-1-mini"
)

// PossibleImageGenToolModelValues returns the possible values for the ImageGenToolModel const type.
func PossibleImageGenToolModelValues() []ImageGenToolModel {
	return []ImageGenToolModel{
		ImageGenToolModelGptImage1,
		ImageGenToolModelGptImage15,
		ImageGenToolModelGptImage1Mini,
	}
}

type ImageGenToolModeration string

const (
	ImageGenToolModerationAuto ImageGenToolModeration = "auto"
	ImageGenToolModerationLow  ImageGenToolModeration = "low"
)

// PossibleImageGenToolModerationValues returns the possible values for the ImageGenToolModeration const type.
func PossibleImageGenToolModerationValues() []ImageGenToolModeration {
	return []ImageGenToolModeration{
		ImageGenToolModerationAuto,
		ImageGenToolModerationLow,
	}
}

type ImageGenToolOutputFormat string

const (
	ImageGenToolOutputFormatJPEG ImageGenToolOutputFormat = "jpeg"
	ImageGenToolOutputFormatPNG  ImageGenToolOutputFormat = "png"
	ImageGenToolOutputFormatWebp ImageGenToolOutputFormat = "webp"
)

// PossibleImageGenToolOutputFormatValues returns the possible values for the ImageGenToolOutputFormat const type.
func PossibleImageGenToolOutputFormatValues() []ImageGenToolOutputFormat {
	return []ImageGenToolOutputFormat{
		ImageGenToolOutputFormatJPEG,
		ImageGenToolOutputFormatPNG,
		ImageGenToolOutputFormatWebp,
	}
}

type ImageGenToolQuality string

const (
	ImageGenToolQualityAuto   ImageGenToolQuality = "auto"
	ImageGenToolQualityHigh   ImageGenToolQuality = "high"
	ImageGenToolQualityLow    ImageGenToolQuality = "low"
	ImageGenToolQualityMedium ImageGenToolQuality = "medium"
)

// PossibleImageGenToolQualityValues returns the possible values for the ImageGenToolQuality const type.
func PossibleImageGenToolQualityValues() []ImageGenToolQuality {
	return []ImageGenToolQuality{
		ImageGenToolQualityAuto,
		ImageGenToolQualityHigh,
		ImageGenToolQualityLow,
		ImageGenToolQualityMedium,
	}
}

type ImageGenToolSize string

const (
	ImageGenToolSize1024X1024 ImageGenToolSize = "1024x1024"
	ImageGenToolSize1024X1536 ImageGenToolSize = "1024x1536"
	ImageGenToolSize1536X1024 ImageGenToolSize = "1536x1024"
	ImageGenToolSizeAuto      ImageGenToolSize = "auto"
)

// PossibleImageGenToolSizeValues returns the possible values for the ImageGenToolSize const type.
func PossibleImageGenToolSizeValues() []ImageGenToolSize {
	return []ImageGenToolSize{
		ImageGenToolSize1024X1024,
		ImageGenToolSize1024X1536,
		ImageGenToolSize1536X1024,
		ImageGenToolSizeAuto,
	}
}

type IndexType string

const (
	// IndexTypeAzureSearch - Azure search
	IndexTypeAzureSearch IndexType = "AzureSearch"
	// IndexTypeCosmosDB - CosmosDB
	IndexTypeCosmosDB IndexType = "CosmosDBNoSqlVectorStore"
	// IndexTypeManagedAzureSearch - Managed Azure Search
	IndexTypeManagedAzureSearch IndexType = "ManagedAzureSearch"
)

// PossibleIndexTypeValues returns the possible values for the IndexType const type.
func PossibleIndexTypeValues() []IndexType {
	return []IndexType{
		IndexTypeAzureSearch,
		IndexTypeCosmosDB,
		IndexTypeManagedAzureSearch,
	}
}

// InputFidelity - Control how much effort the model will exert to match the style and features, especially facial features,
// of input images. This parameter is only supported for `gpt-image-1` and `gpt-image-1.5` and later models, unsupported for
// `gpt-image-1-mini`. Supports `high` and `low`. Defaults to `low`.
type InputFidelity string

const (
	InputFidelityHigh InputFidelity = "high"
	InputFidelityLow  InputFidelity = "low"
)

// PossibleInputFidelityValues returns the possible values for the InputFidelity const type.
func PossibleInputFidelityValues() []InputFidelity {
	return []InputFidelity{
		InputFidelityHigh,
		InputFidelityLow,
	}
}

// InsightType - The request of the insights.
type InsightType string

const (
	// InsightTypeAgentClusterInsight - Cluster Insight on an Agent.
	InsightTypeAgentClusterInsight InsightType = "AgentClusterInsight"
	// InsightTypeEvaluationComparison - Evaluation Comparison.
	InsightTypeEvaluationComparison InsightType = "EvaluationComparison"
	// InsightTypeEvaluationRunClusterInsight - Insights on an Evaluation run result.
	InsightTypeEvaluationRunClusterInsight InsightType = "EvaluationRunClusterInsight"
)

// PossibleInsightTypeValues returns the possible values for the InsightType const type.
func PossibleInsightTypeValues() []InsightType {
	return []InsightType{
		InsightTypeAgentClusterInsight,
		InsightTypeEvaluationComparison,
		InsightTypeEvaluationRunClusterInsight,
	}
}

// JobStatus - Extensible status values shared by Foundry jobs.
type JobStatus string

const (
	// JobStatusCancelled - Job was cancelled by the caller.
	JobStatusCancelled JobStatus = "cancelled"
	// JobStatusFailed - Job failed.
	JobStatusFailed JobStatus = "failed"
	// JobStatusInProgress - Job is actively processing.
	JobStatusInProgress JobStatus = "in_progress"
	// JobStatusQueued - Job is waiting to start.
	JobStatusQueued JobStatus = "queued"
	// JobStatusSucceeded - Job completed successfully.
	JobStatusSucceeded JobStatus = "succeeded"
)

// PossibleJobStatusValues returns the possible values for the JobStatus const type.
func PossibleJobStatusValues() []JobStatus {
	return []JobStatus{
		JobStatusCancelled,
		JobStatusFailed,
		JobStatusInProgress,
		JobStatusQueued,
		JobStatusSucceeded,
	}
}

type ListVersionsRequestType string

const (
	ListVersionsRequestTypeAll ListVersionsRequestType = "all"
	// ListVersionsRequestTypeBuiltIn - Built-in evaluator (Microsoft provided)
	ListVersionsRequestTypeBuiltIn ListVersionsRequestType = "builtin"
	// ListVersionsRequestTypeCustom - Custom evaluator
	ListVersionsRequestTypeCustom ListVersionsRequestType = "custom"
)

// PossibleListVersionsRequestTypeValues returns the possible values for the ListVersionsRequestType const type.
func PossibleListVersionsRequestTypeValues() []ListVersionsRequestType {
	return []ListVersionsRequestType{
		ListVersionsRequestTypeAll,
		ListVersionsRequestTypeBuiltIn,
		ListVersionsRequestTypeCustom,
	}
}

type MCPToolConnectorID string

const (
	MCPToolConnectorIDConnectorDropbox         MCPToolConnectorID = "connector_dropbox"
	MCPToolConnectorIDConnectorGmail           MCPToolConnectorID = "connector_gmail"
	MCPToolConnectorIDConnectorGooglecalendar  MCPToolConnectorID = "connector_googlecalendar"
	MCPToolConnectorIDConnectorGoogledrive     MCPToolConnectorID = "connector_googledrive"
	MCPToolConnectorIDConnectorMicrosoftteams  MCPToolConnectorID = "connector_microsoftteams"
	MCPToolConnectorIDConnectorOutlookcalendar MCPToolConnectorID = "connector_outlookcalendar"
	MCPToolConnectorIDConnectorOutlookemail    MCPToolConnectorID = "connector_outlookemail"
	MCPToolConnectorIDConnectorSharepoint      MCPToolConnectorID = "connector_sharepoint"
)

// PossibleMCPToolConnectorIDValues returns the possible values for the MCPToolConnectorID const type.
func PossibleMCPToolConnectorIDValues() []MCPToolConnectorID {
	return []MCPToolConnectorID{
		MCPToolConnectorIDConnectorDropbox,
		MCPToolConnectorIDConnectorGmail,
		MCPToolConnectorIDConnectorGooglecalendar,
		MCPToolConnectorIDConnectorGoogledrive,
		MCPToolConnectorIDConnectorMicrosoftteams,
		MCPToolConnectorIDConnectorOutlookcalendar,
		MCPToolConnectorIDConnectorOutlookemail,
		MCPToolConnectorIDConnectorSharepoint,
	}
}

// MemoryItemKind - Memory item kind.
type MemoryItemKind string

const (
	// MemoryItemKindChatSummary - Summary of chat conversations.
	MemoryItemKindChatSummary MemoryItemKind = "chat_summary"
	// MemoryItemKindProcedural - Routine procedures extracted from conversations.
	MemoryItemKindProcedural MemoryItemKind = "procedural"
	// MemoryItemKindUserProfile - User profile information extracted from conversations.
	MemoryItemKindUserProfile MemoryItemKind = "user_profile"
)

// PossibleMemoryItemKindValues returns the possible values for the MemoryItemKind const type.
func PossibleMemoryItemKindValues() []MemoryItemKind {
	return []MemoryItemKind{
		MemoryItemKindChatSummary,
		MemoryItemKindProcedural,
		MemoryItemKindUserProfile,
	}
}

// MemoryOperationKind - Memory operation kind.
type MemoryOperationKind string

const (
	// MemoryOperationKindCreate - Create a new memory item.
	MemoryOperationKindCreate MemoryOperationKind = "create"
	// MemoryOperationKindDelete - Delete an existing memory item.
	MemoryOperationKindDelete MemoryOperationKind = "delete"
	// MemoryOperationKindUpdate - Update an existing memory item.
	MemoryOperationKindUpdate MemoryOperationKind = "update"
)

// PossibleMemoryOperationKindValues returns the possible values for the MemoryOperationKind const type.
func PossibleMemoryOperationKindValues() []MemoryOperationKind {
	return []MemoryOperationKind{
		MemoryOperationKindCreate,
		MemoryOperationKindDelete,
		MemoryOperationKindUpdate,
	}
}

// MemoryStoreKind - The type of memory store implementation to use.
type MemoryStoreKind string

const (
	// MemoryStoreKindDefault - The default memory store implementation.
	MemoryStoreKindDefault MemoryStoreKind = "default"
)

// PossibleMemoryStoreKindValues returns the possible values for the MemoryStoreKind const type.
func PossibleMemoryStoreKindValues() []MemoryStoreKind {
	return []MemoryStoreKind{
		MemoryStoreKindDefault,
	}
}

type MemoryStoreObjectType string

const (
	MemoryStoreObjectTypeMemoryDeleted           MemoryStoreObjectType = "memory_store.item.deleted"
	MemoryStoreObjectTypeMemoryStore             MemoryStoreObjectType = "memory_store"
	MemoryStoreObjectTypeMemoryStoreDeleted      MemoryStoreObjectType = "memory_store.deleted"
	MemoryStoreObjectTypeMemoryStoreScopeDeleted MemoryStoreObjectType = "memory_store.scope.deleted"
)

// PossibleMemoryStoreObjectTypeValues returns the possible values for the MemoryStoreObjectType const type.
func PossibleMemoryStoreObjectTypeValues() []MemoryStoreObjectType {
	return []MemoryStoreObjectType{
		MemoryStoreObjectTypeMemoryDeleted,
		MemoryStoreObjectTypeMemoryStore,
		MemoryStoreObjectTypeMemoryStoreDeleted,
		MemoryStoreObjectTypeMemoryStoreScopeDeleted,
	}
}

// MemoryStoreUpdateStatus - Status of a memory store update operation.
type MemoryStoreUpdateStatus string

const (
	MemoryStoreUpdateStatusCompleted  MemoryStoreUpdateStatus = "completed"
	MemoryStoreUpdateStatusFailed     MemoryStoreUpdateStatus = "failed"
	MemoryStoreUpdateStatusInProgress MemoryStoreUpdateStatus = "in_progress"
	MemoryStoreUpdateStatusQueued     MemoryStoreUpdateStatus = "queued"
	MemoryStoreUpdateStatusSuperseded MemoryStoreUpdateStatus = "superseded"
)

// PossibleMemoryStoreUpdateStatusValues returns the possible values for the MemoryStoreUpdateStatus const type.
func PossibleMemoryStoreUpdateStatusValues() []MemoryStoreUpdateStatus {
	return []MemoryStoreUpdateStatus{
		MemoryStoreUpdateStatusCompleted,
		MemoryStoreUpdateStatusFailed,
		MemoryStoreUpdateStatusInProgress,
		MemoryStoreUpdateStatusQueued,
		MemoryStoreUpdateStatusSuperseded,
	}
}

// OpenAPIAuthType - Authentication type for OpenApi endpoint. Allowed types are:
// - Anonymous (no authentication required)
// - Project Connection (requires project_connection_id to endpoint, as setup in AI Foundry)
// - Managed_Identity (requires audience for identity based auth)
type OpenAPIAuthType string

const (
	OpenAPIAuthTypeAnonymous         OpenAPIAuthType = "anonymous"
	OpenAPIAuthTypeManagedIdentity   OpenAPIAuthType = "managed_identity"
	OpenAPIAuthTypeProjectConnection OpenAPIAuthType = "project_connection"
)

// PossibleOpenAPIAuthTypeValues returns the possible values for the OpenAPIAuthType const type.
func PossibleOpenAPIAuthTypeValues() []OpenAPIAuthType {
	return []OpenAPIAuthType{
		OpenAPIAuthTypeAnonymous,
		OpenAPIAuthTypeManagedIdentity,
		OpenAPIAuthTypeProjectConnection,
	}
}

// OperationState - Enum describing allowed operation states.
type OperationState string

const (
	// OperationStateCanceled - The operation has been canceled by the user.
	OperationStateCanceled OperationState = "Canceled"
	// OperationStateFailed - The operation has failed.
	OperationStateFailed OperationState = "Failed"
	// OperationStateNotStarted - The operation has not started.
	OperationStateNotStarted OperationState = "NotStarted"
	// OperationStateRunning - The operation is in progress.
	OperationStateRunning OperationState = "Running"
	// OperationStateSucceeded - The operation has completed successfully.
	OperationStateSucceeded OperationState = "Succeeded"
)

// PossibleOperationStateValues returns the possible values for the OperationState const type.
func PossibleOperationStateValues() []OperationState {
	return []OperationState{
		OperationStateCanceled,
		OperationStateFailed,
		OperationStateNotStarted,
		OperationStateRunning,
		OperationStateSucceeded,
	}
}

type PageOrder string

const (
	PageOrderAsc  PageOrder = "asc"
	PageOrderDesc PageOrder = "desc"
)

// PossiblePageOrderValues returns the possible values for the PageOrder const type.
func PossiblePageOrderValues() []PageOrder {
	return []PageOrder{
		PageOrderAsc,
		PageOrderDesc,
	}
}

// PendingUploadType - The type of pending upload.
type PendingUploadType string

const (
	// PendingUploadTypeBlobReference - Deprecated: the service never read this value and silently ignored it. Use TemporaryBlobReference
	// instead.
	PendingUploadTypeBlobReference PendingUploadType = "BlobReference"
	// PendingUploadTypeNone - No pending upload.
	PendingUploadTypeNone PendingUploadType = "None"
	// PendingUploadTypeTemporaryBlobReference - Temporary blob reference.
	PendingUploadTypeTemporaryBlobReference PendingUploadType = "TemporaryBlobReference"
)

// PossiblePendingUploadTypeValues returns the possible values for the PendingUploadType const type.
func PossiblePendingUploadTypeValues() []PendingUploadType {
	return []PendingUploadType{
		PendingUploadTypeBlobReference,
		PendingUploadTypeNone,
		PendingUploadTypeTemporaryBlobReference,
	}
}

type RankerVersionType string

const (
	RankerVersionTypeAuto            RankerVersionType = "auto"
	RankerVersionTypeDefault20241115 RankerVersionType = "default-2024-11-15"
)

// PossibleRankerVersionTypeValues returns the possible values for the RankerVersionType const type.
func PossibleRankerVersionTypeValues() []RankerVersionType {
	return []RankerVersionType{
		RankerVersionTypeAuto,
		RankerVersionTypeDefault20241115,
	}
}

// RecurrenceType - Recurrence type.
type RecurrenceType string

const (
	// RecurrenceTypeDaily - Daily recurrence pattern.
	RecurrenceTypeDaily RecurrenceType = "Daily"
	// RecurrenceTypeHourly - Hourly recurrence pattern.
	RecurrenceTypeHourly RecurrenceType = "Hourly"
	// RecurrenceTypeMonthly - Monthly recurrence pattern.
	RecurrenceTypeMonthly RecurrenceType = "Monthly"
	// RecurrenceTypeWeekly - Weekly recurrence pattern.
	RecurrenceTypeWeekly RecurrenceType = "Weekly"
)

// PossibleRecurrenceTypeValues returns the possible values for the RecurrenceType const type.
func PossibleRecurrenceTypeValues() []RecurrenceType {
	return []RecurrenceType{
		RecurrenceTypeDaily,
		RecurrenceTypeHourly,
		RecurrenceTypeMonthly,
		RecurrenceTypeWeekly,
	}
}

// RiskCategory - Risk category for the attack objective.
type RiskCategory string

const (
	// RiskCategoryCodeVulnerability - Represents content that contains vulnerabilities in code.
	RiskCategoryCodeVulnerability RiskCategory = "CodeVulnerability"
	// RiskCategoryHateUnfairness - Represents content related to hate or unfairness.
	RiskCategoryHateUnfairness RiskCategory = "HateUnfairness"
	// RiskCategoryProhibitedActions - Represents content that involves prohibited actions.
	RiskCategoryProhibitedActions RiskCategory = "ProhibitedActions"
	// RiskCategoryProtectedMaterial - Represents content that involves illegal activities.
	RiskCategoryProtectedMaterial RiskCategory = "ProtectedMaterial"
	// RiskCategorySelfHarm - Represents content related to self-harm.
	RiskCategorySelfHarm RiskCategory = "SelfHarm"
	// RiskCategorySensitiveDataLeakage - Represents content that involves sensitive data leakage.
	RiskCategorySensitiveDataLeakage RiskCategory = "SensitiveDataLeakage"
	// RiskCategorySexual - Represents content of a sexual nature.
	RiskCategorySexual RiskCategory = "Sexual"
	// RiskCategoryTaskAdherence - Represents content that involves task adherence.
	RiskCategoryTaskAdherence RiskCategory = "TaskAdherence"
	// RiskCategoryUngroundedAttributes - Represents content that lacks a solid grounding in fact.
	RiskCategoryUngroundedAttributes RiskCategory = "UngroundedAttributes"
	// RiskCategoryViolence - Represents content related to violence.
	RiskCategoryViolence RiskCategory = "Violence"
)

// PossibleRiskCategoryValues returns the possible values for the RiskCategory const type.
func PossibleRiskCategoryValues() []RiskCategory {
	return []RiskCategory{
		RiskCategoryCodeVulnerability,
		RiskCategoryHateUnfairness,
		RiskCategoryProhibitedActions,
		RiskCategoryProtectedMaterial,
		RiskCategorySelfHarm,
		RiskCategorySensitiveDataLeakage,
		RiskCategorySexual,
		RiskCategoryTaskAdherence,
		RiskCategoryUngroundedAttributes,
		RiskCategoryViolence,
	}
}

// SampleType - The type of sample used in the analysis.
type SampleType string

const (
	// SampleTypeEvaluationResultSample - A sample from the evaluation result.
	SampleTypeEvaluationResultSample SampleType = "EvaluationResultSample"
)

// PossibleSampleTypeValues returns the possible values for the SampleType const type.
func PossibleSampleTypeValues() []SampleType {
	return []SampleType{
		SampleTypeEvaluationResultSample,
	}
}

// ScheduleProvisioningStatus - Schedule provisioning status.
type ScheduleProvisioningStatus string

const (
	// ScheduleProvisioningStatusCreating - Represents the creation status of the schedule.
	ScheduleProvisioningStatusCreating ScheduleProvisioningStatus = "Creating"
	// ScheduleProvisioningStatusDeleting - Represents the deleting status of the schedule.
	ScheduleProvisioningStatusDeleting ScheduleProvisioningStatus = "Deleting"
	// ScheduleProvisioningStatusFailed - Represents the failed status of the schedule.
	ScheduleProvisioningStatusFailed ScheduleProvisioningStatus = "Failed"
	// ScheduleProvisioningStatusSucceeded - Represents the succeeded status of the schedule.
	ScheduleProvisioningStatusSucceeded ScheduleProvisioningStatus = "Succeeded"
	// ScheduleProvisioningStatusUpdating - Represents the updating status of the schedule.
	ScheduleProvisioningStatusUpdating ScheduleProvisioningStatus = "Updating"
)

// PossibleScheduleProvisioningStatusValues returns the possible values for the ScheduleProvisioningStatus const type.
func PossibleScheduleProvisioningStatusValues() []ScheduleProvisioningStatus {
	return []ScheduleProvisioningStatus{
		ScheduleProvisioningStatusCreating,
		ScheduleProvisioningStatusDeleting,
		ScheduleProvisioningStatusFailed,
		ScheduleProvisioningStatusSucceeded,
		ScheduleProvisioningStatusUpdating,
	}
}

// ScheduleTaskType - Type of the task.
type ScheduleTaskType string

const (
	// ScheduleTaskTypeEvaluation - Evaluation task.
	ScheduleTaskTypeEvaluation ScheduleTaskType = "Evaluation"
	// ScheduleTaskTypeInsight - Insight task.
	ScheduleTaskTypeInsight ScheduleTaskType = "Insight"
)

// PossibleScheduleTaskTypeValues returns the possible values for the ScheduleTaskType const type.
func PossibleScheduleTaskTypeValues() []ScheduleTaskType {
	return []ScheduleTaskType{
		ScheduleTaskTypeEvaluation,
		ScheduleTaskTypeInsight,
	}
}

type SearchContentType string

const (
	SearchContentTypeImage SearchContentType = "image"
	SearchContentTypeText  SearchContentType = "text"
)

// PossibleSearchContentTypeValues returns the possible values for the SearchContentType const type.
func PossibleSearchContentTypeValues() []SearchContentType {
	return []SearchContentType{
		SearchContentTypeImage,
		SearchContentTypeText,
	}
}

type SearchContextSize string

const (
	SearchContextSizeHigh   SearchContextSize = "high"
	SearchContextSizeLow    SearchContextSize = "low"
	SearchContextSizeMedium SearchContextSize = "medium"
)

// PossibleSearchContextSizeValues returns the possible values for the SearchContextSize const type.
func PossibleSearchContextSizeValues() []SearchContextSize {
	return []SearchContextSize{
		SearchContextSizeHigh,
		SearchContextSizeLow,
		SearchContextSizeMedium,
	}
}

type ToolSearchExecutionType string

const (
	ToolSearchExecutionTypeClient ToolSearchExecutionType = "client"
	ToolSearchExecutionTypeServer ToolSearchExecutionType = "server"
)

// PossibleToolSearchExecutionTypeValues returns the possible values for the ToolSearchExecutionType const type.
func PossibleToolSearchExecutionTypeValues() []ToolSearchExecutionType {
	return []ToolSearchExecutionType{
		ToolSearchExecutionTypeClient,
		ToolSearchExecutionTypeServer,
	}
}

type ToolType string

const (
	ToolTypeA2APreview                 ToolType = "a2a_preview"
	ToolTypeApplyPatch                 ToolType = "apply_patch"
	ToolTypeAzureAiSearch              ToolType = "azure_ai_search"
	ToolTypeAzureFunction              ToolType = "azure_function"
	ToolTypeBingCustomSearchPreview    ToolType = "bing_custom_search_preview"
	ToolTypeBingGrounding              ToolType = "bing_grounding"
	ToolTypeBrowserAutomationPreview   ToolType = "browser_automation_preview"
	ToolTypeCaptureStructuredOutputs   ToolType = "capture_structured_outputs"
	ToolTypeCodeInterpreter            ToolType = "code_interpreter"
	ToolTypeComputer                   ToolType = "computer"
	ToolTypeComputerUsePreview         ToolType = "computer_use_preview"
	ToolTypeCustom                     ToolType = "custom"
	ToolTypeFabricDataagentPreview     ToolType = "fabric_dataagent_preview"
	ToolTypeFabricIqPreview            ToolType = "fabric_iq_preview"
	ToolTypeFileSearch                 ToolType = "file_search"
	ToolTypeFunction                   ToolType = "function"
	ToolTypeImageGeneration            ToolType = "image_generation"
	ToolTypeLocalShell                 ToolType = "local_shell"
	ToolTypeMcp                        ToolType = "mcp"
	ToolTypeMemorySearchPreview        ToolType = "memory_search_preview"
	ToolTypeNamespace                  ToolType = "namespace"
	ToolTypeOpenapi                    ToolType = "openapi"
	ToolTypeReminderPreview            ToolType = "reminder_preview"
	ToolTypeSharepointGroundingPreview ToolType = "sharepoint_grounding_preview"
	ToolTypeShell                      ToolType = "shell"
	ToolTypeToolSearch                 ToolType = "tool_search"
	ToolTypeToolboxSearchPreview       ToolType = "toolbox_search_preview"
	ToolTypeWebSearch                  ToolType = "web_search"
	ToolTypeWebSearchPreview           ToolType = "web_search_preview"
	ToolTypeWorkIqPreview              ToolType = "work_iq_preview"
)

// PossibleToolTypeValues returns the possible values for the ToolType const type.
func PossibleToolTypeValues() []ToolType {
	return []ToolType{
		ToolTypeA2APreview,
		ToolTypeApplyPatch,
		ToolTypeAzureAiSearch,
		ToolTypeAzureFunction,
		ToolTypeBingCustomSearchPreview,
		ToolTypeBingGrounding,
		ToolTypeBrowserAutomationPreview,
		ToolTypeCaptureStructuredOutputs,
		ToolTypeCodeInterpreter,
		ToolTypeComputer,
		ToolTypeComputerUsePreview,
		ToolTypeCustom,
		ToolTypeFabricDataagentPreview,
		ToolTypeFabricIqPreview,
		ToolTypeFileSearch,
		ToolTypeFunction,
		ToolTypeImageGeneration,
		ToolTypeLocalShell,
		ToolTypeMcp,
		ToolTypeMemorySearchPreview,
		ToolTypeNamespace,
		ToolTypeOpenapi,
		ToolTypeReminderPreview,
		ToolTypeSharepointGroundingPreview,
		ToolTypeShell,
		ToolTypeToolSearch,
		ToolTypeToolboxSearchPreview,
		ToolTypeWebSearch,
		ToolTypeWebSearchPreview,
		ToolTypeWorkIqPreview,
	}
}

// ToolboxToolType - Supported tool types for tools stored in a toolbox.
type ToolboxToolType string

const (
	ToolboxToolTypeA2APreview               ToolboxToolType = "a2a_preview"
	ToolboxToolTypeAzureAiSearch            ToolboxToolType = "azure_ai_search"
	ToolboxToolTypeBrowserAutomationPreview ToolboxToolType = "browser_automation_preview"
	ToolboxToolTypeCodeInterpreter          ToolboxToolType = "code_interpreter"
	ToolboxToolTypeFabricIqPreview          ToolboxToolType = "fabric_iq_preview"
	ToolboxToolTypeFileSearch               ToolboxToolType = "file_search"
	ToolboxToolTypeMcp                      ToolboxToolType = "mcp"
	ToolboxToolTypeOpenapi                  ToolboxToolType = "openapi"
	ToolboxToolTypeReminderPreview          ToolboxToolType = "reminder_preview"
	ToolboxToolTypeToolboxSearchPreview     ToolboxToolType = "toolbox_search_preview"
	ToolboxToolTypeWebSearch                ToolboxToolType = "web_search"
	ToolboxToolTypeWorkIqPreview            ToolboxToolType = "work_iq_preview"
)

// PossibleToolboxToolTypeValues returns the possible values for the ToolboxToolType const type.
func PossibleToolboxToolTypeValues() []ToolboxToolType {
	return []ToolboxToolType{
		ToolboxToolTypeA2APreview,
		ToolboxToolTypeAzureAiSearch,
		ToolboxToolTypeBrowserAutomationPreview,
		ToolboxToolTypeCodeInterpreter,
		ToolboxToolTypeFabricIqPreview,
		ToolboxToolTypeFileSearch,
		ToolboxToolTypeMcp,
		ToolboxToolTypeOpenapi,
		ToolboxToolTypeReminderPreview,
		ToolboxToolTypeToolboxSearchPreview,
		ToolboxToolTypeWebSearch,
		ToolboxToolTypeWorkIqPreview,
	}
}

// TreatmentEffectType - Treatment Effect Type.
type TreatmentEffectType string

const (
	// TreatmentEffectTypeChanged - Indicates the metric changed with statistical significance, but the direction is neutral.
	TreatmentEffectTypeChanged TreatmentEffectType = "Changed"
	// TreatmentEffectTypeDegraded - Indicates the treatment significantly degraded the metric compared to baseline.
	TreatmentEffectTypeDegraded TreatmentEffectType = "Degraded"
	// TreatmentEffectTypeImproved - Indicates the treatment significantly improved the metric compared to baseline.
	TreatmentEffectTypeImproved TreatmentEffectType = "Improved"
	// TreatmentEffectTypeInconclusive - No significant difference between treatment and baseline.
	TreatmentEffectTypeInconclusive TreatmentEffectType = "Inconclusive"
	// TreatmentEffectTypeTooFewSamples - Not enough samples to determine treatment effect.
	TreatmentEffectTypeTooFewSamples TreatmentEffectType = "TooFewSamples"
)

// PossibleTreatmentEffectTypeValues returns the possible values for the TreatmentEffectType const type.
func PossibleTreatmentEffectTypeValues() []TreatmentEffectType {
	return []TreatmentEffectType{
		TreatmentEffectTypeChanged,
		TreatmentEffectTypeDegraded,
		TreatmentEffectTypeImproved,
		TreatmentEffectTypeInconclusive,
		TreatmentEffectTypeTooFewSamples,
	}
}

// TriggerType - Type of the trigger.
type TriggerType string

const (
	// TriggerTypeCron - Cron based trigger.
	TriggerTypeCron TriggerType = "Cron"
	// TriggerTypeOneTime - One-time trigger.
	TriggerTypeOneTime TriggerType = "OneTime"
	// TriggerTypeRecurrence - Recurrence based trigger.
	TriggerTypeRecurrence TriggerType = "Recurrence"
)

// PossibleTriggerTypeValues returns the possible values for the TriggerType const type.
func PossibleTriggerTypeValues() []TriggerType {
	return []TriggerType{
		TriggerTypeCron,
		TriggerTypeOneTime,
		TriggerTypeRecurrence,
	}
}

type WebSearchToolSearchContextSize string

const (
	WebSearchToolSearchContextSizeHigh   WebSearchToolSearchContextSize = "high"
	WebSearchToolSearchContextSizeLow    WebSearchToolSearchContextSize = "low"
	WebSearchToolSearchContextSizeMedium WebSearchToolSearchContextSize = "medium"
)

// PossibleWebSearchToolSearchContextSizeValues returns the possible values for the WebSearchToolSearchContextSize const type.
func PossibleWebSearchToolSearchContextSizeValues() []WebSearchToolSearchContextSize {
	return []WebSearchToolSearchContextSize{
		WebSearchToolSearchContextSizeHigh,
		WebSearchToolSearchContextSizeLow,
		WebSearchToolSearchContextSizeMedium,
	}
}
