// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// EvaluatorGenerationJobsClient contains the methods for the EvaluatorGenerationJobs group.
// Don't use this type directly, use [Client.NewEvaluatorGenerationJobsClient] instead.
//
// Generated from API version v1
type EvaluatorGenerationJobsClient struct {
	internal *azcore.Client
	endpoint string
}

// Cancel - Cancel an evaluator generation job
//
// Cancels an evaluator generation job by its ID.
// If the operation fails it returns an *azcore.ResponseError type.
//   - jobID - The ID of the job to cancel.
//   - options - EvaluatorGenerationJobsClientCancelOptions contains the optional parameters for the EvaluatorGenerationJobsClient.Cancel
//     method.
func (client *EvaluatorGenerationJobsClient) Cancel(ctx context.Context, jobID string, options *EvaluatorGenerationJobsClientCancelOptions) (EvaluatorGenerationJobsClientCancelResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorGenerationJobsClient.Cancel", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.cancelCreateRequest(ctx, jobID, options)
	if err != nil {
		return EvaluatorGenerationJobsClientCancelResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorGenerationJobsClientCancelResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorGenerationJobsClientCancelResponse{}, err
	}
	resp, err := client.cancelHandleResponse(httpResp)
	return resp, err
}

// cancelCreateRequest creates the Cancel request.
func (client *EvaluatorGenerationJobsClient) cancelCreateRequest(ctx context.Context, jobID string, options *EvaluatorGenerationJobsClientCancelOptions) (*policy.Request, error) {
	urlPath := "/evaluator_generation_jobs/{jobId}:cancel"
	if jobID == "" {
		return nil, errors.New("parameter jobID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{jobId}", url.PathEscape(jobID))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	}
	return req, nil
}

// cancelHandleResponse handles the Cancel response.
func (client *EvaluatorGenerationJobsClient) cancelHandleResponse(resp *http.Response) (EvaluatorGenerationJobsClientCancelResponse, error) {
	result := EvaluatorGenerationJobsClientCancelResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluatorGenerationJob); err != nil {
		return EvaluatorGenerationJobsClientCancelResponse{}, err
	}
	return result, nil
}

// Create - Create an evaluator generation job
//
// Creates an evaluator generation job. The service generates rubric-based evaluator
// definitions from the provided source materials asynchronously.
// If the operation fails it returns an *azcore.ResponseError type.
//   - job - The job to create.
//   - options - EvaluatorGenerationJobsClientCreateOptions contains the optional parameters for the EvaluatorGenerationJobsClient.Create
//     method.
func (client *EvaluatorGenerationJobsClient) Create(ctx context.Context, job EvaluatorGenerationJob, options *EvaluatorGenerationJobsClientCreateOptions) (EvaluatorGenerationJobsClientCreateResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorGenerationJobsClient.Create", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createCreateRequest(ctx, job, options)
	if err != nil {
		return EvaluatorGenerationJobsClientCreateResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorGenerationJobsClientCreateResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusCreated) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorGenerationJobsClientCreateResponse{}, err
	}
	resp, err := client.createHandleResponse(httpResp)
	return resp, err
}

// createCreateRequest creates the Create request.
func (client *EvaluatorGenerationJobsClient) createCreateRequest(ctx context.Context, job EvaluatorGenerationJob, options *EvaluatorGenerationJobsClientCreateOptions) (*policy.Request, error) {
	urlPath := "/evaluator_generation_jobs"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	}
	if options != nil && options.OperationID != nil {
		req.Raw().Header["Operation-Id"] = []string{*options.OperationID}
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, job); err != nil {
		return nil, err
	}
	return req, nil
}

// createHandleResponse handles the Create response.
func (client *EvaluatorGenerationJobsClient) createHandleResponse(resp *http.Response) (EvaluatorGenerationJobsClientCreateResponse, error) {
	result := EvaluatorGenerationJobsClientCreateResponse{}
	if val := resp.Header.Get("Location"); val != "" {
		result.Location = &val
	}
	if val := resp.Header.Get("Operation-Location"); val != "" {
		result.OperationLocation = &val
	}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluatorGenerationJob); err != nil {
		return EvaluatorGenerationJobsClientCreateResponse{}, err
	}
	return result, nil
}

// Delete - Delete an evaluator generation job
//
// Deletes an evaluator generation job by its ID. Deletes the job record only;
// the generated evaluator (if any) is preserved.
// If the operation fails it returns an *azcore.ResponseError type.
//   - jobID - The ID of the job to delete.
//   - options - EvaluatorGenerationJobsClientDeleteOptions contains the optional parameters for the EvaluatorGenerationJobsClient.Delete
//     method.
func (client *EvaluatorGenerationJobsClient) Delete(ctx context.Context, jobID string, options *EvaluatorGenerationJobsClientDeleteOptions) (EvaluatorGenerationJobsClientDeleteResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorGenerationJobsClient.Delete", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteCreateRequest(ctx, jobID, options)
	if err != nil {
		return EvaluatorGenerationJobsClientDeleteResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorGenerationJobsClientDeleteResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusNoContent) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorGenerationJobsClientDeleteResponse{}, err
	}
	return EvaluatorGenerationJobsClientDeleteResponse{}, nil
}

// deleteCreateRequest creates the Delete request.
func (client *EvaluatorGenerationJobsClient) deleteCreateRequest(ctx context.Context, jobID string, options *EvaluatorGenerationJobsClientDeleteOptions) (*policy.Request, error) {
	urlPath := "/evaluator_generation_jobs/{jobId}"
	if jobID == "" {
		return nil, errors.New("parameter jobID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{jobId}", url.PathEscape(jobID))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	}
	return req, nil
}

// Get - Get an evaluator generation job
//
// Gets the details of an evaluator generation job by its ID.
// If the operation fails it returns an *azcore.ResponseError type.
//   - jobID - The ID of the job.
//   - options - EvaluatorGenerationJobsClientGetOptions contains the optional parameters for the EvaluatorGenerationJobsClient.Get
//     method.
func (client *EvaluatorGenerationJobsClient) Get(ctx context.Context, jobID string, options *EvaluatorGenerationJobsClientGetOptions) (EvaluatorGenerationJobsClientGetResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorGenerationJobsClient.Get", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, jobID, options)
	if err != nil {
		return EvaluatorGenerationJobsClientGetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorGenerationJobsClientGetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorGenerationJobsClientGetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the Get request.
func (client *EvaluatorGenerationJobsClient) getCreateRequest(ctx context.Context, jobID string, options *EvaluatorGenerationJobsClientGetOptions) (*policy.Request, error) {
	urlPath := "/evaluator_generation_jobs/{jobId}"
	if jobID == "" {
		return nil, errors.New("parameter jobID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{jobId}", url.PathEscape(jobID))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	}
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *EvaluatorGenerationJobsClient) getHandleResponse(resp *http.Response) (EvaluatorGenerationJobsClientGetResponse, error) {
	result := EvaluatorGenerationJobsClientGetResponse{}
	if val := resp.Header.Get("Retry-After"); val != "" {
		retryAfter32, err := strconv.ParseInt(val, 10, 32)
		retryAfter := int32(retryAfter32)
		if err != nil {
			return EvaluatorGenerationJobsClientGetResponse{}, err
		}
		result.RetryAfter = &retryAfter
	}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluatorGenerationJob); err != nil {
		return EvaluatorGenerationJobsClientGetResponse{}, err
	}
	return result, nil
}

// NewListPager - List evaluator generation jobs
//
// Returns a list of evaluator generation jobs. The List API has up to a few
// seconds of propagation delay, so a recently created job may not appear
// immediately; use the Get evaluator generation job API with the job ID to
// retrieve a specific job without delay.
//   - options - EvaluatorGenerationJobsClientListOptions contains the optional parameters for the EvaluatorGenerationJobsClient.NewListPager
//     method.
func (client *EvaluatorGenerationJobsClient) NewListPager(options *EvaluatorGenerationJobsClientListOptions) *runtime.Pager[EvaluatorGenerationJobsClientListResponse] {
	return runtime.NewPager(runtime.PagingHandler[EvaluatorGenerationJobsClientListResponse]{
		More: func(page EvaluatorGenerationJobsClientListResponse) bool {
			return page.LastID != nil && len(*page.LastID) > 0
		},
		Fetcher: func(ctx context.Context, page *EvaluatorGenerationJobsClientListResponse) (EvaluatorGenerationJobsClientListResponse, error) {
			nextOpts := EvaluatorGenerationJobsClientListOptions{}
			if options != nil {
				nextOpts = *options
			}
			if page != nil {
				nextOpts.After = page.LastID
			}
			req, err := client.listCreateRequest(ctx, &nextOpts)
			if err != nil {
				return EvaluatorGenerationJobsClientListResponse{}, err
			}
			resp, err := client.internal.Pipeline().Do(req)
			if err != nil {
				return EvaluatorGenerationJobsClientListResponse{}, err
			}
			if !runtime.HasStatusCode(resp, http.StatusOK) {
				return EvaluatorGenerationJobsClientListResponse{}, runtime.NewResponseError(resp)
			}
			return client.listHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listCreateRequest creates the List request.
func (client *EvaluatorGenerationJobsClient) listCreateRequest(ctx context.Context, options *EvaluatorGenerationJobsClientListOptions) (*policy.Request, error) {
	urlPath := "/evaluator_generation_jobs"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.After != nil {
		reqQP.Set("after", *options.After)
	}
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Before != nil {
		reqQP.Set("before", *options.Before)
	}
	if options != nil && options.Limit != nil {
		reqQP.Set("limit", strconv.FormatInt(int64(*options.Limit), 10))
	}
	if options != nil && options.Order != nil {
		reqQP.Set("order", string(*options.Order))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	}
	return req, nil
}

// listHandleResponse handles the List response.
func (client *EvaluatorGenerationJobsClient) listHandleResponse(resp *http.Response) (EvaluatorGenerationJobsClientListResponse, error) {
	result := EvaluatorGenerationJobsClientListResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.AgentsPagedResultEvaluatorGenerationJob); err != nil {
		return EvaluatorGenerationJobsClientListResponse{}, err
	}
	return result, nil
}
