// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// EvaluationTaxonomiesClient contains the methods for the EvaluationTaxonomies group.
// Don't use this type directly, use [Client.NewEvaluationTaxonomiesClient] instead.
//
// Generated from API version v1
type EvaluationTaxonomiesClient struct {
	internal *azcore.Client
	endpoint string
}

// Create - Create an evaluation taxonomy
//
// Creates or replaces the specified evaluation taxonomy with the provided definition.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the evaluation taxonomy.
//   - taxonomy - The evaluation taxonomy.
//   - options - EvaluationTaxonomiesClientCreateOptions contains the optional parameters for the EvaluationTaxonomiesClient.Create
//     method.
func (client *EvaluationTaxonomiesClient) Create(ctx context.Context, name string, taxonomy EvaluationTaxonomy, options *EvaluationTaxonomiesClientCreateOptions) (EvaluationTaxonomiesClientCreateResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluationTaxonomiesClient.Create", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createCreateRequest(ctx, name, taxonomy, options)
	if err != nil {
		return EvaluationTaxonomiesClientCreateResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluationTaxonomiesClientCreateResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK, http.StatusCreated) {
		err = runtime.NewResponseError(httpResp)
		return EvaluationTaxonomiesClientCreateResponse{}, err
	}
	resp, err := client.createHandleResponse(httpResp)
	return resp, err
}

// createCreateRequest creates the Create request.
func (client *EvaluationTaxonomiesClient) createCreateRequest(ctx context.Context, name string, taxonomy EvaluationTaxonomy, _ *EvaluationTaxonomiesClientCreateOptions) (*policy.Request, error) {
	urlPath := "/evaluationtaxonomies/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, taxonomy); err != nil {
		return nil, err
	}
	return req, nil
}

// createHandleResponse handles the Create response.
func (client *EvaluationTaxonomiesClient) createHandleResponse(resp *http.Response) (EvaluationTaxonomiesClientCreateResponse, error) {
	result := EvaluationTaxonomiesClientCreateResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluationTaxonomy); err != nil {
		return EvaluationTaxonomiesClientCreateResponse{}, err
	}
	return result, nil
}

// Delete - Delete an evaluation taxonomy
//
// Removes the specified evaluation taxonomy from the project.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - options - EvaluationTaxonomiesClientDeleteOptions contains the optional parameters for the EvaluationTaxonomiesClient.Delete
//     method.
func (client *EvaluationTaxonomiesClient) Delete(ctx context.Context, name string, options *EvaluationTaxonomiesClientDeleteOptions) (EvaluationTaxonomiesClientDeleteResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluationTaxonomiesClient.Delete", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteCreateRequest(ctx, name, options)
	if err != nil {
		return EvaluationTaxonomiesClientDeleteResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluationTaxonomiesClientDeleteResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusNoContent) {
		err = runtime.NewResponseError(httpResp)
		return EvaluationTaxonomiesClientDeleteResponse{}, err
	}
	return EvaluationTaxonomiesClientDeleteResponse{}, nil
}

// deleteCreateRequest creates the Delete request.
func (client *EvaluationTaxonomiesClient) deleteCreateRequest(ctx context.Context, name string, _ *EvaluationTaxonomiesClientDeleteOptions) (*policy.Request, error) {
	urlPath := "/evaluationtaxonomies/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	return req, nil
}

// Get - Get an evaluation taxonomy
//
// Retrieves the specified evaluation taxonomy.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - options - EvaluationTaxonomiesClientGetOptions contains the optional parameters for the EvaluationTaxonomiesClient.Get
//     method.
func (client *EvaluationTaxonomiesClient) Get(ctx context.Context, name string, options *EvaluationTaxonomiesClientGetOptions) (EvaluationTaxonomiesClientGetResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluationTaxonomiesClient.Get", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, name, options)
	if err != nil {
		return EvaluationTaxonomiesClientGetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluationTaxonomiesClientGetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluationTaxonomiesClientGetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the Get request.
func (client *EvaluationTaxonomiesClient) getCreateRequest(ctx context.Context, name string, _ *EvaluationTaxonomiesClientGetOptions) (*policy.Request, error) {
	urlPath := "/evaluationtaxonomies/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *EvaluationTaxonomiesClient) getHandleResponse(resp *http.Response) (EvaluationTaxonomiesClientGetResponse, error) {
	result := EvaluationTaxonomiesClientGetResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluationTaxonomy); err != nil {
		return EvaluationTaxonomiesClientGetResponse{}, err
	}
	return result, nil
}

// NewListPager - List evaluation taxonomies
//
// Returns the evaluation taxonomies available in the project, optionally filtered by input name or input type.
//   - options - EvaluationTaxonomiesClientListOptions contains the optional parameters for the EvaluationTaxonomiesClient.NewListPager
//     method.
func (client *EvaluationTaxonomiesClient) NewListPager(options *EvaluationTaxonomiesClientListOptions) *runtime.Pager[EvaluationTaxonomiesClientListResponse] {
	return runtime.NewPager(runtime.PagingHandler[EvaluationTaxonomiesClientListResponse]{
		More: func(page EvaluationTaxonomiesClientListResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *EvaluationTaxonomiesClientListResponse) (EvaluationTaxonomiesClientListResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listCreateRequest(ctx, options)
			}, nil)
			if err != nil {
				return EvaluationTaxonomiesClientListResponse{}, err
			}
			return client.listHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listCreateRequest creates the List request.
func (client *EvaluationTaxonomiesClient) listCreateRequest(ctx context.Context, options *EvaluationTaxonomiesClientListOptions) (*policy.Request, error) {
	urlPath := "/evaluationtaxonomies"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	if options != nil && options.InputName != nil {
		reqQP.Set("inputName", *options.InputName)
	}
	if options != nil && options.InputType != nil {
		reqQP.Set("inputType", *options.InputType)
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	return req, nil
}

// listHandleResponse handles the List response.
func (client *EvaluationTaxonomiesClient) listHandleResponse(resp *http.Response) (EvaluationTaxonomiesClientListResponse, error) {
	result := EvaluationTaxonomiesClientListResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedEvaluationTaxonomy); err != nil {
		return EvaluationTaxonomiesClientListResponse{}, err
	}
	return result, nil
}

// Update - Update an evaluation taxonomy
//
// Update an evaluation taxonomy.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the evaluation taxonomy.
//   - taxonomy - The evaluation taxonomy.
//   - options - EvaluationTaxonomiesClientUpdateOptions contains the optional parameters for the EvaluationTaxonomiesClient.Update
//     method.
func (client *EvaluationTaxonomiesClient) Update(ctx context.Context, name string, taxonomy EvaluationTaxonomy, options *EvaluationTaxonomiesClientUpdateOptions) (EvaluationTaxonomiesClientUpdateResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluationTaxonomiesClient.Update", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.updateCreateRequest(ctx, name, taxonomy, options)
	if err != nil {
		return EvaluationTaxonomiesClientUpdateResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluationTaxonomiesClientUpdateResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluationTaxonomiesClientUpdateResponse{}, err
	}
	resp, err := client.updateHandleResponse(httpResp)
	return resp, err
}

// updateCreateRequest creates the Update request.
func (client *EvaluationTaxonomiesClient) updateCreateRequest(ctx context.Context, name string, taxonomy EvaluationTaxonomy, _ *EvaluationTaxonomiesClientUpdateOptions) (*policy.Request, error) {
	urlPath := "/evaluationtaxonomies/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPatch, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, taxonomy); err != nil {
		return nil, err
	}
	return req, nil
}

// updateHandleResponse handles the Update response.
func (client *EvaluationTaxonomiesClient) updateHandleResponse(resp *http.Response) (EvaluationTaxonomiesClientUpdateResponse, error) {
	result := EvaluationTaxonomiesClientUpdateResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluationTaxonomy); err != nil {
		return EvaluationTaxonomiesClientUpdateResponse{}, err
	}
	return result, nil
}
