// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// EvaluatorsClient contains the methods for the Evaluators group.
// Don't use this type directly, use [Client.NewEvaluatorsClient] instead.
//
// Generated from API version v1
type EvaluatorsClient struct {
	internal *azcore.Client
	endpoint string
}

// CreateVersion - Create an evaluator version
//
// Creates a new evaluator version with an auto-incremented version identifier.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - options - EvaluatorsClientCreateVersionOptions contains the optional parameters for the EvaluatorsClient.CreateVersion
//     method.
func (client *EvaluatorsClient) CreateVersion(ctx context.Context, name string, evaluatorVersion EvaluatorVersion, options *EvaluatorsClientCreateVersionOptions) (EvaluatorsClientCreateVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorsClient.CreateVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createVersionCreateRequest(ctx, name, evaluatorVersion, options)
	if err != nil {
		return EvaluatorsClientCreateVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorsClientCreateVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusCreated) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorsClientCreateVersionResponse{}, err
	}
	resp, err := client.createVersionHandleResponse(httpResp)
	return resp, err
}

// createVersionCreateRequest creates the CreateVersion request.
func (client *EvaluatorsClient) createVersionCreateRequest(ctx context.Context, name string, evaluatorVersion EvaluatorVersion, _ *EvaluatorsClientCreateVersionOptions) (*policy.Request, error) {
	urlPath := "/evaluators/{name}/versions"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, evaluatorVersion); err != nil {
		return nil, err
	}
	return req, nil
}

// createVersionHandleResponse handles the CreateVersion response.
func (client *EvaluatorsClient) createVersionHandleResponse(resp *http.Response) (EvaluatorsClientCreateVersionResponse, error) {
	result := EvaluatorsClientCreateVersionResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluatorVersion); err != nil {
		return EvaluatorsClientCreateVersionResponse{}, err
	}
	return result, nil
}

// DeleteVersion - Delete an evaluator version
//
// Removes the specified evaluator version. Returns 204 whether the version existed or not.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - version - The version of the EvaluatorVersion to delete.
//   - options - EvaluatorsClientDeleteVersionOptions contains the optional parameters for the EvaluatorsClient.DeleteVersion
//     method.
func (client *EvaluatorsClient) DeleteVersion(ctx context.Context, name string, version string, options *EvaluatorsClientDeleteVersionOptions) (EvaluatorsClientDeleteVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorsClient.DeleteVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteVersionCreateRequest(ctx, name, version, options)
	if err != nil {
		return EvaluatorsClientDeleteVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorsClientDeleteVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusNoContent) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorsClientDeleteVersionResponse{}, err
	}
	return EvaluatorsClientDeleteVersionResponse{}, nil
}

// deleteVersionCreateRequest creates the DeleteVersion request.
func (client *EvaluatorsClient) deleteVersionCreateRequest(ctx context.Context, name string, version string, _ *EvaluatorsClientDeleteVersionOptions) (*policy.Request, error) {
	urlPath := "/evaluators/{name}/versions/{version}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	return req, nil
}

// GetCredentials - Get evaluator credentials
//
// Retrieves SAS credentials for accessing the storage account associated with the specified evaluator version.
// If the operation fails it returns an *azcore.ResponseError type.
//   - credentialRequest - The credential request parameters
//   - version - The specific version id of the EvaluatorVersion to operate on.
//   - options - EvaluatorsClientGetCredentialsOptions contains the optional parameters for the EvaluatorsClient.GetCredentials
//     method.
func (client *EvaluatorsClient) GetCredentials(ctx context.Context, name string, credentialRequest EvaluatorCredentialRequest, version string, options *EvaluatorsClientGetCredentialsOptions) (EvaluatorsClientGetCredentialsResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorsClient.GetCredentials", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCredentialsCreateRequest(ctx, name, credentialRequest, version, options)
	if err != nil {
		return EvaluatorsClientGetCredentialsResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorsClientGetCredentialsResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorsClientGetCredentialsResponse{}, err
	}
	resp, err := client.getCredentialsHandleResponse(httpResp)
	return resp, err
}

// getCredentialsCreateRequest creates the GetCredentials request.
func (client *EvaluatorsClient) getCredentialsCreateRequest(ctx context.Context, name string, credentialRequest EvaluatorCredentialRequest, version string, options *EvaluatorsClientGetCredentialsOptions) (*policy.Request, error) {
	urlPath := "/evaluators/{name}/versions/{version}/credentials"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, credentialRequest); err != nil {
		return nil, err
	}
	return req, nil
}

// getCredentialsHandleResponse handles the GetCredentials response.
func (client *EvaluatorsClient) getCredentialsHandleResponse(resp *http.Response) (EvaluatorsClientGetCredentialsResponse, error) {
	result := EvaluatorsClientGetCredentialsResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.DatasetCredential); err != nil {
		return EvaluatorsClientGetCredentialsResponse{}, err
	}
	return result, nil
}

// GetVersion - Get an evaluator version
//
// Retrieves the specified evaluator version, returning 404 if it does not exist.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - version - The specific version id of the EvaluatorVersion to retrieve.
//   - options - EvaluatorsClientGetVersionOptions contains the optional parameters for the EvaluatorsClient.GetVersion method.
func (client *EvaluatorsClient) GetVersion(ctx context.Context, name string, version string, options *EvaluatorsClientGetVersionOptions) (EvaluatorsClientGetVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorsClient.GetVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getVersionCreateRequest(ctx, name, version, options)
	if err != nil {
		return EvaluatorsClientGetVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorsClientGetVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorsClientGetVersionResponse{}, err
	}
	resp, err := client.getVersionHandleResponse(httpResp)
	return resp, err
}

// getVersionCreateRequest creates the GetVersion request.
func (client *EvaluatorsClient) getVersionCreateRequest(ctx context.Context, name string, version string, _ *EvaluatorsClientGetVersionOptions) (*policy.Request, error) {
	urlPath := "/evaluators/{name}/versions/{version}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	return req, nil
}

// getVersionHandleResponse handles the GetVersion response.
func (client *EvaluatorsClient) getVersionHandleResponse(resp *http.Response) (EvaluatorsClientGetVersionResponse, error) {
	result := EvaluatorsClientGetVersionResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluatorVersion); err != nil {
		return EvaluatorsClientGetVersionResponse{}, err
	}
	return result, nil
}

// NewListLatestVersionsPager - List latest evaluator versions
//
// Lists the latest version of each evaluator
//   - options - EvaluatorsClientListLatestVersionsOptions contains the optional parameters for the EvaluatorsClient.NewListLatestVersionsPager
//     method.
func (client *EvaluatorsClient) NewListLatestVersionsPager(options *EvaluatorsClientListLatestVersionsOptions) *runtime.Pager[EvaluatorsClientListLatestVersionsResponse] {
	return runtime.NewPager(runtime.PagingHandler[EvaluatorsClientListLatestVersionsResponse]{
		More: func(page EvaluatorsClientListLatestVersionsResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *EvaluatorsClientListLatestVersionsResponse) (EvaluatorsClientListLatestVersionsResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listLatestVersionsCreateRequest(ctx, options)
			}, nil)
			if err != nil {
				return EvaluatorsClientListLatestVersionsResponse{}, err
			}
			return client.listLatestVersionsHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listLatestVersionsCreateRequest creates the ListLatestVersions request.
func (client *EvaluatorsClient) listLatestVersionsCreateRequest(ctx context.Context, options *EvaluatorsClientListLatestVersionsOptions) (*policy.Request, error) {
	urlPath := "/evaluators"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Limit != nil {
		reqQP.Set("limit", strconv.FormatInt(int64(*options.Limit), 10))
	}
	if options != nil && options.Type != nil {
		reqQP.Set("type", string(*options.Type))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	return req, nil
}

// listLatestVersionsHandleResponse handles the ListLatestVersions response.
func (client *EvaluatorsClient) listLatestVersionsHandleResponse(resp *http.Response) (EvaluatorsClientListLatestVersionsResponse, error) {
	result := EvaluatorsClientListLatestVersionsResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedEvaluatorVersion); err != nil {
		return EvaluatorsClientListLatestVersionsResponse{}, err
	}
	return result, nil
}

// NewListVersionsPager - List evaluator versions
//
// Returns the available versions for the specified evaluator.
//   - name - The name of the resource
//   - options - EvaluatorsClientListVersionsOptions contains the optional parameters for the EvaluatorsClient.NewListVersionsPager
//     method.
func (client *EvaluatorsClient) NewListVersionsPager(name string, options *EvaluatorsClientListVersionsOptions) *runtime.Pager[EvaluatorsClientListVersionsResponse] {
	return runtime.NewPager(runtime.PagingHandler[EvaluatorsClientListVersionsResponse]{
		More: func(page EvaluatorsClientListVersionsResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *EvaluatorsClientListVersionsResponse) (EvaluatorsClientListVersionsResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listVersionsCreateRequest(ctx, name, options)
			}, nil)
			if err != nil {
				return EvaluatorsClientListVersionsResponse{}, err
			}
			return client.listVersionsHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listVersionsCreateRequest creates the ListVersions request.
func (client *EvaluatorsClient) listVersionsCreateRequest(ctx context.Context, name string, options *EvaluatorsClientListVersionsOptions) (*policy.Request, error) {
	urlPath := "/evaluators/{name}/versions"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Limit != nil {
		reqQP.Set("limit", strconv.FormatInt(int64(*options.Limit), 10))
	}
	if options != nil && options.Type != nil {
		reqQP.Set("type", string(*options.Type))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	return req, nil
}

// listVersionsHandleResponse handles the ListVersions response.
func (client *EvaluatorsClient) listVersionsHandleResponse(resp *http.Response) (EvaluatorsClientListVersionsResponse, error) {
	result := EvaluatorsClientListVersionsResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedEvaluatorVersion); err != nil {
		return EvaluatorsClientListVersionsResponse{}, err
	}
	return result, nil
}

// StartPendingUpload - Start a pending upload
//
// Initiates a new pending upload or retrieves an existing one for the specified evaluator version.
// If the operation fails it returns an *azcore.ResponseError type.
//   - version - The specific version id of the EvaluatorVersion to operate on.
//   - pendingUploadRequest - The pending upload request parameters
//   - options - EvaluatorsClientStartPendingUploadOptions contains the optional parameters for the EvaluatorsClient.StartPendingUpload
//     method.
func (client *EvaluatorsClient) StartPendingUpload(ctx context.Context, name string, version string, pendingUploadRequest PendingUploadRequest, options *EvaluatorsClientStartPendingUploadOptions) (EvaluatorsClientStartPendingUploadResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorsClient.StartPendingUpload", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.startPendingUploadCreateRequest(ctx, name, version, pendingUploadRequest, options)
	if err != nil {
		return EvaluatorsClientStartPendingUploadResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorsClientStartPendingUploadResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorsClientStartPendingUploadResponse{}, err
	}
	resp, err := client.startPendingUploadHandleResponse(httpResp)
	return resp, err
}

// startPendingUploadCreateRequest creates the StartPendingUpload request.
func (client *EvaluatorsClient) startPendingUploadCreateRequest(ctx context.Context, name string, version string, pendingUploadRequest PendingUploadRequest, options *EvaluatorsClientStartPendingUploadOptions) (*policy.Request, error) {
	urlPath := "/evaluators/{name}/versions/{version}/startPendingUpload"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, pendingUploadRequest); err != nil {
		return nil, err
	}
	return req, nil
}

// startPendingUploadHandleResponse handles the StartPendingUpload response.
func (client *EvaluatorsClient) startPendingUploadHandleResponse(resp *http.Response) (EvaluatorsClientStartPendingUploadResponse, error) {
	result := EvaluatorsClientStartPendingUploadResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PendingUploadResponse); err != nil {
		return EvaluatorsClientStartPendingUploadResponse{}, err
	}
	return result, nil
}

// UpdateVersion - Update an evaluator version
//
// Updates the specified evaluator version in place.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - version - The version of the EvaluatorVersion to update.
//   - evaluatorVersion - Evaluator resource
//   - options - EvaluatorsClientUpdateVersionOptions contains the optional parameters for the EvaluatorsClient.UpdateVersion
//     method.
func (client *EvaluatorsClient) UpdateVersion(ctx context.Context, name string, version string, evaluatorVersion EvaluatorVersion, options *EvaluatorsClientUpdateVersionOptions) (EvaluatorsClientUpdateVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluatorsClient.UpdateVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.updateVersionCreateRequest(ctx, name, version, evaluatorVersion, options)
	if err != nil {
		return EvaluatorsClientUpdateVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluatorsClientUpdateVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluatorsClientUpdateVersionResponse{}, err
	}
	resp, err := client.updateVersionHandleResponse(httpResp)
	return resp, err
}

// updateVersionCreateRequest creates the UpdateVersion request.
func (client *EvaluatorsClient) updateVersionCreateRequest(ctx context.Context, name string, version string, evaluatorVersion EvaluatorVersion, _ *EvaluatorsClientUpdateVersionOptions) (*policy.Request, error) {
	urlPath := "/evaluators/{name}/versions/{version}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodPatch, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, evaluatorVersion); err != nil {
		return nil, err
	}
	return req, nil
}

// updateVersionHandleResponse handles the UpdateVersion response.
func (client *EvaluatorsClient) updateVersionHandleResponse(resp *http.Response) (EvaluatorsClientUpdateVersionResponse, error) {
	result := EvaluatorsClientUpdateVersionResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluatorVersion); err != nil {
		return EvaluatorsClientUpdateVersionResponse{}, err
	}
	return result, nil
}
