// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// EvaluationRulesClient contains the methods for the EvaluationRules group.
// Don't use this type directly, use [Client.NewEvaluationRulesClient] instead.
//
// Generated from API version v1
type EvaluationRulesClient struct {
	internal *azcore.Client
	endpoint string
}

// CreateOrUpdate - Create or update an evaluation rule
//
// Creates a new evaluation rule, or replaces the existing rule when the identifier matches.
// If the operation fails it returns an *azcore.ResponseError type.
//   - id - Unique identifier for the evaluation rule.
//   - evaluationRule - Evaluation rule resource
//   - options - EvaluationRulesClientCreateOrUpdateOptions contains the optional parameters for the EvaluationRulesClient.CreateOrUpdate
//     method.
func (client *EvaluationRulesClient) CreateOrUpdate(ctx context.Context, id string, evaluationRule EvaluationRule, options *EvaluationRulesClientCreateOrUpdateOptions) (EvaluationRulesClientCreateOrUpdateResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluationRulesClient.CreateOrUpdate", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createOrUpdateCreateRequest(ctx, id, evaluationRule, options)
	if err != nil {
		return EvaluationRulesClientCreateOrUpdateResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluationRulesClientCreateOrUpdateResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK, http.StatusCreated) {
		err = runtime.NewResponseError(httpResp)
		return EvaluationRulesClientCreateOrUpdateResponse{}, err
	}
	resp, err := client.createOrUpdateHandleResponse(httpResp)
	return resp, err
}

// createOrUpdateCreateRequest creates the CreateOrUpdate request.
func (client *EvaluationRulesClient) createOrUpdateCreateRequest(ctx context.Context, id string, evaluationRule EvaluationRule, options *EvaluationRulesClientCreateOrUpdateOptions) (*policy.Request, error) {
	urlPath := "/evaluationrules/{id}"
	if id == "" {
		return nil, errors.New("parameter id cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{id}", url.PathEscape(id))
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Evaluations=V1Preview"}
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, evaluationRule); err != nil {
		return nil, err
	}
	return req, nil
}

// createOrUpdateHandleResponse handles the CreateOrUpdate response.
func (client *EvaluationRulesClient) createOrUpdateHandleResponse(resp *http.Response) (EvaluationRulesClientCreateOrUpdateResponse, error) {
	result := EvaluationRulesClientCreateOrUpdateResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluationRule); err != nil {
		return EvaluationRulesClientCreateOrUpdateResponse{}, err
	}
	return result, nil
}

// Delete - Delete an evaluation rule
//
// Removes the specified evaluation rule from the project.
// If the operation fails it returns an *azcore.ResponseError type.
//   - id - Unique identifier for the evaluation rule.
//   - options - EvaluationRulesClientDeleteOptions contains the optional parameters for the EvaluationRulesClient.Delete method.
func (client *EvaluationRulesClient) Delete(ctx context.Context, id string, options *EvaluationRulesClientDeleteOptions) (EvaluationRulesClientDeleteResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluationRulesClient.Delete", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteCreateRequest(ctx, id, options)
	if err != nil {
		return EvaluationRulesClientDeleteResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluationRulesClientDeleteResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusNoContent) {
		err = runtime.NewResponseError(httpResp)
		return EvaluationRulesClientDeleteResponse{}, err
	}
	return EvaluationRulesClientDeleteResponse{}, nil
}

// deleteCreateRequest creates the Delete request.
func (client *EvaluationRulesClient) deleteCreateRequest(ctx context.Context, id string, _ *EvaluationRulesClientDeleteOptions) (*policy.Request, error) {
	urlPath := "/evaluationrules/{id}"
	if id == "" {
		return nil, errors.New("parameter id cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{id}", url.PathEscape(id))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	return req, nil
}

// Get - Get an evaluation rule
//
// Retrieves the specified evaluation rule and its configuration.
// If the operation fails it returns an *azcore.ResponseError type.
//   - id - Unique identifier for the evaluation rule.
//   - options - EvaluationRulesClientGetOptions contains the optional parameters for the EvaluationRulesClient.Get method.
func (client *EvaluationRulesClient) Get(ctx context.Context, id string, options *EvaluationRulesClientGetOptions) (EvaluationRulesClientGetResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "EvaluationRulesClient.Get", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, id, options)
	if err != nil {
		return EvaluationRulesClientGetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return EvaluationRulesClientGetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return EvaluationRulesClientGetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the Get request.
func (client *EvaluationRulesClient) getCreateRequest(ctx context.Context, id string, _ *EvaluationRulesClientGetOptions) (*policy.Request, error) {
	urlPath := "/evaluationrules/{id}"
	if id == "" {
		return nil, errors.New("parameter id cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{id}", url.PathEscape(id))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *EvaluationRulesClient) getHandleResponse(resp *http.Response) (EvaluationRulesClientGetResponse, error) {
	result := EvaluationRulesClientGetResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.EvaluationRule); err != nil {
		return EvaluationRulesClientGetResponse{}, err
	}
	return result, nil
}

// NewListPager - List evaluation rules
//
// Returns the evaluation rules configured for the project, optionally filtered by action type, agent name, or enabled state.
//   - options - EvaluationRulesClientListOptions contains the optional parameters for the EvaluationRulesClient.NewListPager
//     method.
func (client *EvaluationRulesClient) NewListPager(options *EvaluationRulesClientListOptions) *runtime.Pager[EvaluationRulesClientListResponse] {
	return runtime.NewPager(runtime.PagingHandler[EvaluationRulesClientListResponse]{
		More: func(page EvaluationRulesClientListResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *EvaluationRulesClientListResponse) (EvaluationRulesClientListResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listCreateRequest(ctx, options)
			}, nil)
			if err != nil {
				return EvaluationRulesClientListResponse{}, err
			}
			return client.listHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listCreateRequest creates the List request.
func (client *EvaluationRulesClient) listCreateRequest(ctx context.Context, options *EvaluationRulesClientListOptions) (*policy.Request, error) {
	urlPath := "/evaluationrules"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.ActionType != nil {
		reqQP.Set("actionType", string(*options.ActionType))
	}
	if options != nil && options.AgentName != nil {
		reqQP.Set("agentName", *options.AgentName)
	}
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Enabled != nil {
		reqQP.Set("enabled", strconv.FormatBool(*options.Enabled))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// listHandleResponse handles the List response.
func (client *EvaluationRulesClient) listHandleResponse(resp *http.Response) (EvaluationRulesClientListResponse, error) {
	result := EvaluationRulesClientListResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedEvaluationRule); err != nil {
		return EvaluationRulesClientListResponse{}, err
	}
	return result, nil
}
