// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/datetime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// InsightsClient contains the methods for the Insights group.
// Don't use this type directly, use [Client.NewInsightsClient] instead.
//
// Generated from API version v1
type InsightsClient struct {
	internal *azcore.Client
	endpoint string
}

// Generate - Generate insights
//
// Generates an insights report from the provided evaluation configuration.
// If the operation fails it returns an *azcore.ResponseError type.
//   - insight - Complete evaluation configuration including data source, evaluators, and result settings
//   - options - InsightsClientGenerateOptions contains the optional parameters for the InsightsClient.Generate method.
func (client *InsightsClient) Generate(ctx context.Context, insight Insight, options *InsightsClientGenerateOptions) (InsightsClientGenerateResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "InsightsClient.Generate", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.generateCreateRequest(ctx, insight, options)
	if err != nil {
		return InsightsClientGenerateResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return InsightsClientGenerateResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusCreated) {
		err = runtime.NewResponseError(httpResp)
		return InsightsClientGenerateResponse{}, err
	}
	resp, err := client.generateHandleResponse(httpResp)
	return resp, err
}

// generateCreateRequest creates the Generate request.
func (client *InsightsClient) generateCreateRequest(ctx context.Context, insight Insight, options *InsightsClientGenerateOptions) (*policy.Request, error) {
	urlPath := "/insights"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Insights=V1Preview"}
	}
	if options != nil && options.RepeatabilityFirstSent != nil {
		req.Raw().Header["Repeatability-First-Sent"] = []string{datetime.RFC1123(*options.RepeatabilityFirstSent).String()}
	}
	if options != nil && options.RepeatabilityRequestID != nil {
		req.Raw().Header["Repeatability-Request-ID"] = []string{*options.RepeatabilityRequestID}
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, insight); err != nil {
		return nil, err
	}
	return req, nil
}

// generateHandleResponse handles the Generate response.
func (client *InsightsClient) generateHandleResponse(resp *http.Response) (InsightsClientGenerateResponse, error) {
	result := InsightsClientGenerateResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.Insight); err != nil {
		return InsightsClientGenerateResponse{}, err
	}
	return result, nil
}

// Get - Get an insight
//
// Retrieves the specified insight report and its results.
// If the operation fails it returns an *azcore.ResponseError type.
//   - id - The unique identifier for the insights report.
//   - options - InsightsClientGetOptions contains the optional parameters for the InsightsClient.Get method.
func (client *InsightsClient) Get(ctx context.Context, id string, options *InsightsClientGetOptions) (InsightsClientGetResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "InsightsClient.Get", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, id, options)
	if err != nil {
		return InsightsClientGetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return InsightsClientGetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return InsightsClientGetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the Get request.
func (client *InsightsClient) getCreateRequest(ctx context.Context, id string, options *InsightsClientGetOptions) (*policy.Request, error) {
	urlPath := "/insights/{id}"
	if id == "" {
		return nil, errors.New("parameter id cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{id}", url.PathEscape(id))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	if options != nil && options.IncludeCoordinates != nil {
		reqQP.Set("includeCoordinates", strconv.FormatBool(*options.IncludeCoordinates))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Insights=V1Preview"}
	}
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *InsightsClient) getHandleResponse(resp *http.Response) (InsightsClientGetResponse, error) {
	result := InsightsClientGetResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.Insight); err != nil {
		return InsightsClientGetResponse{}, err
	}
	return result, nil
}

// NewListPager - List insights
//
// Returns insights in reverse chronological order, with the most recent entries first.
//   - options - InsightsClientListOptions contains the optional parameters for the InsightsClient.NewListPager method.
func (client *InsightsClient) NewListPager(options *InsightsClientListOptions) *runtime.Pager[InsightsClientListResponse] {
	return runtime.NewPager(runtime.PagingHandler[InsightsClientListResponse]{
		More: func(page InsightsClientListResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *InsightsClientListResponse) (InsightsClientListResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listCreateRequest(ctx, options)
			}, nil)
			if err != nil {
				return InsightsClientListResponse{}, err
			}
			return client.listHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listCreateRequest creates the List request.
func (client *InsightsClient) listCreateRequest(ctx context.Context, options *InsightsClientListOptions) (*policy.Request, error) {
	urlPath := "/insights"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.AgentName != nil {
		reqQP.Set("agentName", *options.AgentName)
	}
	reqQP.Set("api-version", versionV1)
	if options != nil && options.EvalID != nil {
		reqQP.Set("evalId", *options.EvalID)
	}
	if options != nil && options.IncludeCoordinates != nil {
		reqQP.Set("includeCoordinates", strconv.FormatBool(*options.IncludeCoordinates))
	}
	if options != nil && options.RunID != nil {
		reqQP.Set("runId", *options.RunID)
	}
	if options != nil && options.Type != nil {
		reqQP.Set("type", string(*options.Type))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	if options != nil && options.FoundryFeatures != nil {
		req.Raw().Header["Foundry-Features"] = []string{"Insights=V1Preview"}
	}
	return req, nil
}

// listHandleResponse handles the List response.
func (client *InsightsClient) listHandleResponse(resp *http.Response) (InsightsClientListResponse, error) {
	result := InsightsClientListResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedInsight); err != nil {
		return InsightsClientListResponse{}, err
	}
	return result, nil
}
