// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// IndexesClient contains the methods for the Indexes group.
// Don't use this type directly, use [Client.NewIndexesClient] instead.
//
// Generated from API version v1
type IndexesClient struct {
	internal *azcore.Client
	endpoint string
}

// CreateOrUpdateVersion - Create or update a version
//
// Create a new or update an existing Index with the given version id
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - indexParam - The Index to create or update.
//   - version - The specific version id of the Index to create or update.
//   - options - IndexesClientCreateOrUpdateVersionOptions contains the optional parameters for the IndexesClient.CreateOrUpdateVersion
//     method.
func (client *IndexesClient) CreateOrUpdateVersion(ctx context.Context, name string, indexParam IndexClassification, version string, options *IndexesClientCreateOrUpdateVersionOptions) (IndexesClientCreateOrUpdateVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "IndexesClient.CreateOrUpdateVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createOrUpdateVersionCreateRequest(ctx, name, indexParam, version, options)
	if err != nil {
		return IndexesClientCreateOrUpdateVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return IndexesClientCreateOrUpdateVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK, http.StatusCreated) {
		err = runtime.NewResponseError(httpResp)
		return IndexesClientCreateOrUpdateVersionResponse{}, err
	}
	resp, err := client.createOrUpdateVersionHandleResponse(httpResp)
	return resp, err
}

// createOrUpdateVersionCreateRequest creates the CreateOrUpdateVersion request.
func (client *IndexesClient) createOrUpdateVersionCreateRequest(ctx context.Context, name string, indexParam IndexClassification, version string, _ *IndexesClientCreateOrUpdateVersionOptions) (*policy.Request, error) {
	urlPath := "/indexes/{name}/versions/{version}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodPatch, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Content-Type"] = []string{"application/merge-patch+json"}
	if err := runtime.MarshalAsJSON(req, indexParam); err != nil {
		return nil, err
	}
	return req, nil
}

// createOrUpdateVersionHandleResponse handles the CreateOrUpdateVersion response.
func (client *IndexesClient) createOrUpdateVersionHandleResponse(resp *http.Response) (IndexesClientCreateOrUpdateVersionResponse, error) {
	result := IndexesClientCreateOrUpdateVersionResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result); err != nil {
		return IndexesClientCreateOrUpdateVersionResponse{}, err
	}
	return result, nil
}

// DeleteVersion - Delete a version
//
// Delete the specific version of the Index. The service returns 204 No Content if the Index was deleted successfully or if
// the Index does not exist.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - version - The version of the Index to delete.
//   - options - IndexesClientDeleteVersionOptions contains the optional parameters for the IndexesClient.DeleteVersion method.
func (client *IndexesClient) DeleteVersion(ctx context.Context, name string, version string, options *IndexesClientDeleteVersionOptions) (IndexesClientDeleteVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "IndexesClient.DeleteVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteVersionCreateRequest(ctx, name, version, options)
	if err != nil {
		return IndexesClientDeleteVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return IndexesClientDeleteVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusNoContent) {
		err = runtime.NewResponseError(httpResp)
		return IndexesClientDeleteVersionResponse{}, err
	}
	return IndexesClientDeleteVersionResponse{}, nil
}

// deleteVersionCreateRequest creates the DeleteVersion request.
func (client *IndexesClient) deleteVersionCreateRequest(ctx context.Context, name string, version string, _ *IndexesClientDeleteVersionOptions) (*policy.Request, error) {
	urlPath := "/indexes/{name}/versions/{version}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	return req, nil
}

// GetVersion - Get a version
//
// Get the specific version of the Index. The service returns 404 Not Found error if the Index does not exist.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the resource
//   - version - The specific version id of the Index to retrieve.
//   - options - IndexesClientGetVersionOptions contains the optional parameters for the IndexesClient.GetVersion method.
func (client *IndexesClient) GetVersion(ctx context.Context, name string, version string, options *IndexesClientGetVersionOptions) (IndexesClientGetVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "IndexesClient.GetVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getVersionCreateRequest(ctx, name, version, options)
	if err != nil {
		return IndexesClientGetVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return IndexesClientGetVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return IndexesClientGetVersionResponse{}, err
	}
	resp, err := client.getVersionHandleResponse(httpResp)
	return resp, err
}

// getVersionCreateRequest creates the GetVersion request.
func (client *IndexesClient) getVersionCreateRequest(ctx context.Context, name string, version string, _ *IndexesClientGetVersionOptions) (*policy.Request, error) {
	urlPath := "/indexes/{name}/versions/{version}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// getVersionHandleResponse handles the GetVersion response.
func (client *IndexesClient) getVersionHandleResponse(resp *http.Response) (IndexesClientGetVersionResponse, error) {
	result := IndexesClientGetVersionResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result); err != nil {
		return IndexesClientGetVersionResponse{}, err
	}
	return result, nil
}

// NewListLatestPager - List latest versions
//
// List the latest version of each Index
//   - options - IndexesClientListLatestOptions contains the optional parameters for the IndexesClient.NewListLatestPager method.
func (client *IndexesClient) NewListLatestPager(options *IndexesClientListLatestOptions) *runtime.Pager[IndexesClientListLatestResponse] {
	return runtime.NewPager(runtime.PagingHandler[IndexesClientListLatestResponse]{
		More: func(page IndexesClientListLatestResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *IndexesClientListLatestResponse) (IndexesClientListLatestResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listLatestCreateRequest(ctx, options)
			}, nil)
			if err != nil {
				return IndexesClientListLatestResponse{}, err
			}
			return client.listLatestHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listLatestCreateRequest creates the ListLatest request.
func (client *IndexesClient) listLatestCreateRequest(ctx context.Context, _ *IndexesClientListLatestOptions) (*policy.Request, error) {
	urlPath := "/indexes"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// listLatestHandleResponse handles the ListLatest response.
func (client *IndexesClient) listLatestHandleResponse(resp *http.Response) (IndexesClientListLatestResponse, error) {
	result := IndexesClientListLatestResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedIndex); err != nil {
		return IndexesClientListLatestResponse{}, err
	}
	return result, nil
}

// NewListVersionsPager - List versions
//
// List all versions of the given Index
//   - name - The name of the resource
//   - options - IndexesClientListVersionsOptions contains the optional parameters for the IndexesClient.NewListVersionsPager
//     method.
func (client *IndexesClient) NewListVersionsPager(name string, options *IndexesClientListVersionsOptions) *runtime.Pager[IndexesClientListVersionsResponse] {
	return runtime.NewPager(runtime.PagingHandler[IndexesClientListVersionsResponse]{
		More: func(page IndexesClientListVersionsResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *IndexesClientListVersionsResponse) (IndexesClientListVersionsResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listVersionsCreateRequest(ctx, name, options)
			}, nil)
			if err != nil {
				return IndexesClientListVersionsResponse{}, err
			}
			return client.listVersionsHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listVersionsCreateRequest creates the ListVersions request.
func (client *IndexesClient) listVersionsCreateRequest(ctx context.Context, name string, _ *IndexesClientListVersionsOptions) (*policy.Request, error) {
	urlPath := "/indexes/{name}/versions"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// listVersionsHandleResponse handles the ListVersions response.
func (client *IndexesClient) listVersionsHandleResponse(resp *http.Response) (IndexesClientListVersionsResponse, error) {
	result := IndexesClientListVersionsResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedIndex); err != nil {
		return IndexesClientListVersionsResponse{}, err
	}
	return result, nil
}
