// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

// BaseCredentialsClassification provides polymorphic access to related types.
// Call the interface's GetBaseCredentials() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *APIKeyCredentials, *AgenticIdentityPreviewCredentials, *BaseCredentials, *CustomCredential, *EntraIDCredentials, *NoAuthenticationCredentials,
// - *SASCredentials
type BaseCredentialsClassification interface {
	// GetBaseCredentials returns the BaseCredentials content of the underlying type.
	GetBaseCredentials() *BaseCredentials
}

// ContainerNetworkPolicyParamClassification provides polymorphic access to related types.
// Call the interface's GetContainerNetworkPolicyParam() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ContainerNetworkPolicyAllowlistParam, *ContainerNetworkPolicyDisabledParam, *ContainerNetworkPolicyParam
type ContainerNetworkPolicyParamClassification interface {
	// GetContainerNetworkPolicyParam returns the ContainerNetworkPolicyParam content of the underlying type.
	GetContainerNetworkPolicyParam() *ContainerNetworkPolicyParam
}

// ContainerSkillClassification provides polymorphic access to related types.
// Call the interface's GetContainerSkill() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ContainerSkill, *InlineSkillParam, *SkillReferenceParam
type ContainerSkillClassification interface {
	// GetContainerSkill returns the ContainerSkill content of the underlying type.
	GetContainerSkill() *ContainerSkill
}

// CustomToolParamFormatClassification provides polymorphic access to related types.
// Call the interface's GetCustomToolParamFormat() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *CustomGrammarFormatParam, *CustomTextFormatParam, *CustomToolParamFormat
type CustomToolParamFormatClassification interface {
	// GetCustomToolParamFormat returns the CustomToolParamFormat content of the underlying type.
	GetCustomToolParamFormat() *CustomToolParamFormat
}

// DatasetVersionClassification provides polymorphic access to related types.
// Call the interface's GetDatasetVersion() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *DatasetVersion, *FileDatasetVersion, *FolderDatasetVersion
type DatasetVersionClassification interface {
	// GetDatasetVersion returns the DatasetVersion content of the underlying type.
	GetDatasetVersion() *DatasetVersion
}

// DeploymentClassification provides polymorphic access to related types.
// Call the interface's GetDeployment() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *Deployment, *ModelDeployment
type DeploymentClassification interface {
	// GetDeployment returns the Deployment content of the underlying type.
	GetDeployment() *Deployment
}

// EvaluationRuleActionClassification provides polymorphic access to related types.
// Call the interface's GetEvaluationRuleAction() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ContinuousEvaluationRuleAction, *EvaluationRuleAction, *HumanEvaluationPreviewRuleAction
type EvaluationRuleActionClassification interface {
	// GetEvaluationRuleAction returns the EvaluationRuleAction content of the underlying type.
	GetEvaluationRuleAction() *EvaluationRuleAction
}

// EvaluationTaxonomyInputClassification provides polymorphic access to related types.
// Call the interface's GetEvaluationTaxonomyInput() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AgentTaxonomyInput, *EvaluationTaxonomyInput
type EvaluationTaxonomyInputClassification interface {
	// GetEvaluationTaxonomyInput returns the EvaluationTaxonomyInput content of the underlying type.
	GetEvaluationTaxonomyInput() *EvaluationTaxonomyInput
}

// EvaluatorDefinitionClassification provides polymorphic access to related types.
// Call the interface's GetEvaluatorDefinition() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *CodeBasedEvaluatorDefinition, *EvaluatorDefinition, *PromptBasedEvaluatorDefinition, *RubricBasedEvaluatorDefinition
type EvaluatorDefinitionClassification interface {
	// GetEvaluatorDefinition returns the EvaluatorDefinition content of the underlying type.
	GetEvaluatorDefinition() *EvaluatorDefinition
}

// EvaluatorGenerationJobSourceClassification provides polymorphic access to related types.
// Call the interface's GetEvaluatorGenerationJobSource() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AgentEvaluatorGenerationJobSource, *DatasetEvaluatorGenerationJobSource, *EvaluatorGenerationJobSource, *PromptEvaluatorGenerationJobSource,
// - *TracesEvaluatorGenerationJobSource
type EvaluatorGenerationJobSourceClassification interface {
	// GetEvaluatorGenerationJobSource returns the EvaluatorGenerationJobSource content of the underlying type.
	GetEvaluatorGenerationJobSource() *EvaluatorGenerationJobSource
}

// FunctionShellToolParamEnvironmentClassification provides polymorphic access to related types.
// Call the interface's GetFunctionShellToolParamEnvironment() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ContainerAutoParam, *FunctionShellToolParamEnvironment, *FunctionShellToolParamEnvironmentContainerReferenceParam, *FunctionShellToolParamEnvironmentLocalEnvironmentParam
type FunctionShellToolParamEnvironmentClassification interface {
	// GetFunctionShellToolParamEnvironment returns the FunctionShellToolParamEnvironment content of the underlying type.
	GetFunctionShellToolParamEnvironment() *FunctionShellToolParamEnvironment
}

// IndexClassification provides polymorphic access to related types.
// Call the interface's GetIndex() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AzureAISearchIndex, *CosmosDBIndex, *Index, *ManagedAzureAISearchIndex
type IndexClassification interface {
	// GetIndex returns the Index content of the underlying type.
	GetIndex() *Index
}

// InsightRequestClassification provides polymorphic access to related types.
// Call the interface's GetInsightRequest() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AgentClusterInsightRequest, *EvaluationComparisonInsightRequest, *EvaluationRunClusterInsightRequest, *InsightRequest
type InsightRequestClassification interface {
	// GetInsightRequest returns the InsightRequest content of the underlying type.
	GetInsightRequest() *InsightRequest
}

// InsightResultClassification provides polymorphic access to related types.
// Call the interface's GetInsightResult() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AgentClusterInsightResult, *EvaluationComparisonInsightResult, *EvaluationRunClusterInsightResult, *InsightResult
type InsightResultClassification interface {
	// GetInsightResult returns the InsightResult content of the underlying type.
	GetInsightResult() *InsightResult
}

// InsightSampleClassification provides polymorphic access to related types.
// Call the interface's GetInsightSample() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *EvaluationResultSample, *InsightSample
type InsightSampleClassification interface {
	// GetInsightSample returns the InsightSample content of the underlying type.
	GetInsightSample() *InsightSample
}

// MemoryItemClassification provides polymorphic access to related types.
// Call the interface's GetMemoryItem() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ChatSummaryMemoryItem, *MemoryItem, *ProceduralMemoryItem, *UserProfileMemoryItem
type MemoryItemClassification interface {
	// GetMemoryItem returns the MemoryItem content of the underlying type.
	GetMemoryItem() *MemoryItem
}

// MemoryStoreDefinitionClassification provides polymorphic access to related types.
// Call the interface's GetMemoryStoreDefinition() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *MemoryStoreDefaultDefinition, *MemoryStoreDefinition
type MemoryStoreDefinitionClassification interface {
	// GetMemoryStoreDefinition returns the MemoryStoreDefinition content of the underlying type.
	GetMemoryStoreDefinition() *MemoryStoreDefinition
}

// OpenAPIAuthDetailsClassification provides polymorphic access to related types.
// Call the interface's GetOpenAPIAuthDetails() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *OpenAPIAnonymousAuthDetails, *OpenAPIAuthDetails, *OpenAPIManagedAuthDetails, *OpenAPIProjectConnectionAuthDetails
type OpenAPIAuthDetailsClassification interface {
	// GetOpenAPIAuthDetails returns the OpenAPIAuthDetails content of the underlying type.
	GetOpenAPIAuthDetails() *OpenAPIAuthDetails
}

// RecurrenceScheduleClassification provides polymorphic access to related types.
// Call the interface's GetRecurrenceSchedule() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *DailyRecurrenceSchedule, *HourlyRecurrenceSchedule, *MonthlyRecurrenceSchedule, *RecurrenceSchedule, *WeeklyRecurrenceSchedule
type RecurrenceScheduleClassification interface {
	// GetRecurrenceSchedule returns the RecurrenceSchedule content of the underlying type.
	GetRecurrenceSchedule() *RecurrenceSchedule
}

// RedTeamTargetConfigClassification provides polymorphic access to related types.
// Call the interface's GetRedTeamTargetConfig() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AzureOpenAIModelConfiguration, *RedTeamTargetConfig
type RedTeamTargetConfigClassification interface {
	// GetRedTeamTargetConfig returns the RedTeamTargetConfig content of the underlying type.
	GetRedTeamTargetConfig() *RedTeamTargetConfig
}

// ScheduleTaskClassification provides polymorphic access to related types.
// Call the interface's GetScheduleTask() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *EvaluationScheduleTask, *InsightScheduleTask, *ScheduleTask
type ScheduleTaskClassification interface {
	// GetScheduleTask returns the ScheduleTask content of the underlying type.
	GetScheduleTask() *ScheduleTask
}

// TargetClassification provides polymorphic access to related types.
// Call the interface's GetTarget() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AzureAIAgentTarget, *AzureAIModelTarget, *Target
type TargetClassification interface {
	// GetTarget returns the Target content of the underlying type.
	GetTarget() *Target
}

// ToolClassification provides polymorphic access to related types.
// Call the interface's GetTool() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *A2APreviewTool, *ApplyPatchToolParam, *AzureAISearchTool, *AzureFunctionTool, *BingCustomSearchPreviewTool, *BingGroundingTool,
// - *BrowserAutomationPreviewTool, *CaptureStructuredOutputsTool, *CodeInterpreterTool, *ComputerTool, *ComputerUsePreviewTool,
// - *CustomToolParam, *FabricIQPreviewTool, *FileSearchTool, *FunctionShellToolParam, *FunctionTool, *ImageGenTool, *LocalShellToolParam,
// - *MCPTool, *MemorySearchPreviewTool, *MicrosoftFabricPreviewTool, *NamespaceToolParam, *OpenAPITool, *ReminderPreviewTool,
// - *SharepointPreviewTool, *Tool, *ToolSearchToolParam, *WebSearchPreviewTool, *WebSearchTool, *WorkIQPreviewTool
type ToolClassification interface {
	// GetTool returns the Tool content of the underlying type.
	GetTool() *Tool
}

// ToolboxSkillClassification provides polymorphic access to related types.
// Call the interface's GetToolboxSkill() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ToolboxSkill, *ToolboxSkillReference
type ToolboxSkillClassification interface {
	// GetToolboxSkill returns the ToolboxSkill content of the underlying type.
	GetToolboxSkill() *ToolboxSkill
}

// ToolboxToolClassification provides polymorphic access to related types.
// Call the interface's GetToolboxTool() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *A2APreviewToolboxTool, *AzureAISearchToolboxTool, *BrowserAutomationPreviewToolboxTool, *CodeInterpreterToolboxTool,
// - *FabricIQPreviewToolboxTool, *FileSearchToolboxTool, *MCPToolboxTool, *OpenAPIToolboxTool, *ReminderPreviewToolboxTool,
// - *ToolboxSearchPreviewToolboxTool, *ToolboxTool, *WebSearchToolboxTool, *WorkIQPreviewToolboxTool
type ToolboxToolClassification interface {
	// GetToolboxTool returns the ToolboxTool content of the underlying type.
	GetToolboxTool() *ToolboxTool
}

// TriggerClassification provides polymorphic access to related types.
// Call the interface's GetTrigger() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *CronTrigger, *OneTimeTrigger, *RecurrenceTrigger, *Trigger
type TriggerClassification interface {
	// GetTrigger returns the Trigger content of the underlying type.
	GetTrigger() *Trigger
}
