// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// MemoryStoresClient contains the methods for the MemoryStores group.
// Don't use this type directly, use [Client.NewMemoryStoresClient] instead.
//
// Generated from API version v1
type MemoryStoresClient struct {
	internal *azcore.Client
	endpoint string
}

// CreateMemory - Create a memory item
//
// Creates a memory item in the specified memory store.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store.
//   - scope - The namespace that logically groups and isolates memories, such as a user ID.
//   - content - The content of the memory.
//   - kind - The kind of the memory item.
//   - options - MemoryStoresClientCreateMemoryOptions contains the optional parameters for the MemoryStoresClient.CreateMemory
//     method.
func (client *MemoryStoresClient) CreateMemory(ctx context.Context, name string, scope string, content string, kind MemoryItemKind, options *MemoryStoresClientCreateMemoryOptions) (MemoryStoresClientCreateMemoryResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.CreateMemory", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createMemoryCreateRequest(ctx, name, scope, content, kind, options)
	if err != nil {
		return MemoryStoresClientCreateMemoryResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientCreateMemoryResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientCreateMemoryResponse{}, err
	}
	resp, err := client.createMemoryHandleResponse(httpResp)
	return resp, err
}

// createMemoryCreateRequest creates the CreateMemory request.
func (client *MemoryStoresClient) createMemoryCreateRequest(ctx context.Context, name string, scope string, content string, kind MemoryItemKind, _ *MemoryStoresClientCreateMemoryOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}/items"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	body := struct {
		Scope   string         `json:"scope"`
		Content string         `json:"content"`
		Kind    MemoryItemKind `json:"kind"`
	}{
		Scope:   scope,
		Content: content,
		Kind:    kind,
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// createMemoryHandleResponse handles the CreateMemory response.
func (client *MemoryStoresClient) createMemoryHandleResponse(resp *http.Response) (MemoryStoresClientCreateMemoryResponse, error) {
	result := MemoryStoresClientCreateMemoryResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result); err != nil {
		return MemoryStoresClientCreateMemoryResponse{}, err
	}
	return result, nil
}

// CreateMemoryStore - Create a memory store
//
// Creates a memory store resource with the provided configuration.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store.
//   - definition - The memory store definition.
//   - options - MemoryStoresClientCreateMemoryStoreOptions contains the optional parameters for the MemoryStoresClient.CreateMemoryStore
//     method.
func (client *MemoryStoresClient) CreateMemoryStore(ctx context.Context, name string, definition MemoryStoreDefinitionClassification, options *MemoryStoresClientCreateMemoryStoreOptions) (MemoryStoresClientCreateMemoryStoreResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.CreateMemoryStore", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createMemoryStoreCreateRequest(ctx, name, definition, options)
	if err != nil {
		return MemoryStoresClientCreateMemoryStoreResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientCreateMemoryStoreResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientCreateMemoryStoreResponse{}, err
	}
	resp, err := client.createMemoryStoreHandleResponse(httpResp)
	return resp, err
}

// createMemoryStoreCreateRequest creates the CreateMemoryStore request.
func (client *MemoryStoresClient) createMemoryStoreCreateRequest(ctx context.Context, name string, definition MemoryStoreDefinitionClassification, options *MemoryStoresClientCreateMemoryStoreOptions) (*policy.Request, error) {
	urlPath := "/memory_stores"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	body := struct {
		Name        string                              `json:"name"`
		Description *string                             `json:"description"`
		Metadata    map[string]*string                  `json:"metadata"`
		Definition  MemoryStoreDefinitionClassification `json:"definition"`
	}{
		Name:       name,
		Definition: definition,
	}
	if options != nil && options.Description != nil {
		body.Description = options.Description
	}
	if options != nil && options.Metadata != nil {
		body.Metadata = options.Metadata
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// createMemoryStoreHandleResponse handles the CreateMemoryStore response.
func (client *MemoryStoresClient) createMemoryStoreHandleResponse(resp *http.Response) (MemoryStoresClientCreateMemoryStoreResponse, error) {
	result := MemoryStoresClientCreateMemoryStoreResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.MemoryStoreObject); err != nil {
		return MemoryStoresClientCreateMemoryStoreResponse{}, err
	}
	return result, nil
}

// DeleteMemory - Delete a memory item
//
// Deletes the specified memory item from the memory store.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store.
//   - memoryID - The ID of the memory item to delete.
//   - options - MemoryStoresClientDeleteMemoryOptions contains the optional parameters for the MemoryStoresClient.DeleteMemory
//     method.
func (client *MemoryStoresClient) DeleteMemory(ctx context.Context, name string, memoryID string, options *MemoryStoresClientDeleteMemoryOptions) (MemoryStoresClientDeleteMemoryResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.DeleteMemory", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteMemoryCreateRequest(ctx, name, memoryID, options)
	if err != nil {
		return MemoryStoresClientDeleteMemoryResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientDeleteMemoryResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientDeleteMemoryResponse{}, err
	}
	resp, err := client.deleteMemoryHandleResponse(httpResp)
	return resp, err
}

// deleteMemoryCreateRequest creates the DeleteMemory request.
func (client *MemoryStoresClient) deleteMemoryCreateRequest(ctx context.Context, name string, memoryID string, _ *MemoryStoresClientDeleteMemoryOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}/items/{memory_id}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if memoryID == "" {
		return nil, errors.New("parameter memoryID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{memory_id}", url.PathEscape(memoryID))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	return req, nil
}

// deleteMemoryHandleResponse handles the DeleteMemory response.
func (client *MemoryStoresClient) deleteMemoryHandleResponse(resp *http.Response) (MemoryStoresClientDeleteMemoryResponse, error) {
	result := MemoryStoresClientDeleteMemoryResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.DeleteMemoryResponse); err != nil {
		return MemoryStoresClientDeleteMemoryResponse{}, err
	}
	return result, nil
}

// DeleteMemoryStore - Delete a memory store
//
// Deletes the specified memory store.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store to delete.
//   - options - MemoryStoresClientDeleteMemoryStoreOptions contains the optional parameters for the MemoryStoresClient.DeleteMemoryStore
//     method.
func (client *MemoryStoresClient) DeleteMemoryStore(ctx context.Context, name string, options *MemoryStoresClientDeleteMemoryStoreOptions) (MemoryStoresClientDeleteMemoryStoreResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.DeleteMemoryStore", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteMemoryStoreCreateRequest(ctx, name, options)
	if err != nil {
		return MemoryStoresClientDeleteMemoryStoreResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientDeleteMemoryStoreResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientDeleteMemoryStoreResponse{}, err
	}
	resp, err := client.deleteMemoryStoreHandleResponse(httpResp)
	return resp, err
}

// deleteMemoryStoreCreateRequest creates the DeleteMemoryStore request.
func (client *MemoryStoresClient) deleteMemoryStoreCreateRequest(ctx context.Context, name string, _ *MemoryStoresClientDeleteMemoryStoreOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	return req, nil
}

// deleteMemoryStoreHandleResponse handles the DeleteMemoryStore response.
func (client *MemoryStoresClient) deleteMemoryStoreHandleResponse(resp *http.Response) (MemoryStoresClientDeleteMemoryStoreResponse, error) {
	result := MemoryStoresClientDeleteMemoryStoreResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.DeleteMemoryStoreResult); err != nil {
		return MemoryStoresClientDeleteMemoryStoreResponse{}, err
	}
	return result, nil
}

// DeleteScope - Delete memories by scope
//
// Deletes all memories in the specified memory store that are associated with the provided scope.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store.
//   - scope - The namespace that logically groups and isolates memories to delete, such as a user ID.
//   - options - MemoryStoresClientDeleteScopeOptions contains the optional parameters for the MemoryStoresClient.DeleteScope
//     method.
func (client *MemoryStoresClient) DeleteScope(ctx context.Context, name string, scope string, options *MemoryStoresClientDeleteScopeOptions) (MemoryStoresClientDeleteScopeResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.DeleteScope", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteScopeCreateRequest(ctx, name, scope, options)
	if err != nil {
		return MemoryStoresClientDeleteScopeResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientDeleteScopeResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientDeleteScopeResponse{}, err
	}
	resp, err := client.deleteScopeHandleResponse(httpResp)
	return resp, err
}

// deleteScopeCreateRequest creates the DeleteScope request.
func (client *MemoryStoresClient) deleteScopeCreateRequest(ctx context.Context, name string, scope string, _ *MemoryStoresClientDeleteScopeOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}:delete_scope"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	body := struct {
		Scope string `json:"scope"`
	}{
		Scope: scope,
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// deleteScopeHandleResponse handles the DeleteScope response.
func (client *MemoryStoresClient) deleteScopeHandleResponse(resp *http.Response) (MemoryStoresClientDeleteScopeResponse, error) {
	result := MemoryStoresClientDeleteScopeResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.MemoryStoreDeleteScopeResult); err != nil {
		return MemoryStoresClientDeleteScopeResponse{}, err
	}
	return result, nil
}

// GetMemory - Get a memory item
//
// Retrieves the specified memory item from the memory store.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store.
//   - memoryID - The ID of the memory item to retrieve.
//   - options - MemoryStoresClientGetMemoryOptions contains the optional parameters for the MemoryStoresClient.GetMemory method.
func (client *MemoryStoresClient) GetMemory(ctx context.Context, name string, memoryID string, options *MemoryStoresClientGetMemoryOptions) (MemoryStoresClientGetMemoryResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.GetMemory", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getMemoryCreateRequest(ctx, name, memoryID, options)
	if err != nil {
		return MemoryStoresClientGetMemoryResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientGetMemoryResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientGetMemoryResponse{}, err
	}
	resp, err := client.getMemoryHandleResponse(httpResp)
	return resp, err
}

// getMemoryCreateRequest creates the GetMemory request.
func (client *MemoryStoresClient) getMemoryCreateRequest(ctx context.Context, name string, memoryID string, _ *MemoryStoresClientGetMemoryOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}/items/{memory_id}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if memoryID == "" {
		return nil, errors.New("parameter memoryID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{memory_id}", url.PathEscape(memoryID))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	return req, nil
}

// getMemoryHandleResponse handles the GetMemory response.
func (client *MemoryStoresClient) getMemoryHandleResponse(resp *http.Response) (MemoryStoresClientGetMemoryResponse, error) {
	result := MemoryStoresClientGetMemoryResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result); err != nil {
		return MemoryStoresClientGetMemoryResponse{}, err
	}
	return result, nil
}

// GetMemoryStore - Get a memory store
//
// Retrieves the specified memory store and its current configuration.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store to retrieve.
//   - options - MemoryStoresClientGetMemoryStoreOptions contains the optional parameters for the MemoryStoresClient.GetMemoryStore
//     method.
func (client *MemoryStoresClient) GetMemoryStore(ctx context.Context, name string, options *MemoryStoresClientGetMemoryStoreOptions) (MemoryStoresClientGetMemoryStoreResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.GetMemoryStore", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getMemoryStoreCreateRequest(ctx, name, options)
	if err != nil {
		return MemoryStoresClientGetMemoryStoreResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientGetMemoryStoreResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientGetMemoryStoreResponse{}, err
	}
	resp, err := client.getMemoryStoreHandleResponse(httpResp)
	return resp, err
}

// getMemoryStoreCreateRequest creates the GetMemoryStore request.
func (client *MemoryStoresClient) getMemoryStoreCreateRequest(ctx context.Context, name string, _ *MemoryStoresClientGetMemoryStoreOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	return req, nil
}

// getMemoryStoreHandleResponse handles the GetMemoryStore response.
func (client *MemoryStoresClient) getMemoryStoreHandleResponse(resp *http.Response) (MemoryStoresClientGetMemoryStoreResponse, error) {
	result := MemoryStoresClientGetMemoryStoreResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.MemoryStoreObject); err != nil {
		return MemoryStoresClientGetMemoryStoreResponse{}, err
	}
	return result, nil
}

// GetUpdateResult - Get an update result
//
// Retrieves the status and result of a memory store update operation.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store.
//   - updateID - The ID of the memory update operation.
//   - options - MemoryStoresClientGetUpdateResultOptions contains the optional parameters for the MemoryStoresClient.GetUpdateResult
//     method.
func (client *MemoryStoresClient) GetUpdateResult(ctx context.Context, name string, updateID string, options *MemoryStoresClientGetUpdateResultOptions) (MemoryStoresClientGetUpdateResultResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.GetUpdateResult", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getUpdateResultCreateRequest(ctx, name, updateID, options)
	if err != nil {
		return MemoryStoresClientGetUpdateResultResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientGetUpdateResultResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientGetUpdateResultResponse{}, err
	}
	resp, err := client.getUpdateResultHandleResponse(httpResp)
	return resp, err
}

// getUpdateResultCreateRequest creates the GetUpdateResult request.
func (client *MemoryStoresClient) getUpdateResultCreateRequest(ctx context.Context, name string, updateID string, _ *MemoryStoresClientGetUpdateResultOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}/updates/{update_id}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if updateID == "" {
		return nil, errors.New("parameter updateID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{update_id}", url.PathEscape(updateID))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	return req, nil
}

// getUpdateResultHandleResponse handles the GetUpdateResult response.
func (client *MemoryStoresClient) getUpdateResultHandleResponse(resp *http.Response) (MemoryStoresClientGetUpdateResultResponse, error) {
	result := MemoryStoresClientGetUpdateResultResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.MemoryStoreUpdateResult); err != nil {
		return MemoryStoresClientGetUpdateResultResponse{}, err
	}
	return result, nil
}

// NewListMemoriesPager - List memory items
//
// Returns memory items from the specified memory store.
//   - name - The name of the memory store.
//   - scope - The namespace that logically groups and isolates memories, such as a user ID.
//   - options - MemoryStoresClientListMemoriesOptions contains the optional parameters for the MemoryStoresClient.NewListMemoriesPager
//     method.
func (client *MemoryStoresClient) NewListMemoriesPager(name string, scope string, options *MemoryStoresClientListMemoriesOptions) *runtime.Pager[MemoryStoresClientListMemoriesResponse] {
	return runtime.NewPager(runtime.PagingHandler[MemoryStoresClientListMemoriesResponse]{
		More: func(page MemoryStoresClientListMemoriesResponse) bool {
			return page.LastID != nil && len(*page.LastID) > 0
		},
		Fetcher: func(ctx context.Context, page *MemoryStoresClientListMemoriesResponse) (MemoryStoresClientListMemoriesResponse, error) {
			nextOpts := MemoryStoresClientListMemoriesOptions{}
			if options != nil {
				nextOpts = *options
			}
			if page != nil {
				nextOpts.After = page.LastID
			}
			req, err := client.listMemoriesCreateRequest(ctx, name, scope, &nextOpts)
			if err != nil {
				return MemoryStoresClientListMemoriesResponse{}, err
			}
			resp, err := client.internal.Pipeline().Do(req)
			if err != nil {
				return MemoryStoresClientListMemoriesResponse{}, err
			}
			if !runtime.HasStatusCode(resp, http.StatusOK) {
				return MemoryStoresClientListMemoriesResponse{}, runtime.NewResponseError(resp)
			}
			return client.listMemoriesHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listMemoriesCreateRequest creates the ListMemories request.
func (client *MemoryStoresClient) listMemoriesCreateRequest(ctx context.Context, name string, scope string, options *MemoryStoresClientListMemoriesOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}/items:list"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.After != nil {
		reqQP.Set("after", *options.After)
	}
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Before != nil {
		reqQP.Set("before", *options.Before)
	}
	if options != nil && options.Kind != nil {
		reqQP.Set("kind", string(*options.Kind))
	}
	if options != nil && options.Limit != nil {
		reqQP.Set("limit", strconv.FormatInt(int64(*options.Limit), 10))
	}
	if options != nil && options.Order != nil {
		reqQP.Set("order", string(*options.Order))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	body := struct {
		Scope string `json:"scope"`
	}{
		Scope: scope,
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// listMemoriesHandleResponse handles the ListMemories response.
func (client *MemoryStoresClient) listMemoriesHandleResponse(resp *http.Response) (MemoryStoresClientListMemoriesResponse, error) {
	result := MemoryStoresClientListMemoriesResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.AgentsPagedResultMemoryItem); err != nil {
		return MemoryStoresClientListMemoriesResponse{}, err
	}
	return result, nil
}

// NewListMemoryStoresPager - List memory stores
//
// Returns the memory stores available to the caller.
//   - options - MemoryStoresClientListMemoryStoresOptions contains the optional parameters for the MemoryStoresClient.NewListMemoryStoresPager
//     method.
func (client *MemoryStoresClient) NewListMemoryStoresPager(options *MemoryStoresClientListMemoryStoresOptions) *runtime.Pager[MemoryStoresClientListMemoryStoresResponse] {
	return runtime.NewPager(runtime.PagingHandler[MemoryStoresClientListMemoryStoresResponse]{
		More: func(page MemoryStoresClientListMemoryStoresResponse) bool {
			return page.LastID != nil && len(*page.LastID) > 0
		},
		Fetcher: func(ctx context.Context, page *MemoryStoresClientListMemoryStoresResponse) (MemoryStoresClientListMemoryStoresResponse, error) {
			nextOpts := MemoryStoresClientListMemoryStoresOptions{}
			if options != nil {
				nextOpts = *options
			}
			if page != nil {
				nextOpts.After = page.LastID
			}
			req, err := client.listMemoryStoresCreateRequest(ctx, &nextOpts)
			if err != nil {
				return MemoryStoresClientListMemoryStoresResponse{}, err
			}
			resp, err := client.internal.Pipeline().Do(req)
			if err != nil {
				return MemoryStoresClientListMemoryStoresResponse{}, err
			}
			if !runtime.HasStatusCode(resp, http.StatusOK) {
				return MemoryStoresClientListMemoryStoresResponse{}, runtime.NewResponseError(resp)
			}
			return client.listMemoryStoresHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listMemoryStoresCreateRequest creates the ListMemoryStores request.
func (client *MemoryStoresClient) listMemoryStoresCreateRequest(ctx context.Context, options *MemoryStoresClientListMemoryStoresOptions) (*policy.Request, error) {
	urlPath := "/memory_stores"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.After != nil {
		reqQP.Set("after", *options.After)
	}
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Before != nil {
		reqQP.Set("before", *options.Before)
	}
	if options != nil && options.Limit != nil {
		reqQP.Set("limit", strconv.FormatInt(int64(*options.Limit), 10))
	}
	if options != nil && options.Order != nil {
		reqQP.Set("order", string(*options.Order))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	return req, nil
}

// listMemoryStoresHandleResponse handles the ListMemoryStores response.
func (client *MemoryStoresClient) listMemoryStoresHandleResponse(resp *http.Response) (MemoryStoresClientListMemoryStoresResponse, error) {
	result := MemoryStoresClientListMemoryStoresResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.AgentsPagedResultMemoryStoreObject); err != nil {
		return MemoryStoresClientListMemoryStoresResponse{}, err
	}
	return result, nil
}

// SearchMemories - Search memories
//
// Searches the specified memory store for memories relevant to the provided conversation context.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store to search.
//   - scope - The namespace that logically groups and isolates memories, such as a user ID.
//   - options - MemoryStoresClientSearchMemoriesOptions contains the optional parameters for the MemoryStoresClient.SearchMemories
//     method.
func (client *MemoryStoresClient) SearchMemories(ctx context.Context, name string, scope string, options *MemoryStoresClientSearchMemoriesOptions) (MemoryStoresClientSearchMemoriesResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.SearchMemories", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.searchMemoriesCreateRequest(ctx, name, scope, options)
	if err != nil {
		return MemoryStoresClientSearchMemoriesResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientSearchMemoriesResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientSearchMemoriesResponse{}, err
	}
	resp, err := client.searchMemoriesHandleResponse(httpResp)
	return resp, err
}

// searchMemoriesCreateRequest creates the SearchMemories request.
func (client *MemoryStoresClient) searchMemoriesCreateRequest(ctx context.Context, name string, scope string, options *MemoryStoresClientSearchMemoriesOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}:search_memories"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	body := struct {
		Scope              string                     `json:"scope"`
		Items              []map[string]any           `json:"items"`
		Previous_search_id *string                    `json:"previous_search_id"`
		Options            *MemorySearchResultOptions `json:"options"`
	}{
		Scope: scope,
	}
	if options != nil && options.Items != nil {
		body.Items = options.Items
	}
	if options != nil && options.PreviousSearchID != nil {
		body.Previous_search_id = options.PreviousSearchID
	}
	if options != nil && options.Options != nil {
		body.Options = options.Options
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// searchMemoriesHandleResponse handles the SearchMemories response.
func (client *MemoryStoresClient) searchMemoriesHandleResponse(resp *http.Response) (MemoryStoresClientSearchMemoriesResponse, error) {
	result := MemoryStoresClientSearchMemoriesResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.MemoryStoreSearchResult); err != nil {
		return MemoryStoresClientSearchMemoriesResponse{}, err
	}
	return result, nil
}

// BeginUpdateMemories - Update memories
//
// Starts an update that writes conversation memories into the specified memory store.
// The operation returns a long-running status location for polling the update result.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store to update.
//   - scope - The namespace that logically groups and isolates memories, such as a user ID.
//   - options - MemoryStoresClientBeginUpdateMemoriesOptions contains the optional parameters for the MemoryStoresClient.BeginUpdateMemories
//     method.
func (client *MemoryStoresClient) BeginUpdateMemories(ctx context.Context, name string, scope string, options *MemoryStoresClientBeginUpdateMemoriesOptions) (*runtime.Poller[MemoryStoresClientUpdateMemoriesResponse], error) {
	if options == nil || options.ResumeToken == "" {
		resp, err := client.updateMemories(ctx, name, scope, options)
		if err != nil {
			return nil, err
		}
		poller, err := runtime.NewPoller(resp, client.internal.Pipeline(), &runtime.NewPollerOptions[MemoryStoresClientUpdateMemoriesResponse]{
			OperationLocationResultPath: "result",
			Tracer:                      client.internal.Tracer(),
		})
		return poller, err
	} else {
		return runtime.NewPollerFromResumeToken(options.ResumeToken, client.internal.Pipeline(), &runtime.NewPollerFromResumeTokenOptions[MemoryStoresClientUpdateMemoriesResponse]{
			Tracer: client.internal.Tracer(),
		})
	}
}

// UpdateMemories - Update memories
//
// Starts an update that writes conversation memories into the specified memory store.
// The operation returns a long-running status location for polling the update result.
// If the operation fails it returns an *azcore.ResponseError type.
func (client *MemoryStoresClient) updateMemories(ctx context.Context, name string, scope string, options *MemoryStoresClientBeginUpdateMemoriesOptions) (*http.Response, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.BeginUpdateMemories", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.updateMemoriesCreateRequest(ctx, name, scope, options)
	if err != nil {
		return nil, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusAccepted) {
		err = runtime.NewResponseError(httpResp)
		return nil, err
	}
	return httpResp, nil
}

// updateMemoriesCreateRequest creates the UpdateMemories request.
func (client *MemoryStoresClient) updateMemoriesCreateRequest(ctx context.Context, name string, scope string, options *MemoryStoresClientBeginUpdateMemoriesOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}:update_memories"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	body := struct {
		Scope              string           `json:"scope"`
		Items              []map[string]any `json:"items"`
		Previous_update_id *string          `json:"previous_update_id"`
		Update_delay       *int32           `json:"update_delay"`
	}{
		Scope: scope,
	}
	if options != nil && options.Items != nil {
		body.Items = options.Items
	}
	if options != nil && options.PreviousUpdateID != nil {
		body.Previous_update_id = options.PreviousUpdateID
	}
	if options != nil && options.UpdateDelay != nil {
		body.Update_delay = options.UpdateDelay
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// UpdateMemory - Update a memory item
//
// Updates the specified memory item in the memory store.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store.
//   - memoryID - The ID of the memory item to update.
//   - content - The updated content of the memory.
//   - options - MemoryStoresClientUpdateMemoryOptions contains the optional parameters for the MemoryStoresClient.UpdateMemory
//     method.
func (client *MemoryStoresClient) UpdateMemory(ctx context.Context, name string, memoryID string, content string, options *MemoryStoresClientUpdateMemoryOptions) (MemoryStoresClientUpdateMemoryResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.UpdateMemory", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.updateMemoryCreateRequest(ctx, name, memoryID, content, options)
	if err != nil {
		return MemoryStoresClientUpdateMemoryResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientUpdateMemoryResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientUpdateMemoryResponse{}, err
	}
	resp, err := client.updateMemoryHandleResponse(httpResp)
	return resp, err
}

// updateMemoryCreateRequest creates the UpdateMemory request.
func (client *MemoryStoresClient) updateMemoryCreateRequest(ctx context.Context, name string, memoryID string, content string, _ *MemoryStoresClientUpdateMemoryOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}/items/{memory_id}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	if memoryID == "" {
		return nil, errors.New("parameter memoryID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{memory_id}", url.PathEscape(memoryID))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	body := struct {
		Content string `json:"content"`
	}{
		Content: content,
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// updateMemoryHandleResponse handles the UpdateMemory response.
func (client *MemoryStoresClient) updateMemoryHandleResponse(resp *http.Response) (MemoryStoresClientUpdateMemoryResponse, error) {
	result := MemoryStoresClientUpdateMemoryResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result); err != nil {
		return MemoryStoresClientUpdateMemoryResponse{}, err
	}
	return result, nil
}

// UpdateMemoryStore - Update a memory store
//
// Updates the specified memory store with the supplied configuration changes.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the memory store to update.
//   - options - MemoryStoresClientUpdateMemoryStoreOptions contains the optional parameters for the MemoryStoresClient.UpdateMemoryStore
//     method.
func (client *MemoryStoresClient) UpdateMemoryStore(ctx context.Context, name string, options *MemoryStoresClientUpdateMemoryStoreOptions) (MemoryStoresClientUpdateMemoryStoreResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "MemoryStoresClient.UpdateMemoryStore", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.updateMemoryStoreCreateRequest(ctx, name, options)
	if err != nil {
		return MemoryStoresClientUpdateMemoryStoreResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return MemoryStoresClientUpdateMemoryStoreResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return MemoryStoresClientUpdateMemoryStoreResponse{}, err
	}
	resp, err := client.updateMemoryStoreHandleResponse(httpResp)
	return resp, err
}

// updateMemoryStoreCreateRequest creates the UpdateMemoryStore request.
func (client *MemoryStoresClient) updateMemoryStoreCreateRequest(ctx context.Context, name string, options *MemoryStoresClientUpdateMemoryStoreOptions) (*policy.Request, error) {
	urlPath := "/memory_stores/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"MemoryStores=V1Preview"}
	body := struct {
		Description *string            `json:"description"`
		Metadata    map[string]*string `json:"metadata"`
	}{}
	if options != nil && options.Description != nil {
		body.Description = options.Description
	}
	if options != nil && options.Metadata != nil {
		body.Metadata = options.Metadata
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// updateMemoryStoreHandleResponse handles the UpdateMemoryStore response.
func (client *MemoryStoresClient) updateMemoryStoreHandleResponse(resp *http.Response) (MemoryStoresClientUpdateMemoryStoreResponse, error) {
	result := MemoryStoresClientUpdateMemoryStoreResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.MemoryStoreObject); err != nil {
		return MemoryStoresClientUpdateMemoryStoreResponse{}, err
	}
	return result, nil
}
