// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import "time"

// ConnectionsClientListOptions contains the optional parameters for the ConnectionsClient.NewListPager method.
type ConnectionsClientListOptions struct {
	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string

	// Lists connections of this specific type
	ConnectionType *ConnectionType

	// Lists connections that are default connections
	DefaultConnection *bool
}

// DatasetsClientCreateOrUpdateVersionOptions contains the optional parameters for the DatasetsClient.CreateOrUpdateVersion
// method.
type DatasetsClientCreateOrUpdateVersionOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientDeleteVersionOptions contains the optional parameters for the DatasetsClient.DeleteVersion method.
type DatasetsClientDeleteVersionOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientGetCredentialsOptions contains the optional parameters for the DatasetsClient.GetCredentials method.
type DatasetsClientGetCredentialsOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientGetVersionOptions contains the optional parameters for the DatasetsClient.GetVersion method.
type DatasetsClientGetVersionOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientListLatestOptions contains the optional parameters for the DatasetsClient.NewListLatestPager method.
type DatasetsClientListLatestOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientListVersionsOptions contains the optional parameters for the DatasetsClient.NewListVersionsPager method.
type DatasetsClientListVersionsOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientStartPendingUploadVersionOptions contains the optional parameters for the DatasetsClient.StartPendingUploadVersion
// method.
type DatasetsClientStartPendingUploadVersionOptions struct {
	// placeholder for future optional parameters
}

// DeploymentsClientGetOptions contains the optional parameters for the DeploymentsClient.Get method.
type DeploymentsClientGetOptions struct {
	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string
}

// DeploymentsClientListOptions contains the optional parameters for the DeploymentsClient.NewListPager method.
type DeploymentsClientListOptions struct {
	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string

	// Type of deployment to filter list by
	DeploymentType *DeploymentType

	// Model name (the publisher specific name) to filter models by
	ModelName *string

	// Model publisher to filter models by
	ModelPublisher *string
}

// EvaluationRulesClientCreateOrUpdateOptions contains the optional parameters for the EvaluationRulesClient.CreateOrUpdate
// method.
type EvaluationRulesClientCreateOrUpdateOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string
}

// EvaluationRulesClientDeleteOptions contains the optional parameters for the EvaluationRulesClient.Delete method.
type EvaluationRulesClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// EvaluationRulesClientGetOptions contains the optional parameters for the EvaluationRulesClient.Get method.
type EvaluationRulesClientGetOptions struct {
	// placeholder for future optional parameters
}

// EvaluationRulesClientListOptions contains the optional parameters for the EvaluationRulesClient.NewListPager method.
type EvaluationRulesClientListOptions struct {
	// Filter by the type of evaluation rule.
	ActionType *EvaluationRuleActionType

	// Filter by the agent name.
	AgentName *string

	// Filter by the enabled status.
	Enabled *bool
}

// EvaluationTaxonomiesClientCreateOptions contains the optional parameters for the EvaluationTaxonomiesClient.Create method.
type EvaluationTaxonomiesClientCreateOptions struct {
	// placeholder for future optional parameters
}

// EvaluationTaxonomiesClientDeleteOptions contains the optional parameters for the EvaluationTaxonomiesClient.Delete method.
type EvaluationTaxonomiesClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// EvaluationTaxonomiesClientGetOptions contains the optional parameters for the EvaluationTaxonomiesClient.Get method.
type EvaluationTaxonomiesClientGetOptions struct {
	// placeholder for future optional parameters
}

// EvaluationTaxonomiesClientListOptions contains the optional parameters for the EvaluationTaxonomiesClient.NewListPager
// method.
type EvaluationTaxonomiesClientListOptions struct {
	// Filter by the evaluation input name.
	InputName *string

	// Filter by taxonomy input type.
	InputType *string
}

// EvaluationTaxonomiesClientUpdateOptions contains the optional parameters for the EvaluationTaxonomiesClient.Update method.
type EvaluationTaxonomiesClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// EvaluatorGenerationJobsClientCancelOptions contains the optional parameters for the EvaluatorGenerationJobsClient.Cancel
// method.
type EvaluatorGenerationJobsClientCancelOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string
}

// EvaluatorGenerationJobsClientCreateOptions contains the optional parameters for the EvaluatorGenerationJobsClient.Create
// method.
type EvaluatorGenerationJobsClientCreateOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string

	// Client-generated unique ID for idempotent retries. When absent, the server creates the job unconditionally.
	OperationID *string
}

// EvaluatorGenerationJobsClientDeleteOptions contains the optional parameters for the EvaluatorGenerationJobsClient.Delete
// method.
type EvaluatorGenerationJobsClientDeleteOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string
}

// EvaluatorGenerationJobsClientGetOptions contains the optional parameters for the EvaluatorGenerationJobsClient.Get method.
type EvaluatorGenerationJobsClientGetOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string
}

// EvaluatorGenerationJobsClientListOptions contains the optional parameters for the EvaluatorGenerationJobsClient.NewListPager
// method.
type EvaluatorGenerationJobsClientListOptions struct {
	// A cursor for use in pagination. `after` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include after=obj_foo in order to fetch the next page of the list.
	After *string

	// A cursor for use in pagination. `before` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include before=obj_foo in order to fetch the previous page of the list.
	Before *string

	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string

	// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the
	// default is 20.
	Limit *int32

	// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and`desc`
	// for descending order.
	Order *PageOrder
}

// EvaluatorsClientCreateVersionOptions contains the optional parameters for the EvaluatorsClient.CreateVersion method.
type EvaluatorsClientCreateVersionOptions struct {
	// placeholder for future optional parameters
}

// EvaluatorsClientDeleteVersionOptions contains the optional parameters for the EvaluatorsClient.DeleteVersion method.
type EvaluatorsClientDeleteVersionOptions struct {
	// placeholder for future optional parameters
}

// EvaluatorsClientGetCredentialsOptions contains the optional parameters for the EvaluatorsClient.GetCredentials method.
type EvaluatorsClientGetCredentialsOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string
}

// EvaluatorsClientGetVersionOptions contains the optional parameters for the EvaluatorsClient.GetVersion method.
type EvaluatorsClientGetVersionOptions struct {
	// placeholder for future optional parameters
}

// EvaluatorsClientListLatestVersionsOptions contains the optional parameters for the EvaluatorsClient.NewListLatestVersionsPager
// method.
type EvaluatorsClientListLatestVersionsOptions struct {
	// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
	Limit *int32

	// Filter evaluators by type. Possible values: 'all', 'custom', 'builtin'.
	Type *ListVersionsRequestType
}

// EvaluatorsClientListVersionsOptions contains the optional parameters for the EvaluatorsClient.NewListVersionsPager method.
type EvaluatorsClientListVersionsOptions struct {
	// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
	Limit *int32

	// Filter evaluators by type. Possible values: 'all', 'custom', 'builtin'.
	Type *ListVersionsRequestType
}

// EvaluatorsClientStartPendingUploadOptions contains the optional parameters for the EvaluatorsClient.StartPendingUpload
// method.
type EvaluatorsClientStartPendingUploadOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string
}

// EvaluatorsClientUpdateVersionOptions contains the optional parameters for the EvaluatorsClient.UpdateVersion method.
type EvaluatorsClientUpdateVersionOptions struct {
	// placeholder for future optional parameters
}

// IndexesClientCreateOrUpdateVersionOptions contains the optional parameters for the IndexesClient.CreateOrUpdateVersion
// method.
type IndexesClientCreateOrUpdateVersionOptions struct {
	// placeholder for future optional parameters
}

// IndexesClientDeleteVersionOptions contains the optional parameters for the IndexesClient.DeleteVersion method.
type IndexesClientDeleteVersionOptions struct {
	// placeholder for future optional parameters
}

// IndexesClientGetVersionOptions contains the optional parameters for the IndexesClient.GetVersion method.
type IndexesClientGetVersionOptions struct {
	// placeholder for future optional parameters
}

// IndexesClientListLatestOptions contains the optional parameters for the IndexesClient.NewListLatestPager method.
type IndexesClientListLatestOptions struct {
	// placeholder for future optional parameters
}

// IndexesClientListVersionsOptions contains the optional parameters for the IndexesClient.NewListVersionsPager method.
type IndexesClientListVersionsOptions struct {
	// placeholder for future optional parameters
}

// InsightsClientGenerateOptions contains the optional parameters for the InsightsClient.Generate method.
type InsightsClientGenerateOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string

	// Timestamp indicating when this request was first initiated. Used in conjunction with repeatability-request-id for idempotency
	// control.
	RepeatabilityFirstSent *time.Time

	// Unique, client-generated identifier for ensuring request idempotency. Use the same ID for retries to prevent duplicate
	// evaluations.
	RepeatabilityRequestID *string
}

// InsightsClientGetOptions contains the optional parameters for the InsightsClient.Get method.
type InsightsClientGetOptions struct {
	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string

	// Whether to include coordinates for visualization in the response. Defaults to false.
	IncludeCoordinates *bool
}

// InsightsClientListOptions contains the optional parameters for the InsightsClient.NewListPager method.
type InsightsClientListOptions struct {
	// Filter by the agent name.
	AgentName *string

	// Filter by the evaluation ID.
	EvalID *string

	// A feature flag opt-in required when using preview operations or modifying persisted preview resources.
	FoundryFeatures *string

	// Whether to include coordinates for visualization in the response. Defaults to false.
	IncludeCoordinates *bool

	// Filter by the evaluation run ID.
	RunID *string

	// Filter by the type of analysis.
	Type *InsightType
}

// MemoryStoresClientBeginUpdateMemoriesOptions contains the optional parameters for the MemoryStoresClient.BeginUpdateMemories
// method.
type MemoryStoresClientBeginUpdateMemoriesOptions struct {
	// A list of messages to store in memory. Each item is represented as a map with keys such as `type`, `role`, and `content`,
	// similar to OpenAI response input items. Only message items are currently processed; other item types are ignored.
	Items []map[string]any

	// The unique ID of the previous update request, enabling incremental memory updates from where the last operation left off.
	PreviousUpdateID *string

	// Resumes the long-running operation from the provided token.
	ResumeToken string

	// Timeout period before processing the memory update in seconds.
	// If a new update request is received during this period, it will cancel the current request and reset the timeout.
	// Set to 0 to immediately trigger the update without delay.
	// Defaults to 300 (5 minutes).
	UpdateDelay *int32
}

// MemoryStoresClientCreateMemoryOptions contains the optional parameters for the MemoryStoresClient.CreateMemory method.
type MemoryStoresClientCreateMemoryOptions struct {
	// placeholder for future optional parameters
}

// MemoryStoresClientCreateMemoryStoreOptions contains the optional parameters for the MemoryStoresClient.CreateMemoryStore
// method.
type MemoryStoresClientCreateMemoryStoreOptions struct {
	// A human-readable description of the memory store.
	Description *string

	// Arbitrary key-value metadata to associate with the memory store.
	Metadata map[string]*string
}

// MemoryStoresClientDeleteMemoryOptions contains the optional parameters for the MemoryStoresClient.DeleteMemory method.
type MemoryStoresClientDeleteMemoryOptions struct {
	// placeholder for future optional parameters
}

// MemoryStoresClientDeleteMemoryStoreOptions contains the optional parameters for the MemoryStoresClient.DeleteMemoryStore
// method.
type MemoryStoresClientDeleteMemoryStoreOptions struct {
	// placeholder for future optional parameters
}

// MemoryStoresClientDeleteScopeOptions contains the optional parameters for the MemoryStoresClient.DeleteScope method.
type MemoryStoresClientDeleteScopeOptions struct {
	// placeholder for future optional parameters
}

// MemoryStoresClientGetMemoryOptions contains the optional parameters for the MemoryStoresClient.GetMemory method.
type MemoryStoresClientGetMemoryOptions struct {
	// placeholder for future optional parameters
}

// MemoryStoresClientGetMemoryStoreOptions contains the optional parameters for the MemoryStoresClient.GetMemoryStore method.
type MemoryStoresClientGetMemoryStoreOptions struct {
	// placeholder for future optional parameters
}

// MemoryStoresClientGetUpdateResultOptions contains the optional parameters for the MemoryStoresClient.GetUpdateResult method.
type MemoryStoresClientGetUpdateResultOptions struct {
	// placeholder for future optional parameters
}

// MemoryStoresClientListMemoriesOptions contains the optional parameters for the MemoryStoresClient.NewListMemoriesPager
// method.
type MemoryStoresClientListMemoriesOptions struct {
	// A cursor for use in pagination. `after` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include after=obj_foo in order to fetch the next page of the list.
	After *string

	// A cursor for use in pagination. `before` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include before=obj_foo in order to fetch the previous page of the list.
	Before *string

	// The kind of the memory item.
	Kind *MemoryItemKind

	// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the
	// default is 20.
	Limit *int32

	// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and`desc`
	// for descending order.
	Order *PageOrder
}

// MemoryStoresClientListMemoryStoresOptions contains the optional parameters for the MemoryStoresClient.NewListMemoryStoresPager
// method.
type MemoryStoresClientListMemoryStoresOptions struct {
	// A cursor for use in pagination. `after` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include after=obj_foo in order to fetch the next page of the list.
	After *string

	// A cursor for use in pagination. `before` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include before=obj_foo in order to fetch the previous page of the list.
	Before *string

	// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the
	// default is 20.
	Limit *int32

	// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and`desc`
	// for descending order.
	Order *PageOrder
}

// MemoryStoresClientSearchMemoriesOptions contains the optional parameters for the MemoryStoresClient.SearchMemories method.
type MemoryStoresClientSearchMemoriesOptions struct {
	// A list of messages used to search for relevant memories. Each item is represented as a map with keys such as `type`, `role`,
	// and `content`, similar to OpenAI response input items. Only message items are currently processed; other item types are
	// ignored.
	Items []map[string]any

	// Memory search options.
	Options *MemorySearchResultOptions

	// The unique ID of the previous search request, enabling incremental memory search from where the last operation left off.
	PreviousSearchID *string
}

// MemoryStoresClientUpdateMemoryOptions contains the optional parameters for the MemoryStoresClient.UpdateMemory method.
type MemoryStoresClientUpdateMemoryOptions struct {
	// placeholder for future optional parameters
}

// MemoryStoresClientUpdateMemoryStoreOptions contains the optional parameters for the MemoryStoresClient.UpdateMemoryStore
// method.
type MemoryStoresClientUpdateMemoryStoreOptions struct {
	// A human-readable description of the memory store.
	Description *string

	// Arbitrary key-value metadata to associate with the memory store.
	Metadata map[string]*string
}

// RedTeamsClientCreateOptions contains the optional parameters for the RedTeamsClient.Create method.
type RedTeamsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// RedTeamsClientGetOptions contains the optional parameters for the RedTeamsClient.Get method.
type RedTeamsClientGetOptions struct {
	// placeholder for future optional parameters
}

// RedTeamsClientListOptions contains the optional parameters for the RedTeamsClient.NewListPager method.
type RedTeamsClientListOptions struct {
	// placeholder for future optional parameters
}

// SchedulesClientCreateOrUpdateOptions contains the optional parameters for the SchedulesClient.CreateOrUpdate method.
type SchedulesClientCreateOrUpdateOptions struct {
	// placeholder for future optional parameters
}

// SchedulesClientDeleteOptions contains the optional parameters for the SchedulesClient.Delete method.
type SchedulesClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// SchedulesClientGetOptions contains the optional parameters for the SchedulesClient.Get method.
type SchedulesClientGetOptions struct {
	// placeholder for future optional parameters
}

// SchedulesClientGetRunOptions contains the optional parameters for the SchedulesClient.GetRun method.
type SchedulesClientGetRunOptions struct {
	// placeholder for future optional parameters
}

// SchedulesClientListOptions contains the optional parameters for the SchedulesClient.NewListPager method.
type SchedulesClientListOptions struct {
	// Filter by the enabled status.
	Enabled *bool

	// Filter by the type of schedule.
	Type *ScheduleTaskType
}

// SchedulesClientListRunsOptions contains the optional parameters for the SchedulesClient.NewListRunsPager method.
type SchedulesClientListRunsOptions struct {
	// Filter by the enabled status.
	Enabled *bool

	// Filter by the type of schedule.
	Type *ScheduleTaskType
}

// ToolboxesClientCreateToolboxVersionOptions contains the optional parameters for the ToolboxesClient.CreateToolboxVersion
// method.
type ToolboxesClientCreateToolboxVersionOptions struct {
	// A human-readable description of the toolbox.
	Description *string

	// Arbitrary key-value metadata to associate with the toolbox.
	Metadata map[string]*string

	// Policy configuration for this toolbox version.
	Policies *ToolboxPolicies

	// The list of skill sources to include in this version. A skill reference specifies a skill name and optionally a version.
	// If version is omitted, the skill's default version is used.
	Skills []ToolboxSkillClassification
}

// ToolboxesClientDeleteToolboxOptions contains the optional parameters for the ToolboxesClient.DeleteToolbox method.
type ToolboxesClientDeleteToolboxOptions struct {
	// placeholder for future optional parameters
}

// ToolboxesClientDeleteToolboxVersionOptions contains the optional parameters for the ToolboxesClient.DeleteToolboxVersion
// method.
type ToolboxesClientDeleteToolboxVersionOptions struct {
	// placeholder for future optional parameters
}

// ToolboxesClientGetToolboxOptions contains the optional parameters for the ToolboxesClient.GetToolbox method.
type ToolboxesClientGetToolboxOptions struct {
	// placeholder for future optional parameters
}

// ToolboxesClientGetToolboxVersionOptions contains the optional parameters for the ToolboxesClient.GetToolboxVersion method.
type ToolboxesClientGetToolboxVersionOptions struct {
	// placeholder for future optional parameters
}

// ToolboxesClientListToolboxVersionsOptions contains the optional parameters for the ToolboxesClient.NewListToolboxVersionsPager
// method.
type ToolboxesClientListToolboxVersionsOptions struct {
	// A cursor for use in pagination. `after` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include after=obj_foo in order to fetch the next page of the list.
	After *string

	// A cursor for use in pagination. `before` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include before=obj_foo in order to fetch the previous page of the list.
	Before *string

	// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the
	// default is 20.
	Limit *int32

	// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and`desc`
	// for descending order.
	Order *PageOrder
}

// ToolboxesClientListToolboxesOptions contains the optional parameters for the ToolboxesClient.NewListToolboxesPager method.
type ToolboxesClientListToolboxesOptions struct {
	// A cursor for use in pagination. `after` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include after=obj_foo in order to fetch the next page of the list.
	After *string

	// A cursor for use in pagination. `before` is an object ID that defines your place in the list.
	// For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
	// subsequent call can include before=obj_foo in order to fetch the previous page of the list.
	Before *string

	// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the
	// default is 20.
	Limit *int32

	// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and`desc`
	// for descending order.
	Order *PageOrder
}

// ToolboxesClientUpdateToolboxOptions contains the optional parameters for the ToolboxesClient.UpdateToolbox method.
type ToolboxesClientUpdateToolboxOptions struct {
	// placeholder for future optional parameters
}

// connectionsClientgetOptions contains the optional parameters for the ConnectionsClient.get method.
type connectionsClientgetOptions struct {
	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string
}

// connectionsClientgetWithCredentialsOptions contains the optional parameters for the ConnectionsClient.getWithCredentials
// method.
type connectionsClientgetWithCredentialsOptions struct {
	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string
}
