// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import "encoding/json"

func unmarshalBaseCredentialsClassification(rawMsg json.RawMessage) (BaseCredentialsClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b BaseCredentialsClassification
	switch m["type"] {
	case string(CredentialTypeAPIKey):
		b = &APIKeyCredentials{}
	case string(CredentialTypeAgenticIdentityPreview):
		b = &AgenticIdentityPreviewCredentials{}
	case string(CredentialTypeCustom):
		b = &CustomCredential{}
	case string(CredentialTypeEntraID):
		b = &EntraIDCredentials{}
	case string(CredentialTypeNone):
		b = &NoAuthenticationCredentials{}
	case string(CredentialTypeSAS):
		b = &SASCredentials{}
	default:
		b = &BaseCredentials{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalContainerNetworkPolicyParamClassification(rawMsg json.RawMessage) (ContainerNetworkPolicyParamClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b ContainerNetworkPolicyParamClassification
	switch m["type"] {
	case string(ContainerNetworkPolicyParamTypeAllowlist):
		b = &ContainerNetworkPolicyAllowlistParam{}
	case string(ContainerNetworkPolicyParamTypeDisabled):
		b = &ContainerNetworkPolicyDisabledParam{}
	default:
		b = &ContainerNetworkPolicyParam{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalContainerSkillClassification(rawMsg json.RawMessage) (ContainerSkillClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b ContainerSkillClassification
	switch m["type"] {
	case string(ContainerSkillTypeInline):
		b = &InlineSkillParam{}
	case string(ContainerSkillTypeSkillReference):
		b = &SkillReferenceParam{}
	default:
		b = &ContainerSkill{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalContainerSkillClassificationArray(rawMsg json.RawMessage) ([]ContainerSkillClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]ContainerSkillClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalContainerSkillClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalCustomToolParamFormatClassification(rawMsg json.RawMessage) (CustomToolParamFormatClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b CustomToolParamFormatClassification
	switch m["type"] {
	case string(CustomToolParamFormatTypeGrammar):
		b = &CustomGrammarFormatParam{}
	case string(CustomToolParamFormatTypeText):
		b = &CustomTextFormatParam{}
	default:
		b = &CustomToolParamFormat{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalDatasetVersionClassification(rawMsg json.RawMessage) (DatasetVersionClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b DatasetVersionClassification
	switch m["type"] {
	case string(DatasetTypeURIFile):
		b = &FileDatasetVersion{}
	case string(DatasetTypeURIFolder):
		b = &FolderDatasetVersion{}
	default:
		b = &DatasetVersion{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalDatasetVersionClassificationArray(rawMsg json.RawMessage) ([]DatasetVersionClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]DatasetVersionClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalDatasetVersionClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalDeploymentClassification(rawMsg json.RawMessage) (DeploymentClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b DeploymentClassification
	switch m["type"] {
	case string(DeploymentTypeModelDeployment):
		b = &ModelDeployment{}
	default:
		b = &Deployment{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalDeploymentClassificationArray(rawMsg json.RawMessage) ([]DeploymentClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]DeploymentClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalDeploymentClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalEvaluationRuleActionClassification(rawMsg json.RawMessage) (EvaluationRuleActionClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b EvaluationRuleActionClassification
	switch m["type"] {
	case string(EvaluationRuleActionTypeContinuousEvaluation):
		b = &ContinuousEvaluationRuleAction{}
	case string(EvaluationRuleActionTypeHumanEvaluationPreview):
		b = &HumanEvaluationPreviewRuleAction{}
	default:
		b = &EvaluationRuleAction{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalEvaluationTaxonomyInputClassification(rawMsg json.RawMessage) (EvaluationTaxonomyInputClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b EvaluationTaxonomyInputClassification
	switch m["type"] {
	case string(EvaluationTaxonomyInputTypeAgent):
		b = &AgentTaxonomyInput{}
	default:
		b = &EvaluationTaxonomyInput{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalEvaluatorDefinitionClassification(rawMsg json.RawMessage) (EvaluatorDefinitionClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b EvaluatorDefinitionClassification
	switch m["type"] {
	case string(EvaluatorDefinitionTypeCode):
		b = &CodeBasedEvaluatorDefinition{}
	case string(EvaluatorDefinitionTypePrompt):
		b = &PromptBasedEvaluatorDefinition{}
	case string(EvaluatorDefinitionTypeRubric):
		b = &RubricBasedEvaluatorDefinition{}
	default:
		b = &EvaluatorDefinition{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalEvaluatorGenerationJobSourceClassification(rawMsg json.RawMessage) (EvaluatorGenerationJobSourceClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b EvaluatorGenerationJobSourceClassification
	switch m["type"] {
	case string(EvaluatorGenerationJobSourceTypeAgent):
		b = &AgentEvaluatorGenerationJobSource{}
	case string(EvaluatorGenerationJobSourceTypeDataset):
		b = &DatasetEvaluatorGenerationJobSource{}
	case string(EvaluatorGenerationJobSourceTypePrompt):
		b = &PromptEvaluatorGenerationJobSource{}
	case string(EvaluatorGenerationJobSourceTypeTraces):
		b = &TracesEvaluatorGenerationJobSource{}
	default:
		b = &EvaluatorGenerationJobSource{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalEvaluatorGenerationJobSourceClassificationArray(rawMsg json.RawMessage) ([]EvaluatorGenerationJobSourceClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]EvaluatorGenerationJobSourceClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalEvaluatorGenerationJobSourceClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalFunctionShellToolParamEnvironmentClassification(rawMsg json.RawMessage) (FunctionShellToolParamEnvironmentClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b FunctionShellToolParamEnvironmentClassification
	switch m["type"] {
	case string(FunctionShellToolParamEnvironmentTypeContainerAuto):
		b = &ContainerAutoParam{}
	case string(FunctionShellToolParamEnvironmentTypeContainerReference):
		b = &FunctionShellToolParamEnvironmentContainerReferenceParam{}
	case string(FunctionShellToolParamEnvironmentTypeLocal):
		b = &FunctionShellToolParamEnvironmentLocalEnvironmentParam{}
	default:
		b = &FunctionShellToolParamEnvironment{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalIndexClassification(rawMsg json.RawMessage) (IndexClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b IndexClassification
	switch m["type"] {
	case string(IndexTypeAzureSearch):
		b = &AzureAISearchIndex{}
	case string(IndexTypeCosmosDB):
		b = &CosmosDBIndex{}
	case string(IndexTypeManagedAzureSearch):
		b = &ManagedAzureAISearchIndex{}
	default:
		b = &Index{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalIndexClassificationArray(rawMsg json.RawMessage) ([]IndexClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]IndexClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalIndexClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalInsightRequestClassification(rawMsg json.RawMessage) (InsightRequestClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b InsightRequestClassification
	switch m["type"] {
	case string(InsightTypeAgentClusterInsight):
		b = &AgentClusterInsightRequest{}
	case string(InsightTypeEvaluationComparison):
		b = &EvaluationComparisonInsightRequest{}
	case string(InsightTypeEvaluationRunClusterInsight):
		b = &EvaluationRunClusterInsightRequest{}
	default:
		b = &InsightRequest{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalInsightResultClassification(rawMsg json.RawMessage) (InsightResultClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b InsightResultClassification
	switch m["type"] {
	case string(InsightTypeAgentClusterInsight):
		b = &AgentClusterInsightResult{}
	case string(InsightTypeEvaluationComparison):
		b = &EvaluationComparisonInsightResult{}
	case string(InsightTypeEvaluationRunClusterInsight):
		b = &EvaluationRunClusterInsightResult{}
	default:
		b = &InsightResult{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalInsightSampleClassification(rawMsg json.RawMessage) (InsightSampleClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b InsightSampleClassification
	switch m["type"] {
	case string(SampleTypeEvaluationResultSample):
		b = &EvaluationResultSample{}
	default:
		b = &InsightSample{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalInsightSampleClassificationArray(rawMsg json.RawMessage) ([]InsightSampleClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]InsightSampleClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalInsightSampleClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalMemoryItemClassification(rawMsg json.RawMessage) (MemoryItemClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b MemoryItemClassification
	switch m["kind"] {
	case string(MemoryItemKindChatSummary):
		b = &ChatSummaryMemoryItem{}
	case string(MemoryItemKindProcedural):
		b = &ProceduralMemoryItem{}
	case string(MemoryItemKindUserProfile):
		b = &UserProfileMemoryItem{}
	default:
		b = &MemoryItem{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalMemoryItemClassificationArray(rawMsg json.RawMessage) ([]MemoryItemClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]MemoryItemClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalMemoryItemClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalMemoryStoreDefinitionClassification(rawMsg json.RawMessage) (MemoryStoreDefinitionClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b MemoryStoreDefinitionClassification
	switch m["kind"] {
	case string(MemoryStoreKindDefault):
		b = &MemoryStoreDefaultDefinition{}
	default:
		b = &MemoryStoreDefinition{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalOpenAPIAuthDetailsClassification(rawMsg json.RawMessage) (OpenAPIAuthDetailsClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b OpenAPIAuthDetailsClassification
	switch m["type"] {
	case string(OpenAPIAuthTypeAnonymous):
		b = &OpenAPIAnonymousAuthDetails{}
	case string(OpenAPIAuthTypeManagedIdentity):
		b = &OpenAPIManagedAuthDetails{}
	case string(OpenAPIAuthTypeProjectConnection):
		b = &OpenAPIProjectConnectionAuthDetails{}
	default:
		b = &OpenAPIAuthDetails{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalRecurrenceScheduleClassification(rawMsg json.RawMessage) (RecurrenceScheduleClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b RecurrenceScheduleClassification
	switch m["type"] {
	case string(RecurrenceTypeDaily):
		b = &DailyRecurrenceSchedule{}
	case string(RecurrenceTypeHourly):
		b = &HourlyRecurrenceSchedule{}
	case string(RecurrenceTypeMonthly):
		b = &MonthlyRecurrenceSchedule{}
	case string(RecurrenceTypeWeekly):
		b = &WeeklyRecurrenceSchedule{}
	default:
		b = &RecurrenceSchedule{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalRedTeamTargetConfigClassification(rawMsg json.RawMessage) (RedTeamTargetConfigClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b RedTeamTargetConfigClassification
	switch m["type"] {
	case "AzureOpenAIModel":
		b = &AzureOpenAIModelConfiguration{}
	default:
		b = &RedTeamTargetConfig{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalScheduleTaskClassification(rawMsg json.RawMessage) (ScheduleTaskClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b ScheduleTaskClassification
	switch m["type"] {
	case string(ScheduleTaskTypeEvaluation):
		b = &EvaluationScheduleTask{}
	case string(ScheduleTaskTypeInsight):
		b = &InsightScheduleTask{}
	default:
		b = &ScheduleTask{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalTargetClassification(rawMsg json.RawMessage) (TargetClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b TargetClassification
	switch m["type"] {
	case "azure_ai_agent":
		b = &AzureAIAgentTarget{}
	case "azure_ai_model":
		b = &AzureAIModelTarget{}
	default:
		b = &Target{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalToolClassification(rawMsg json.RawMessage) (ToolClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b ToolClassification
	switch m["type"] {
	case string(ToolTypeA2APreview):
		b = &A2APreviewTool{}
	case string(ToolTypeApplyPatch):
		b = &ApplyPatchToolParam{}
	case string(ToolTypeAzureAiSearch):
		b = &AzureAISearchTool{}
	case string(ToolTypeAzureFunction):
		b = &AzureFunctionTool{}
	case string(ToolTypeBingCustomSearchPreview):
		b = &BingCustomSearchPreviewTool{}
	case string(ToolTypeBingGrounding):
		b = &BingGroundingTool{}
	case string(ToolTypeBrowserAutomationPreview):
		b = &BrowserAutomationPreviewTool{}
	case string(ToolTypeCaptureStructuredOutputs):
		b = &CaptureStructuredOutputsTool{}
	case string(ToolTypeCodeInterpreter):
		b = &CodeInterpreterTool{}
	case string(ToolTypeComputer):
		b = &ComputerTool{}
	case string(ToolTypeComputerUsePreview):
		b = &ComputerUsePreviewTool{}
	case string(ToolTypeCustom):
		b = &CustomToolParam{}
	case string(ToolTypeFabricDataagentPreview):
		b = &MicrosoftFabricPreviewTool{}
	case string(ToolTypeFabricIqPreview):
		b = &FabricIQPreviewTool{}
	case string(ToolTypeFileSearch):
		b = &FileSearchTool{}
	case string(ToolTypeFunction):
		b = &FunctionTool{}
	case string(ToolTypeImageGeneration):
		b = &ImageGenTool{}
	case string(ToolTypeLocalShell):
		b = &LocalShellToolParam{}
	case string(ToolTypeMcp):
		b = &MCPTool{}
	case string(ToolTypeMemorySearchPreview):
		b = &MemorySearchPreviewTool{}
	case string(ToolTypeNamespace):
		b = &NamespaceToolParam{}
	case string(ToolTypeOpenapi):
		b = &OpenAPITool{}
	case string(ToolTypeReminderPreview):
		b = &ReminderPreviewTool{}
	case string(ToolTypeSharepointGroundingPreview):
		b = &SharepointPreviewTool{}
	case string(ToolTypeShell):
		b = &FunctionShellToolParam{}
	case string(ToolTypeToolSearch):
		b = &ToolSearchToolParam{}
	case string(ToolTypeWebSearch):
		b = &WebSearchTool{}
	case string(ToolTypeWebSearchPreview):
		b = &WebSearchPreviewTool{}
	case string(ToolTypeWorkIqPreview):
		b = &WorkIQPreviewTool{}
	default:
		b = &Tool{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalToolClassificationArray(rawMsg json.RawMessage) ([]ToolClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]ToolClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalToolClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalToolboxSkillClassification(rawMsg json.RawMessage) (ToolboxSkillClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b ToolboxSkillClassification
	switch m["type"] {
	case "skill_reference":
		b = &ToolboxSkillReference{}
	default:
		b = &ToolboxSkill{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalToolboxSkillClassificationArray(rawMsg json.RawMessage) ([]ToolboxSkillClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]ToolboxSkillClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalToolboxSkillClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalToolboxToolClassification(rawMsg json.RawMessage) (ToolboxToolClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b ToolboxToolClassification
	switch m["type"] {
	case string(ToolboxToolTypeA2APreview):
		b = &A2APreviewToolboxTool{}
	case string(ToolboxToolTypeAzureAiSearch):
		b = &AzureAISearchToolboxTool{}
	case string(ToolboxToolTypeBrowserAutomationPreview):
		b = &BrowserAutomationPreviewToolboxTool{}
	case string(ToolboxToolTypeCodeInterpreter):
		b = &CodeInterpreterToolboxTool{}
	case string(ToolboxToolTypeFabricIqPreview):
		b = &FabricIQPreviewToolboxTool{}
	case string(ToolboxToolTypeFileSearch):
		b = &FileSearchToolboxTool{}
	case string(ToolboxToolTypeMcp):
		b = &MCPToolboxTool{}
	case string(ToolboxToolTypeOpenapi):
		b = &OpenAPIToolboxTool{}
	case string(ToolboxToolTypeReminderPreview):
		b = &ReminderPreviewToolboxTool{}
	case string(ToolboxToolTypeToolboxSearchPreview):
		b = &ToolboxSearchPreviewToolboxTool{}
	case string(ToolboxToolTypeWebSearch):
		b = &WebSearchToolboxTool{}
	case string(ToolboxToolTypeWorkIqPreview):
		b = &WorkIQPreviewToolboxTool{}
	default:
		b = &ToolboxTool{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

func unmarshalToolboxToolClassificationArray(rawMsg json.RawMessage) ([]ToolboxToolClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(rawMsg, &rawMessages); err != nil {
		return nil, err
	}
	fArray := make([]ToolboxToolClassification, len(rawMessages))
	for index, rawMessage := range rawMessages {
		f, err := unmarshalToolboxToolClassification(rawMessage)
		if err != nil {
			return nil, err
		}
		fArray[index] = f
	}
	return fArray, nil
}

func unmarshalTriggerClassification(rawMsg json.RawMessage) (TriggerClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b TriggerClassification
	switch m["type"] {
	case string(TriggerTypeCron):
		b = &CronTrigger{}
	case string(TriggerTypeOneTime):
		b = &OneTimeTrigger{}
	case string(TriggerTypeRecurrence):
		b = &RecurrenceTrigger{}
	default:
		b = &Trigger{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}
