// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

// ConnectionsClientListResponse contains the response from method ConnectionsClient.NewListPager.
type ConnectionsClientListResponse struct {
	// Paged collection of Connection items
	PagedConnection

	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string
}

// DatasetsClientCreateOrUpdateVersionResponse contains the response from method DatasetsClient.CreateOrUpdateVersion.
type DatasetsClientCreateOrUpdateVersionResponse struct {
	// DatasetVersion Definition
	DatasetVersionClassification
}

// DatasetsClientDeleteVersionResponse contains the response from method DatasetsClient.DeleteVersion.
type DatasetsClientDeleteVersionResponse struct {
	// placeholder for future response values
}

// DatasetsClientGetCredentialsResponse contains the response from method DatasetsClient.GetCredentials.
type DatasetsClientGetCredentialsResponse struct {
	// Represents a reference to a blob for consumption
	DatasetCredential
}

// DatasetsClientGetVersionResponse contains the response from method DatasetsClient.GetVersion.
type DatasetsClientGetVersionResponse struct {
	// DatasetVersion Definition
	DatasetVersionClassification
}

// DatasetsClientListLatestResponse contains the response from method DatasetsClient.NewListLatestPager.
type DatasetsClientListLatestResponse struct {
	// Paged collection of DatasetVersion items
	PagedDatasetVersion
}

// DatasetsClientListVersionsResponse contains the response from method DatasetsClient.NewListVersionsPager.
type DatasetsClientListVersionsResponse struct {
	// Paged collection of DatasetVersion items
	PagedDatasetVersion
}

// DatasetsClientStartPendingUploadVersionResponse contains the response from method DatasetsClient.StartPendingUploadVersion.
type DatasetsClientStartPendingUploadVersionResponse struct {
	// Represents the response for a pending upload request
	PendingUploadResponse
}

// DeploymentsClientGetResponse contains the response from method DeploymentsClient.Get.
type DeploymentsClientGetResponse struct {
	// Model Deployment Definition
	DeploymentClassification

	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string
}

// DeploymentsClientListResponse contains the response from method DeploymentsClient.NewListPager.
type DeploymentsClientListResponse struct {
	// Paged collection of Deployment items
	PagedDeployment

	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string
}

// EvaluationRulesClientCreateOrUpdateResponse contains the response from method EvaluationRulesClient.CreateOrUpdate.
type EvaluationRulesClientCreateOrUpdateResponse struct {
	// Evaluation rule model.
	EvaluationRule
}

// EvaluationRulesClientDeleteResponse contains the response from method EvaluationRulesClient.Delete.
type EvaluationRulesClientDeleteResponse struct {
	// placeholder for future response values
}

// EvaluationRulesClientGetResponse contains the response from method EvaluationRulesClient.Get.
type EvaluationRulesClientGetResponse struct {
	// Evaluation rule model.
	EvaluationRule
}

// EvaluationRulesClientListResponse contains the response from method EvaluationRulesClient.NewListPager.
type EvaluationRulesClientListResponse struct {
	// Paged collection of EvaluationRule items
	PagedEvaluationRule
}

// EvaluationTaxonomiesClientCreateResponse contains the response from method EvaluationTaxonomiesClient.Create.
type EvaluationTaxonomiesClientCreateResponse struct {
	// Evaluation Taxonomy Definition
	EvaluationTaxonomy
}

// EvaluationTaxonomiesClientDeleteResponse contains the response from method EvaluationTaxonomiesClient.Delete.
type EvaluationTaxonomiesClientDeleteResponse struct {
	// placeholder for future response values
}

// EvaluationTaxonomiesClientGetResponse contains the response from method EvaluationTaxonomiesClient.Get.
type EvaluationTaxonomiesClientGetResponse struct {
	// Evaluation Taxonomy Definition
	EvaluationTaxonomy
}

// EvaluationTaxonomiesClientListResponse contains the response from method EvaluationTaxonomiesClient.NewListPager.
type EvaluationTaxonomiesClientListResponse struct {
	// Paged collection of EvaluationTaxonomy items
	PagedEvaluationTaxonomy
}

// EvaluationTaxonomiesClientUpdateResponse contains the response from method EvaluationTaxonomiesClient.Update.
type EvaluationTaxonomiesClientUpdateResponse struct {
	// Evaluation Taxonomy Definition
	EvaluationTaxonomy
}

// EvaluatorGenerationJobsClientCancelResponse contains the response from method EvaluatorGenerationJobsClient.Cancel.
type EvaluatorGenerationJobsClientCancelResponse struct {
	// Evaluator Generation Job resource — a long-running job that generates rubric-based evaluator definitions from source materials.
	// On success, the result is the persisted EvaluatorVersion.
	EvaluatorGenerationJob
}

// EvaluatorGenerationJobsClientCreateResponse contains the response from method EvaluatorGenerationJobsClient.Create.
type EvaluatorGenerationJobsClientCreateResponse struct {
	// Evaluator Generation Job resource — a long-running job that generates rubric-based evaluator definitions from source materials.
	// On success, the result is the persisted EvaluatorVersion.
	EvaluatorGenerationJob

	// URL of the created job resource.
	Location *string

	// URL to poll for the job status.
	OperationLocation *string
}

// EvaluatorGenerationJobsClientDeleteResponse contains the response from method EvaluatorGenerationJobsClient.Delete.
type EvaluatorGenerationJobsClientDeleteResponse struct {
	// placeholder for future response values
}

// EvaluatorGenerationJobsClientGetResponse contains the response from method EvaluatorGenerationJobsClient.Get.
type EvaluatorGenerationJobsClientGetResponse struct {
	// Evaluator Generation Job resource — a long-running job that generates rubric-based evaluator definitions from source materials.
	// On success, the result is the persisted EvaluatorVersion.
	EvaluatorGenerationJob

	// Recommended number of seconds to wait before polling again.
	RetryAfter *int32
}

// EvaluatorGenerationJobsClientListResponse contains the response from method EvaluatorGenerationJobsClient.NewListPager.
type EvaluatorGenerationJobsClientListResponse struct {
	// The response data for a requested list of items.
	AgentsPagedResultEvaluatorGenerationJob
}

// EvaluatorsClientCreateVersionResponse contains the response from method EvaluatorsClient.CreateVersion.
type EvaluatorsClientCreateVersionResponse struct {
	// Evaluator Definition
	EvaluatorVersion
}

// EvaluatorsClientDeleteVersionResponse contains the response from method EvaluatorsClient.DeleteVersion.
type EvaluatorsClientDeleteVersionResponse struct {
	// placeholder for future response values
}

// EvaluatorsClientGetCredentialsResponse contains the response from method EvaluatorsClient.GetCredentials.
type EvaluatorsClientGetCredentialsResponse struct {
	// Represents a reference to a blob for consumption
	DatasetCredential
}

// EvaluatorsClientGetVersionResponse contains the response from method EvaluatorsClient.GetVersion.
type EvaluatorsClientGetVersionResponse struct {
	// Evaluator Definition
	EvaluatorVersion
}

// EvaluatorsClientListLatestVersionsResponse contains the response from method EvaluatorsClient.NewListLatestVersionsPager.
type EvaluatorsClientListLatestVersionsResponse struct {
	// Paged collection of EvaluatorVersion items
	PagedEvaluatorVersion
}

// EvaluatorsClientListVersionsResponse contains the response from method EvaluatorsClient.NewListVersionsPager.
type EvaluatorsClientListVersionsResponse struct {
	// Paged collection of EvaluatorVersion items
	PagedEvaluatorVersion
}

// EvaluatorsClientStartPendingUploadResponse contains the response from method EvaluatorsClient.StartPendingUpload.
type EvaluatorsClientStartPendingUploadResponse struct {
	// Represents the response for a pending upload request
	PendingUploadResponse
}

// EvaluatorsClientUpdateVersionResponse contains the response from method EvaluatorsClient.UpdateVersion.
type EvaluatorsClientUpdateVersionResponse struct {
	// Evaluator Definition
	EvaluatorVersion
}

// IndexesClientCreateOrUpdateVersionResponse contains the response from method IndexesClient.CreateOrUpdateVersion.
type IndexesClientCreateOrUpdateVersionResponse struct {
	// Index resource Definition
	IndexClassification
}

// IndexesClientDeleteVersionResponse contains the response from method IndexesClient.DeleteVersion.
type IndexesClientDeleteVersionResponse struct {
	// placeholder for future response values
}

// IndexesClientGetVersionResponse contains the response from method IndexesClient.GetVersion.
type IndexesClientGetVersionResponse struct {
	// Index resource Definition
	IndexClassification
}

// IndexesClientListLatestResponse contains the response from method IndexesClient.NewListLatestPager.
type IndexesClientListLatestResponse struct {
	// Paged collection of Index items
	PagedIndex
}

// IndexesClientListVersionsResponse contains the response from method IndexesClient.NewListVersionsPager.
type IndexesClientListVersionsResponse struct {
	// Paged collection of Index items
	PagedIndex
}

// InsightsClientGenerateResponse contains the response from method InsightsClient.Generate.
type InsightsClientGenerateResponse struct {
	// The response body for cluster insights.
	Insight
}

// InsightsClientGetResponse contains the response from method InsightsClient.Get.
type InsightsClientGetResponse struct {
	// The response body for cluster insights.
	Insight
}

// InsightsClientListResponse contains the response from method InsightsClient.NewListPager.
type InsightsClientListResponse struct {
	// Paged collection of Insight items
	PagedInsight
}

// MemoryStoresClientCreateMemoryResponse contains the response from method MemoryStoresClient.CreateMemory.
type MemoryStoresClientCreateMemoryResponse struct {
	// A single memory item stored in the memory store, containing content and metadata.
	MemoryItemClassification
}

// MemoryStoresClientCreateMemoryStoreResponse contains the response from method MemoryStoresClient.CreateMemoryStore.
type MemoryStoresClientCreateMemoryStoreResponse struct {
	// A memory store that can store and retrieve user memories.
	MemoryStoreObject
}

// MemoryStoresClientDeleteMemoryResponse contains the response from method MemoryStoresClient.DeleteMemory.
type MemoryStoresClientDeleteMemoryResponse struct {
	// Response for deleting a memory item from a memory store.
	DeleteMemoryResponse
}

// MemoryStoresClientDeleteMemoryStoreResponse contains the response from method MemoryStoresClient.DeleteMemoryStore.
type MemoryStoresClientDeleteMemoryStoreResponse struct {
	DeleteMemoryStoreResult
}

// MemoryStoresClientDeleteScopeResponse contains the response from method MemoryStoresClient.DeleteScope.
type MemoryStoresClientDeleteScopeResponse struct {
	// Response for deleting memories from a scope.
	MemoryStoreDeleteScopeResult
}

// MemoryStoresClientGetMemoryResponse contains the response from method MemoryStoresClient.GetMemory.
type MemoryStoresClientGetMemoryResponse struct {
	// A single memory item stored in the memory store, containing content and metadata.
	MemoryItemClassification
}

// MemoryStoresClientGetMemoryStoreResponse contains the response from method MemoryStoresClient.GetMemoryStore.
type MemoryStoresClientGetMemoryStoreResponse struct {
	// A memory store that can store and retrieve user memories.
	MemoryStoreObject
}

// MemoryStoresClientGetUpdateResultResponse contains the response from method MemoryStoresClient.GetUpdateResult.
type MemoryStoresClientGetUpdateResultResponse struct {
	// Provides the status of a memory store update operation.
	MemoryStoreUpdateResult
}

// MemoryStoresClientListMemoriesResponse contains the response from method MemoryStoresClient.NewListMemoriesPager.
type MemoryStoresClientListMemoriesResponse struct {
	// The response data for a requested list of items.
	AgentsPagedResultMemoryItem
}

// MemoryStoresClientListMemoryStoresResponse contains the response from method MemoryStoresClient.NewListMemoryStoresPager.
type MemoryStoresClientListMemoryStoresResponse struct {
	// The response data for a requested list of items.
	AgentsPagedResultMemoryStoreObject
}

// MemoryStoresClientSearchMemoriesResponse contains the response from method MemoryStoresClient.SearchMemories.
type MemoryStoresClientSearchMemoriesResponse struct {
	// Memory search response.
	MemoryStoreSearchResult
}

// MemoryStoresClientUpdateMemoriesResponse contains the response from method MemoryStoresClient.BeginUpdateMemories.
type MemoryStoresClientUpdateMemoriesResponse struct {
	// Memory update result.
	MemoryStoreUpdateCompletedResult
}

// MemoryStoresClientUpdateMemoryResponse contains the response from method MemoryStoresClient.UpdateMemory.
type MemoryStoresClientUpdateMemoryResponse struct {
	// A single memory item stored in the memory store, containing content and metadata.
	MemoryItemClassification
}

// MemoryStoresClientUpdateMemoryStoreResponse contains the response from method MemoryStoresClient.UpdateMemoryStore.
type MemoryStoresClientUpdateMemoryStoreResponse struct {
	// A memory store that can store and retrieve user memories.
	MemoryStoreObject
}

// RedTeamsClientCreateResponse contains the response from method RedTeamsClient.Create.
type RedTeamsClientCreateResponse struct {
	// Red team details.
	RedTeam
}

// RedTeamsClientGetResponse contains the response from method RedTeamsClient.Get.
type RedTeamsClientGetResponse struct {
	// Red team details.
	RedTeam
}

// RedTeamsClientListResponse contains the response from method RedTeamsClient.NewListPager.
type RedTeamsClientListResponse struct {
	// Paged collection of RedTeam items
	PagedRedTeam
}

// SchedulesClientCreateOrUpdateResponse contains the response from method SchedulesClient.CreateOrUpdate.
type SchedulesClientCreateOrUpdateResponse struct {
	// Schedule model.
	Schedule
}

// SchedulesClientDeleteResponse contains the response from method SchedulesClient.Delete.
type SchedulesClientDeleteResponse struct {
	// placeholder for future response values
}

// SchedulesClientGetResponse contains the response from method SchedulesClient.Get.
type SchedulesClientGetResponse struct {
	// Schedule model.
	Schedule
}

// SchedulesClientGetRunResponse contains the response from method SchedulesClient.GetRun.
type SchedulesClientGetRunResponse struct {
	// Schedule run model.
	ScheduleRun
}

// SchedulesClientListResponse contains the response from method SchedulesClient.NewListPager.
type SchedulesClientListResponse struct {
	// Paged collection of Schedule items
	PagedSchedule
}

// SchedulesClientListRunsResponse contains the response from method SchedulesClient.NewListRunsPager.
type SchedulesClientListRunsResponse struct {
	// Paged collection of ScheduleRun items
	PagedScheduleRun
}

// ToolboxesClientCreateToolboxVersionResponse contains the response from method ToolboxesClient.CreateToolboxVersion.
type ToolboxesClientCreateToolboxVersionResponse struct {
	// A specific version of a toolbox.
	ToolboxVersionObject
}

// ToolboxesClientDeleteToolboxResponse contains the response from method ToolboxesClient.DeleteToolbox.
type ToolboxesClientDeleteToolboxResponse struct {
	// placeholder for future response values
}

// ToolboxesClientDeleteToolboxVersionResponse contains the response from method ToolboxesClient.DeleteToolboxVersion.
type ToolboxesClientDeleteToolboxVersionResponse struct {
	// placeholder for future response values
}

// ToolboxesClientGetToolboxResponse contains the response from method ToolboxesClient.GetToolbox.
type ToolboxesClientGetToolboxResponse struct {
	// A toolbox that stores reusable tool definitions for agents.
	ToolboxObject
}

// ToolboxesClientGetToolboxVersionResponse contains the response from method ToolboxesClient.GetToolboxVersion.
type ToolboxesClientGetToolboxVersionResponse struct {
	// A specific version of a toolbox.
	ToolboxVersionObject
}

// ToolboxesClientListToolboxVersionsResponse contains the response from method ToolboxesClient.NewListToolboxVersionsPager.
type ToolboxesClientListToolboxVersionsResponse struct {
	// The response data for a requested list of items.
	AgentsPagedResultToolboxVersionObject
}

// ToolboxesClientListToolboxesResponse contains the response from method ToolboxesClient.NewListToolboxesPager.
type ToolboxesClientListToolboxesResponse struct {
	// The response data for a requested list of items.
	AgentsPagedResultToolboxObject
}

// ToolboxesClientUpdateToolboxResponse contains the response from method ToolboxesClient.UpdateToolbox.
type ToolboxesClientUpdateToolboxResponse struct {
	// A toolbox that stores reusable tool definitions for agents.
	ToolboxObject
}

// connectionsClientgetResponse contains the response from method ConnectionsClient.get.
type connectionsClientgetResponse struct {
	// Response from the list and get connections operations
	Connection

	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string
}

// connectionsClientgetWithCredentialsResponse contains the response from method ConnectionsClient.getWithCredentials.
type connectionsClientgetWithCredentialsResponse struct {
	// Response from the list and get connections operations
	Connection

	// An opaque, globally-unique, client-generated string identifier for the request.
	ClientRequestID *string
}
