// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// RedTeamsClient contains the methods for the RedTeams group.
// Don't use this type directly, use [Client.NewRedTeamsClient] instead.
//
// Generated from API version v1
type RedTeamsClient struct {
	internal *azcore.Client
	endpoint string
}

// Create - Create a redteam run
//
// Submits a new redteam run for execution with the provided configuration.
// If the operation fails it returns an *azcore.ResponseError type.
//   - redTeam - Redteam to be run
//   - options - RedTeamsClientCreateOptions contains the optional parameters for the RedTeamsClient.Create method.
func (client *RedTeamsClient) Create(ctx context.Context, redTeam RedTeam, options *RedTeamsClientCreateOptions) (RedTeamsClientCreateResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "RedTeamsClient.Create", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createCreateRequest(ctx, redTeam, options)
	if err != nil {
		return RedTeamsClientCreateResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return RedTeamsClientCreateResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusCreated) {
		err = runtime.NewResponseError(httpResp)
		return RedTeamsClientCreateResponse{}, err
	}
	resp, err := client.createHandleResponse(httpResp)
	return resp, err
}

// createCreateRequest creates the Create request.
func (client *RedTeamsClient) createCreateRequest(ctx context.Context, redTeam RedTeam, _ *RedTeamsClientCreateOptions) (*policy.Request, error) {
	urlPath := "/redTeams/runs:run"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"RedTeams=V1Preview"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, redTeam); err != nil {
		return nil, err
	}
	return req, nil
}

// createHandleResponse handles the Create response.
func (client *RedTeamsClient) createHandleResponse(resp *http.Response) (RedTeamsClientCreateResponse, error) {
	result := RedTeamsClientCreateResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.RedTeam); err != nil {
		return RedTeamsClientCreateResponse{}, err
	}
	return result, nil
}

// Get - Get a redteam
//
// Retrieves the specified redteam and its configuration.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - Identifier of the red team run.
//   - options - RedTeamsClientGetOptions contains the optional parameters for the RedTeamsClient.Get method.
func (client *RedTeamsClient) Get(ctx context.Context, name string, options *RedTeamsClientGetOptions) (RedTeamsClientGetResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "RedTeamsClient.Get", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, name, options)
	if err != nil {
		return RedTeamsClientGetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return RedTeamsClientGetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return RedTeamsClientGetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the Get request.
func (client *RedTeamsClient) getCreateRequest(ctx context.Context, name string, _ *RedTeamsClientGetOptions) (*policy.Request, error) {
	urlPath := "/redTeams/runs/{name}"
	if name == "" {
		return nil, errors.New("parameter name cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{name}", url.PathEscape(name))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"RedTeams=V1Preview"}
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *RedTeamsClient) getHandleResponse(resp *http.Response) (RedTeamsClientGetResponse, error) {
	result := RedTeamsClientGetResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.RedTeam); err != nil {
		return RedTeamsClientGetResponse{}, err
	}
	return result, nil
}

// NewListPager - List redteams
//
// Returns the redteams available in the current project.
//   - options - RedTeamsClientListOptions contains the optional parameters for the RedTeamsClient.NewListPager method.
func (client *RedTeamsClient) NewListPager(options *RedTeamsClientListOptions) *runtime.Pager[RedTeamsClientListResponse] {
	return runtime.NewPager(runtime.PagingHandler[RedTeamsClientListResponse]{
		More: func(page RedTeamsClientListResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *RedTeamsClientListResponse) (RedTeamsClientListResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listCreateRequest(ctx, options)
			}, nil)
			if err != nil {
				return RedTeamsClientListResponse{}, err
			}
			return client.listHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listCreateRequest creates the List request.
func (client *RedTeamsClient) listCreateRequest(ctx context.Context, _ *RedTeamsClientListOptions) (*policy.Request, error) {
	urlPath := "/redTeams/runs"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"RedTeams=V1Preview"}
	return req, nil
}

// listHandleResponse handles the List response.
func (client *RedTeamsClient) listHandleResponse(resp *http.Response) (RedTeamsClientListResponse, error) {
	result := RedTeamsClientListResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedRedTeam); err != nil {
		return RedTeamsClientListResponse{}, err
	}
	return result, nil
}
