// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

// UnmarshalJSON implements the json.Unmarshaller interface for type DatasetsClientCreateOrUpdateVersionResponse.
func (d *DatasetsClientCreateOrUpdateVersionResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalDatasetVersionClassification(data)
	if err != nil {
		return err
	}
	d.DatasetVersionClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type DatasetsClientGetVersionResponse.
func (d *DatasetsClientGetVersionResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalDatasetVersionClassification(data)
	if err != nil {
		return err
	}
	d.DatasetVersionClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type DeploymentsClientGetResponse.
func (d *DeploymentsClientGetResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalDeploymentClassification(data)
	if err != nil {
		return err
	}
	d.DeploymentClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type IndexesClientCreateOrUpdateVersionResponse.
func (i *IndexesClientCreateOrUpdateVersionResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalIndexClassification(data)
	if err != nil {
		return err
	}
	i.IndexClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type IndexesClientGetVersionResponse.
func (i *IndexesClientGetVersionResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalIndexClassification(data)
	if err != nil {
		return err
	}
	i.IndexClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type MemoryStoresClientCreateMemoryResponse.
func (m *MemoryStoresClientCreateMemoryResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalMemoryItemClassification(data)
	if err != nil {
		return err
	}
	m.MemoryItemClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type MemoryStoresClientGetMemoryResponse.
func (m *MemoryStoresClientGetMemoryResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalMemoryItemClassification(data)
	if err != nil {
		return err
	}
	m.MemoryItemClassification = res
	return nil
}

// UnmarshalJSON implements the json.Unmarshaller interface for type MemoryStoresClientUpdateMemoryResponse.
func (m *MemoryStoresClientUpdateMemoryResponse) UnmarshalJSON(data []byte) error {
	res, err := unmarshalMemoryItemClassification(data)
	if err != nil {
		return err
	}
	m.MemoryItemClassification = res
	return nil
}
