// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// SchedulesClient contains the methods for the Schedules group.
// Don't use this type directly, use [Client.NewSchedulesClient] instead.
//
// Generated from API version v1
type SchedulesClient struct {
	internal *azcore.Client
	endpoint string
}

// CreateOrUpdate - Create or update a schedule
//
// Creates a new schedule or updates an existing schedule with the supplied definition.
// If the operation fails it returns an *azcore.ResponseError type.
//   - scheduleID - Identifier of the schedule.
//   - schedule - The resource instance.
//   - options - SchedulesClientCreateOrUpdateOptions contains the optional parameters for the SchedulesClient.CreateOrUpdate
//     method.
func (client *SchedulesClient) CreateOrUpdate(ctx context.Context, scheduleID string, schedule Schedule, options *SchedulesClientCreateOrUpdateOptions) (SchedulesClientCreateOrUpdateResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "SchedulesClient.CreateOrUpdate", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createOrUpdateCreateRequest(ctx, scheduleID, schedule, options)
	if err != nil {
		return SchedulesClientCreateOrUpdateResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SchedulesClientCreateOrUpdateResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK, http.StatusCreated) {
		err = runtime.NewResponseError(httpResp)
		return SchedulesClientCreateOrUpdateResponse{}, err
	}
	resp, err := client.createOrUpdateHandleResponse(httpResp)
	return resp, err
}

// createOrUpdateCreateRequest creates the CreateOrUpdate request.
func (client *SchedulesClient) createOrUpdateCreateRequest(ctx context.Context, scheduleID string, schedule Schedule, _ *SchedulesClientCreateOrUpdateOptions) (*policy.Request, error) {
	urlPath := "/schedules/{id}"
	if scheduleID == "" {
		return nil, errors.New("parameter scheduleID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{id}", url.PathEscape(scheduleID))
	req, err := runtime.NewRequest(ctx, http.MethodPut, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Schedules=V1Preview"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, schedule); err != nil {
		return nil, err
	}
	return req, nil
}

// createOrUpdateHandleResponse handles the CreateOrUpdate response.
func (client *SchedulesClient) createOrUpdateHandleResponse(resp *http.Response) (SchedulesClientCreateOrUpdateResponse, error) {
	result := SchedulesClientCreateOrUpdateResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.Schedule); err != nil {
		return SchedulesClientCreateOrUpdateResponse{}, err
	}
	return result, nil
}

// Delete - Delete a schedule
//
// Deletes the specified schedule resource.
// If the operation fails it returns an *azcore.ResponseError type.
//   - scheduleID - Identifier of the schedule.
//   - options - SchedulesClientDeleteOptions contains the optional parameters for the SchedulesClient.Delete method.
func (client *SchedulesClient) Delete(ctx context.Context, scheduleID string, options *SchedulesClientDeleteOptions) (SchedulesClientDeleteResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "SchedulesClient.Delete", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteCreateRequest(ctx, scheduleID, options)
	if err != nil {
		return SchedulesClientDeleteResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SchedulesClientDeleteResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusNoContent) {
		err = runtime.NewResponseError(httpResp)
		return SchedulesClientDeleteResponse{}, err
	}
	return SchedulesClientDeleteResponse{}, nil
}

// deleteCreateRequest creates the Delete request.
func (client *SchedulesClient) deleteCreateRequest(ctx context.Context, scheduleID string, _ *SchedulesClientDeleteOptions) (*policy.Request, error) {
	urlPath := "/schedules/{id}"
	if scheduleID == "" {
		return nil, errors.New("parameter scheduleID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{id}", url.PathEscape(scheduleID))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Foundry-Features"] = []string{"Schedules=V1Preview"}
	return req, nil
}

// Get - Get a schedule
//
// Retrieves the specified schedule resource.
// If the operation fails it returns an *azcore.ResponseError type.
//   - scheduleID - Identifier of the schedule.
//   - options - SchedulesClientGetOptions contains the optional parameters for the SchedulesClient.Get method.
func (client *SchedulesClient) Get(ctx context.Context, scheduleID string, options *SchedulesClientGetOptions) (SchedulesClientGetResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "SchedulesClient.Get", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, scheduleID, options)
	if err != nil {
		return SchedulesClientGetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SchedulesClientGetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return SchedulesClientGetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the Get request.
func (client *SchedulesClient) getCreateRequest(ctx context.Context, scheduleID string, _ *SchedulesClientGetOptions) (*policy.Request, error) {
	urlPath := "/schedules/{id}"
	if scheduleID == "" {
		return nil, errors.New("parameter scheduleID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{id}", url.PathEscape(scheduleID))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Schedules=V1Preview"}
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *SchedulesClient) getHandleResponse(resp *http.Response) (SchedulesClientGetResponse, error) {
	result := SchedulesClientGetResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.Schedule); err != nil {
		return SchedulesClientGetResponse{}, err
	}
	return result, nil
}

// GetRun - Get a schedule run
//
// Retrieves the specified run for a schedule.
// If the operation fails it returns an *azcore.ResponseError type.
//   - scheduleID - The unique identifier of the schedule.
//   - runID - The unique identifier of the schedule run.
//   - options - SchedulesClientGetRunOptions contains the optional parameters for the SchedulesClient.GetRun method.
func (client *SchedulesClient) GetRun(ctx context.Context, scheduleID string, runID string, options *SchedulesClientGetRunOptions) (SchedulesClientGetRunResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "SchedulesClient.GetRun", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getRunCreateRequest(ctx, scheduleID, runID, options)
	if err != nil {
		return SchedulesClientGetRunResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SchedulesClientGetRunResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return SchedulesClientGetRunResponse{}, err
	}
	resp, err := client.getRunHandleResponse(httpResp)
	return resp, err
}

// getRunCreateRequest creates the GetRun request.
func (client *SchedulesClient) getRunCreateRequest(ctx context.Context, scheduleID string, runID string, _ *SchedulesClientGetRunOptions) (*policy.Request, error) {
	urlPath := "/schedules/{schedule_id}/runs/{run_id}"
	if scheduleID == "" {
		return nil, errors.New("parameter scheduleID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{schedule_id}", url.PathEscape(scheduleID))
	if runID == "" {
		return nil, errors.New("parameter runID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{run_id}", url.PathEscape(runID))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Schedules=V1Preview"}
	return req, nil
}

// getRunHandleResponse handles the GetRun response.
func (client *SchedulesClient) getRunHandleResponse(resp *http.Response) (SchedulesClientGetRunResponse, error) {
	result := SchedulesClientGetRunResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.ScheduleRun); err != nil {
		return SchedulesClientGetRunResponse{}, err
	}
	return result, nil
}

// NewListPager - List schedules
//
// Returns schedules that match the supplied type and enabled filters.
//   - options - SchedulesClientListOptions contains the optional parameters for the SchedulesClient.NewListPager method.
func (client *SchedulesClient) NewListPager(options *SchedulesClientListOptions) *runtime.Pager[SchedulesClientListResponse] {
	return runtime.NewPager(runtime.PagingHandler[SchedulesClientListResponse]{
		More: func(page SchedulesClientListResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *SchedulesClientListResponse) (SchedulesClientListResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listCreateRequest(ctx, options)
			}, nil)
			if err != nil {
				return SchedulesClientListResponse{}, err
			}
			return client.listHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listCreateRequest creates the List request.
func (client *SchedulesClient) listCreateRequest(ctx context.Context, options *SchedulesClientListOptions) (*policy.Request, error) {
	urlPath := "/schedules"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Enabled != nil {
		reqQP.Set("enabled", strconv.FormatBool(*options.Enabled))
	}
	if options != nil && options.Type != nil {
		reqQP.Set("type", string(*options.Type))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Schedules=V1Preview"}
	return req, nil
}

// listHandleResponse handles the List response.
func (client *SchedulesClient) listHandleResponse(resp *http.Response) (SchedulesClientListResponse, error) {
	result := SchedulesClientListResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedSchedule); err != nil {
		return SchedulesClientListResponse{}, err
	}
	return result, nil
}

// NewListRunsPager - List schedule runs
//
// Returns schedule runs that match the supplied filters.
//   - scheduleID - Identifier of the schedule.
//   - options - SchedulesClientListRunsOptions contains the optional parameters for the SchedulesClient.NewListRunsPager method.
func (client *SchedulesClient) NewListRunsPager(scheduleID string, options *SchedulesClientListRunsOptions) *runtime.Pager[SchedulesClientListRunsResponse] {
	return runtime.NewPager(runtime.PagingHandler[SchedulesClientListRunsResponse]{
		More: func(page SchedulesClientListRunsResponse) bool {
			return page.NextLink != nil && len(*page.NextLink) > 0
		},
		Fetcher: func(ctx context.Context, page *SchedulesClientListRunsResponse) (SchedulesClientListRunsResponse, error) {
			nextLink := ""
			if page != nil {
				nextLink = *page.NextLink
			}
			resp, err := runtime.FetcherForNextLink(ctx, client.internal.Pipeline(), nextLink, func(ctx context.Context) (*policy.Request, error) {
				return client.listRunsCreateRequest(ctx, scheduleID, options)
			}, nil)
			if err != nil {
				return SchedulesClientListRunsResponse{}, err
			}
			return client.listRunsHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listRunsCreateRequest creates the ListRuns request.
func (client *SchedulesClient) listRunsCreateRequest(ctx context.Context, scheduleID string, options *SchedulesClientListRunsOptions) (*policy.Request, error) {
	urlPath := "/schedules/{id}/runs"
	if scheduleID == "" {
		return nil, errors.New("parameter scheduleID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{id}", url.PathEscape(scheduleID))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Enabled != nil {
		reqQP.Set("enabled", strconv.FormatBool(*options.Enabled))
	}
	if options != nil && options.Type != nil {
		reqQP.Set("type", string(*options.Type))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Foundry-Features"] = []string{"Schedules=V1Preview"}
	return req, nil
}

// listRunsHandleResponse handles the ListRuns response.
func (client *SchedulesClient) listRunsHandleResponse(resp *http.Response) (SchedulesClientListRunsResponse, error) {
	result := SchedulesClientListRunsResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.PagedScheduleRun); err != nil {
		return SchedulesClientListRunsResponse{}, err
	}
	return result, nil
}
