// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azaiprojects

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// ToolboxesClient contains the methods for the Toolboxes group.
// Don't use this type directly, use [Client.NewToolboxesClient] instead.
//
// Generated from API version v1
type ToolboxesClient struct {
	internal *azcore.Client
	endpoint string
}

// CreateToolboxVersion - Create a new version of a toolbox
//
// Creates a new toolbox version, provisioning the toolbox itself if it does not already exist.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the toolbox. If the toolbox does not exist, it will be created.
//   - tools - The list of tools to include in this version.
//   - options - ToolboxesClientCreateToolboxVersionOptions contains the optional parameters for the ToolboxesClient.CreateToolboxVersion
//     method.
func (client *ToolboxesClient) CreateToolboxVersion(ctx context.Context, name string, tools []ToolboxToolClassification, options *ToolboxesClientCreateToolboxVersionOptions) (ToolboxesClientCreateToolboxVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "ToolboxesClient.CreateToolboxVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.createToolboxVersionCreateRequest(ctx, name, tools, options)
	if err != nil {
		return ToolboxesClientCreateToolboxVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return ToolboxesClientCreateToolboxVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return ToolboxesClientCreateToolboxVersionResponse{}, err
	}
	resp, err := client.createToolboxVersionHandleResponse(httpResp)
	return resp, err
}

// createToolboxVersionCreateRequest creates the CreateToolboxVersion request.
func (client *ToolboxesClient) createToolboxVersionCreateRequest(ctx context.Context, name string, tools []ToolboxToolClassification, options *ToolboxesClientCreateToolboxVersionOptions) (*policy.Request, error) {
	urlPath := "/toolboxes/{name}/versions"
	var err error
	urlPath, err = replaceToolboxNamePathParameter(client.endpoint, urlPath, name)
	if err != nil {
		return nil, err
	}
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	body := struct {
		Description *string                      `json:"description"`
		Metadata    map[string]*string           `json:"metadata"`
		Tools       []ToolboxToolClassification  `json:"tools"`
		Skills      []ToolboxSkillClassification `json:"skills"`
		Policies    *ToolboxPolicies             `json:"policies"`
	}{
		Tools: tools,
	}
	if options != nil && options.Description != nil {
		body.Description = options.Description
	}
	if options != nil && options.Metadata != nil {
		body.Metadata = options.Metadata
	}
	if options != nil && options.Skills != nil {
		body.Skills = options.Skills
	}
	if options != nil && options.Policies != nil {
		body.Policies = options.Policies
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// createToolboxVersionHandleResponse handles the CreateToolboxVersion response.
func (client *ToolboxesClient) createToolboxVersionHandleResponse(resp *http.Response) (ToolboxesClientCreateToolboxVersionResponse, error) {
	result := ToolboxesClientCreateToolboxVersionResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.ToolboxVersionObject); err != nil {
		return ToolboxesClientCreateToolboxVersionResponse{}, err
	}
	return result, nil
}

// DeleteToolbox - Delete a toolbox
//
// Removes the specified toolbox along with all of its versions.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the toolbox to delete.
//   - options - ToolboxesClientDeleteToolboxOptions contains the optional parameters for the ToolboxesClient.DeleteToolbox method.
func (client *ToolboxesClient) DeleteToolbox(ctx context.Context, name string, options *ToolboxesClientDeleteToolboxOptions) (ToolboxesClientDeleteToolboxResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "ToolboxesClient.DeleteToolbox", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteToolboxCreateRequest(ctx, name, options)
	if err != nil {
		return ToolboxesClientDeleteToolboxResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return ToolboxesClientDeleteToolboxResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusNoContent) {
		err = runtime.NewResponseError(httpResp)
		return ToolboxesClientDeleteToolboxResponse{}, err
	}
	return ToolboxesClientDeleteToolboxResponse{}, nil
}

// deleteToolboxCreateRequest creates the DeleteToolbox request.
func (client *ToolboxesClient) deleteToolboxCreateRequest(ctx context.Context, name string, _ *ToolboxesClientDeleteToolboxOptions) (*policy.Request, error) {
	urlPath := "/toolboxes/{name}"
	var err error
	urlPath, err = replaceToolboxNamePathParameter(client.endpoint, urlPath, name)
	if err != nil {
		return nil, err
	}
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	return req, nil
}

// DeleteToolboxVersion - Delete a specific version of a toolbox
//
// Removes the specified version of a toolbox.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the toolbox.
//   - version - The version identifier to delete.
//   - options - ToolboxesClientDeleteToolboxVersionOptions contains the optional parameters for the ToolboxesClient.DeleteToolboxVersion
//     method.
func (client *ToolboxesClient) DeleteToolboxVersion(ctx context.Context, name string, version string, options *ToolboxesClientDeleteToolboxVersionOptions) (ToolboxesClientDeleteToolboxVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "ToolboxesClient.DeleteToolboxVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.deleteToolboxVersionCreateRequest(ctx, name, version, options)
	if err != nil {
		return ToolboxesClientDeleteToolboxVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return ToolboxesClientDeleteToolboxVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusNoContent) {
		err = runtime.NewResponseError(httpResp)
		return ToolboxesClientDeleteToolboxVersionResponse{}, err
	}
	return ToolboxesClientDeleteToolboxVersionResponse{}, nil
}

// deleteToolboxVersionCreateRequest creates the DeleteToolboxVersion request.
func (client *ToolboxesClient) deleteToolboxVersionCreateRequest(ctx context.Context, name string, version string, _ *ToolboxesClientDeleteToolboxVersionOptions) (*policy.Request, error) {
	urlPath := "/toolboxes/{name}/versions/{version}"
	var err error
	urlPath, err = replaceToolboxNamePathParameter(client.endpoint, urlPath, name)
	if err != nil {
		return nil, err
	}
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodDelete, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	return req, nil
}

// GetToolbox - Retrieve a toolbox
//
// Retrieves the specified toolbox and its current configuration.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the toolbox to retrieve.
//   - options - ToolboxesClientGetToolboxOptions contains the optional parameters for the ToolboxesClient.GetToolbox method.
func (client *ToolboxesClient) GetToolbox(ctx context.Context, name string, options *ToolboxesClientGetToolboxOptions) (ToolboxesClientGetToolboxResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "ToolboxesClient.GetToolbox", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getToolboxCreateRequest(ctx, name, options)
	if err != nil {
		return ToolboxesClientGetToolboxResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return ToolboxesClientGetToolboxResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return ToolboxesClientGetToolboxResponse{}, err
	}
	resp, err := client.getToolboxHandleResponse(httpResp)
	return resp, err
}

// getToolboxCreateRequest creates the GetToolbox request.
func (client *ToolboxesClient) getToolboxCreateRequest(ctx context.Context, name string, _ *ToolboxesClientGetToolboxOptions) (*policy.Request, error) {
	urlPath := "/toolboxes/{name}"
	var err error
	urlPath, err = replaceToolboxNamePathParameter(client.endpoint, urlPath, name)
	if err != nil {
		return nil, err
	}
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// getToolboxHandleResponse handles the GetToolbox response.
func (client *ToolboxesClient) getToolboxHandleResponse(resp *http.Response) (ToolboxesClientGetToolboxResponse, error) {
	result := ToolboxesClientGetToolboxResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.ToolboxObject); err != nil {
		return ToolboxesClientGetToolboxResponse{}, err
	}
	return result, nil
}

// GetToolboxVersion - Retrieve a specific version of a toolbox
//
// Retrieves the specified version of a toolbox by name and version identifier.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the toolbox.
//   - version - The version identifier to retrieve.
//   - options - ToolboxesClientGetToolboxVersionOptions contains the optional parameters for the ToolboxesClient.GetToolboxVersion
//     method.
func (client *ToolboxesClient) GetToolboxVersion(ctx context.Context, name string, version string, options *ToolboxesClientGetToolboxVersionOptions) (ToolboxesClientGetToolboxVersionResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "ToolboxesClient.GetToolboxVersion", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getToolboxVersionCreateRequest(ctx, name, version, options)
	if err != nil {
		return ToolboxesClientGetToolboxVersionResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return ToolboxesClientGetToolboxVersionResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return ToolboxesClientGetToolboxVersionResponse{}, err
	}
	resp, err := client.getToolboxVersionHandleResponse(httpResp)
	return resp, err
}

// getToolboxVersionCreateRequest creates the GetToolboxVersion request.
func (client *ToolboxesClient) getToolboxVersionCreateRequest(ctx context.Context, name string, version string, _ *ToolboxesClientGetToolboxVersionOptions) (*policy.Request, error) {
	urlPath := "/toolboxes/{name}/versions/{version}"
	var err error
	urlPath, err = replaceToolboxNamePathParameter(client.endpoint, urlPath, name)
	if err != nil {
		return nil, err
	}
	if version == "" {
		return nil, errors.New("parameter version cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{version}", url.PathEscape(version))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// getToolboxVersionHandleResponse handles the GetToolboxVersion response.
func (client *ToolboxesClient) getToolboxVersionHandleResponse(resp *http.Response) (ToolboxesClientGetToolboxVersionResponse, error) {
	result := ToolboxesClientGetToolboxVersionResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.ToolboxVersionObject); err != nil {
		return ToolboxesClientGetToolboxVersionResponse{}, err
	}
	return result, nil
}

// NewListToolboxVersionsPager - List toolbox versions
//
// Returns the available versions for the specified toolbox.
//   - name - The name of the toolbox to list versions for.
//   - options - ToolboxesClientListToolboxVersionsOptions contains the optional parameters for the ToolboxesClient.NewListToolboxVersionsPager
//     method.
func (client *ToolboxesClient) NewListToolboxVersionsPager(name string, options *ToolboxesClientListToolboxVersionsOptions) *runtime.Pager[ToolboxesClientListToolboxVersionsResponse] {
	return runtime.NewPager(runtime.PagingHandler[ToolboxesClientListToolboxVersionsResponse]{
		More: func(page ToolboxesClientListToolboxVersionsResponse) bool {
			return page.LastID != nil && len(*page.LastID) > 0
		},
		Fetcher: func(ctx context.Context, page *ToolboxesClientListToolboxVersionsResponse) (ToolboxesClientListToolboxVersionsResponse, error) {
			nextOpts := ToolboxesClientListToolboxVersionsOptions{}
			if options != nil {
				nextOpts = *options
			}
			if page != nil {
				nextOpts.After = page.LastID
			}
			req, err := client.listToolboxVersionsCreateRequest(ctx, name, &nextOpts)
			if err != nil {
				return ToolboxesClientListToolboxVersionsResponse{}, err
			}
			resp, err := client.internal.Pipeline().Do(req)
			if err != nil {
				return ToolboxesClientListToolboxVersionsResponse{}, err
			}
			if !runtime.HasStatusCode(resp, http.StatusOK) {
				return ToolboxesClientListToolboxVersionsResponse{}, runtime.NewResponseError(resp)
			}
			return client.listToolboxVersionsHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listToolboxVersionsCreateRequest creates the ListToolboxVersions request.
func (client *ToolboxesClient) listToolboxVersionsCreateRequest(ctx context.Context, name string, options *ToolboxesClientListToolboxVersionsOptions) (*policy.Request, error) {
	urlPath := "/toolboxes/{name}/versions"
	var err error
	urlPath, err = replaceToolboxNamePathParameter(client.endpoint, urlPath, name)
	if err != nil {
		return nil, err
	}
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.After != nil {
		reqQP.Set("after", *options.After)
	}
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Before != nil {
		reqQP.Set("before", *options.Before)
	}
	if options != nil && options.Limit != nil {
		reqQP.Set("limit", strconv.FormatInt(int64(*options.Limit), 10))
	}
	if options != nil && options.Order != nil {
		reqQP.Set("order", string(*options.Order))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// listToolboxVersionsHandleResponse handles the ListToolboxVersions response.
func (client *ToolboxesClient) listToolboxVersionsHandleResponse(resp *http.Response) (ToolboxesClientListToolboxVersionsResponse, error) {
	result := ToolboxesClientListToolboxVersionsResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.AgentsPagedResultToolboxVersionObject); err != nil {
		return ToolboxesClientListToolboxVersionsResponse{}, err
	}
	return result, nil
}

// NewListToolboxesPager - List toolboxes
//
// Returns the toolboxes available in the current project.
//   - options - ToolboxesClientListToolboxesOptions contains the optional parameters for the ToolboxesClient.NewListToolboxesPager
//     method.
func (client *ToolboxesClient) NewListToolboxesPager(options *ToolboxesClientListToolboxesOptions) *runtime.Pager[ToolboxesClientListToolboxesResponse] {
	return runtime.NewPager(runtime.PagingHandler[ToolboxesClientListToolboxesResponse]{
		More: func(page ToolboxesClientListToolboxesResponse) bool {
			return page.LastID != nil && len(*page.LastID) > 0
		},
		Fetcher: func(ctx context.Context, page *ToolboxesClientListToolboxesResponse) (ToolboxesClientListToolboxesResponse, error) {
			nextOpts := ToolboxesClientListToolboxesOptions{}
			if options != nil {
				nextOpts = *options
			}
			if page != nil {
				nextOpts.After = page.LastID
			}
			req, err := client.listToolboxesCreateRequest(ctx, &nextOpts)
			if err != nil {
				return ToolboxesClientListToolboxesResponse{}, err
			}
			resp, err := client.internal.Pipeline().Do(req)
			if err != nil {
				return ToolboxesClientListToolboxesResponse{}, err
			}
			if !runtime.HasStatusCode(resp, http.StatusOK) {
				return ToolboxesClientListToolboxesResponse{}, runtime.NewResponseError(resp)
			}
			return client.listToolboxesHandleResponse(resp)
		},
		Tracer: client.internal.Tracer(),
	})
}

// listToolboxesCreateRequest creates the ListToolboxes request.
func (client *ToolboxesClient) listToolboxesCreateRequest(ctx context.Context, options *ToolboxesClientListToolboxesOptions) (*policy.Request, error) {
	urlPath := "/toolboxes"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	if options != nil && options.After != nil {
		reqQP.Set("after", *options.After)
	}
	reqQP.Set("api-version", versionV1)
	if options != nil && options.Before != nil {
		reqQP.Set("before", *options.Before)
	}
	if options != nil && options.Limit != nil {
		reqQP.Set("limit", strconv.FormatInt(int64(*options.Limit), 10))
	}
	if options != nil && options.Order != nil {
		reqQP.Set("order", string(*options.Order))
	}
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// listToolboxesHandleResponse handles the ListToolboxes response.
func (client *ToolboxesClient) listToolboxesHandleResponse(resp *http.Response) (ToolboxesClientListToolboxesResponse, error) {
	result := ToolboxesClientListToolboxesResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.AgentsPagedResultToolboxObject); err != nil {
		return ToolboxesClientListToolboxesResponse{}, err
	}
	return result, nil
}

// UpdateToolbox - Update a toolbox to point to a specific version
//
// Updates the toolbox's default version pointer to the specified version.
// If the operation fails it returns an *azcore.ResponseError type.
//   - name - The name of the toolbox to update.
//   - defaultVersion - The version identifier that the toolbox should point to. When set, the toolbox's default version will
//     resolve to this version instead of the latest.
//   - options - ToolboxesClientUpdateToolboxOptions contains the optional parameters for the ToolboxesClient.UpdateToolbox method.
func (client *ToolboxesClient) UpdateToolbox(ctx context.Context, name string, defaultVersion string, options *ToolboxesClientUpdateToolboxOptions) (ToolboxesClientUpdateToolboxResponse, error) {
	var err error
	ctx, endSpan := runtime.StartSpan(ctx, "ToolboxesClient.UpdateToolbox", client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.updateToolboxCreateRequest(ctx, name, defaultVersion, options)
	if err != nil {
		return ToolboxesClientUpdateToolboxResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return ToolboxesClientUpdateToolboxResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return ToolboxesClientUpdateToolboxResponse{}, err
	}
	resp, err := client.updateToolboxHandleResponse(httpResp)
	return resp, err
}

// updateToolboxCreateRequest creates the UpdateToolbox request.
func (client *ToolboxesClient) updateToolboxCreateRequest(ctx context.Context, name string, defaultVersion string, _ *ToolboxesClientUpdateToolboxOptions) (*policy.Request, error) {
	urlPath := "/toolboxes/{name}"
	var err error
	urlPath, err = replaceToolboxNamePathParameter(client.endpoint, urlPath, name)
	if err != nil {
		return nil, err
	}
	req, err := runtime.NewRequest(ctx, http.MethodPatch, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", versionV1)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	body := struct {
		Default_version string `json:"default_version"`
	}{
		Default_version: defaultVersion,
	}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// updateToolboxHandleResponse handles the UpdateToolbox response.
func (client *ToolboxesClient) updateToolboxHandleResponse(resp *http.Response) (ToolboxesClientUpdateToolboxResponse, error) {
	result := ToolboxesClientUpdateToolboxResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.ToolboxObject); err != nil {
		return ToolboxesClientUpdateToolboxResponse{}, err
	}
	return result, nil
}
