name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test Go Code (${{ matrix.target.name }}, Go ${{ matrix.go-version }})
    runs-on: ${{ matrix.target.runner }}
    
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.25', '1.26']
        target:
        - name: linux
          runner: ubuntu-latest
        - name: windows
          runner: windows-latest
        - name: windows-arm64
          runner: windows-11-arm
        - name: macos
          runner: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    
    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: go.sum
    
    - name: Run tests
      run: go test -v ${{ matrix.target.name != 'windows-arm64' && '-race' || '' }} -shuffle=on ./...

  conclusion:
    needs: [test]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Result
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled."
            exit 1
          fi
          echo "All jobs passed."
